// Generated by api2skill — do not edit by hand; re-run the generator instead.
// Usage: dotnet fsi call.fsx -- <operationId> [--<param> <value> ...] [--body <json|@file>]
open System
open System.Collections.Generic
open System.Diagnostics
open System.Net
open System.Net.Http
open System.Security.Cryptography
open System.Text
open System.Text.Json
open System.Text.Json.Nodes
open System.Threading.Tasks

type ParamSpec = { Name: string; Location: string }
type OperationSpec = { Method: string; PathTemplate: string; Parameters: ParamSpec list; HasBody: bool; BodyContentType: string option; SecuritySchemeIds: string list; AuthProfileNames: string list }
type SchemeSpec = { Id: string; Kind: string; ApiKeyName: string option; ApiKeyLocation: string option; OAuthTokenUrl: string option }
type TokenResponse = { AccessToken: string; RefreshToken: string option; ExpiresIn: int }

exception AuthResolutionException of string

let operations : Map<string, OperationSpec> =
    Map.ofList [
        "getPetById", { Method = "GET"; PathTemplate = "/pet/{petId}"; Parameters = [ { Name = "petId"; Location = "path" } ]; HasBody = false; BodyContentType = None; SecuritySchemeIds = [ "api_key" ]; AuthProfileNames = [] }
        "addPet", { Method = "POST"; PathTemplate = "/pet"; Parameters = []; HasBody = true; BodyContentType = Some "application/json"; SecuritySchemeIds = [ "petstore_auth" ]; AuthProfileNames = [] }
        "get_store_inventory", { Method = "GET"; PathTemplate = "/store/inventory"; Parameters = []; HasBody = false; BodyContentType = None; SecuritySchemeIds = [ "api_key" ]; AuthProfileNames = [] }
        "get_health", { Method = "GET"; PathTemplate = "/health"; Parameters = []; HasBody = false; BodyContentType = None; SecuritySchemeIds = []; AuthProfileNames = [] }
    ]

let schemes : Map<string, SchemeSpec> =
    Map.ofList [
        "api_key", { Id = "api_key"; Kind = "apiKey"; ApiKeyName = Some "api_key"; ApiKeyLocation = Some "header"; OAuthTokenUrl = None }
        "petstore_auth", { Id = "petstore_auth"; Kind = "oauth2"; ApiKeyName = None; ApiKeyLocation = None; OAuthTokenUrl = Some "https://petstore.example.com/oauth/token" }
    ]

let secretsPath = IO.Path.Combine(__SOURCE_DIRECTORY__, "..", "secrets.json")

let loadSecrets () : JsonElement option =
    if IO.File.Exists(secretsPath) then
        try
            use doc = JsonDocument.Parse(IO.File.ReadAllText(secretsPath))
            Some (doc.RootElement.Clone())
        with :? JsonException as ex ->
            eprintfn "warning: secrets.json is not valid JSON (%s); proceeding as if no secrets were configured." ex.Message
            None
    else
        None

let topLevelSecret (secrets: JsonElement option) (key: string) : string option =
    match secrets with
    | None -> None
    | Some root ->
        match root.TryGetProperty(key) with
        | true, v -> Some (v.GetString())
        | false, _ -> None

let schemeSecret (secrets: JsonElement option) (schemeId: string) (key: string) : string option =
    match secrets with
    | None -> None
    | Some root ->
        match root.TryGetProperty(schemeId) with
        | false, _ -> None
        | true, entry ->
            match entry.TryGetProperty(key) with
            | true, v -> Some (v.GetString())
            | false, _ -> None

let authConfigPath = IO.Path.Combine(__SOURCE_DIRECTORY__, "..", "auth.json")

let loadAuthConfig () : JsonElement option =
    if IO.File.Exists(authConfigPath) then
        try
            use doc = JsonDocument.Parse(IO.File.ReadAllText(authConfigPath))
            Some (doc.RootElement.Clone())
        with :? JsonException as ex ->
            raise (AuthResolutionException (sprintf "auth.json is not valid JSON (%s)." ex.Message))
    else
        None

let getProp (el: JsonElement) (name: string) : string =
    match el.TryGetProperty(name) with
    | true, v -> (match v.GetString() with | null -> "" | s -> s)
    | false, _ -> ""

let findProfile (profiles: JsonElement option) (name: string) : JsonElement option =
    match profiles with
    | Some arr when arr.ValueKind = JsonValueKind.Array ->
        arr.EnumerateArray()
        |> Seq.tryFind (fun p -> match p.TryGetProperty("name") with | true, n -> n.GetString() = name | false, _ -> false)
    | _ -> None

let resolveSecretOrLiteral (raw: string) (secrets: JsonElement option) : string =
    if raw.StartsWith("{secret:") && raw.EndsWith("}") then
        let key = raw.Substring(8, raw.Length - 9)
        let found =
            match secrets with
            | None -> None
            | Some root ->
                match root.TryGetProperty(key) with
                | true, value when value.GetString() <> null -> Some (value.GetString())
                | _ -> None
        match found with
        | Some s -> s
        | None -> raise (AuthResolutionException (sprintf "secrets.json has no value for \"%s\" (referenced by auth.json)." key))
    else
        raw

let parseArgs (rest: string[]) : Dictionary<string, string> * string option =
    let values = Dictionary<string, string>()
    let mutable body : string option = None
    let mutable i = 0
    while i < rest.Length do
        if rest.[i].StartsWith("--") && i + 1 < rest.Length then
            let key = rest.[i].Substring(2)
            let value = rest.[i + 1]
            if key = "body" then body <- Some value else values.[key] <- value
            i <- i + 2
        else
            i <- i + 1
    (values, body)

let fetchOAuth2Token (http: HttpClient) (tokenUrl: string) (clientId: string) (clientSecret: string) (tokenCache: Dictionary<string, string>) : Task<string option> =
    task {
        let cacheKey = tokenUrl + "|" + clientId
        match tokenCache.TryGetValue(cacheKey) with
        | true, cached -> return Some cached
        | false, _ ->

        let form = new FormUrlEncodedContent(dict [
            "grant_type", "client_credentials"
            "client_id", clientId
            "client_secret", clientSecret
        ])
        let! response = http.PostAsync(tokenUrl, form)
        if not response.IsSuccessStatusCode then
            return None
        else

        let! text = response.Content.ReadAsStringAsync()
        try
            use doc = JsonDocument.Parse(text)
            match doc.RootElement.TryGetProperty("access_token") with
            | false, _ -> return None
            | true, tokenEl ->
                let token = tokenEl.GetString()
                tokenCache.[cacheKey] <- token
                return Some token
        with :? JsonException ->
            // The token endpoint returned a 2xx with a body that isn't valid JSON — treat
            // the same as a failed token fetch rather than crashing the whole dispatch.
            return None
    }

let applyAuth (http: HttpClient) (scheme: SchemeSpec) (secrets: JsonElement option) (query: ResizeArray<string>) (headers: ResizeArray<string * string>) (tokenCache: Dictionary<string, string>) : Task<unit> =
    task {
        match scheme.Kind with
        | "apiKey" ->
            match schemeSecret secrets scheme.Id "apiKey" with
            | None -> eprintfn "warning: no apiKey configured for scheme '%s' in secrets.json — sending unauthenticated." scheme.Id
            | Some key ->
                let name = scheme.ApiKeyName |> Option.defaultValue ""
                if scheme.ApiKeyLocation = Some "query" then
                    query.Add(sprintf "%s=%s" (Uri.EscapeDataString(name)) (Uri.EscapeDataString(key)))
                else
                    headers.Add((name, key))
        | "bearer" ->
            match schemeSecret secrets scheme.Id "bearerToken" with
            | None -> eprintfn "warning: no bearerToken configured for scheme '%s' in secrets.json — sending unauthenticated." scheme.Id
            | Some token -> headers.Add(("Authorization", sprintf "Bearer %s" token))
        | "basic" ->
            let user = schemeSecret secrets scheme.Id "username"
            let pass = schemeSecret secrets scheme.Id "password"
            match user, pass with
            | Some u, Some p ->
                let encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes(sprintf "%s:%s" u p))
                headers.Add(("Authorization", sprintf "Basic %s" encoded))
            | _ -> eprintfn "warning: no username/password configured for scheme '%s' in secrets.json — sending unauthenticated." scheme.Id
        | "oauth2" ->
            let clientId = schemeSecret secrets scheme.Id "clientId"
            let clientSecret = schemeSecret secrets scheme.Id "clientSecret"
            let tokenUrl = (schemeSecret secrets scheme.Id "tokenUrl") |> Option.orElse scheme.OAuthTokenUrl
            match clientId, clientSecret, tokenUrl with
            | Some cid, Some cs, Some url ->
                let! token = fetchOAuth2Token http url cid cs tokenCache
                match token with
                | Some t -> headers.Add(("Authorization", sprintf "Bearer %s" t))
                | None -> eprintfn "warning: failed to obtain an OAuth2 token for scheme '%s' — sending unauthenticated." scheme.Id
            | _ -> eprintfn "warning: no clientId/clientSecret/tokenUrl configured for scheme '%s' in secrets.json — sending unauthenticated." scheme.Id
        | _ -> eprintfn "warning: scheme '%s' (%s) is not a supported auth kind — sending unauthenticated." scheme.Id scheme.Kind
    }

let generatePkce () : string * string =
    let bytes = Array.zeroCreate<byte> 32
    RandomNumberGenerator.Fill(bytes)
    let verifier = Convert.ToBase64String(bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
    let challengeBytes = SHA256.HashData(Encoding.ASCII.GetBytes(verifier))
    let challenge = Convert.ToBase64String(challengeBytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
    (verifier, challenge)

let generateState () : string =
    let bytes = Array.zeroCreate<byte> 16
    RandomNumberGenerator.Fill(bytes)
    Convert.ToBase64String(bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')

let parseQuery (query: string) : Dictionary<string, string> =
    let result = Dictionary<string, string>(StringComparer.Ordinal)
    let q = query.TrimStart('?')
    if q.Length > 0 then
        for pair in q.Split('&') do
            let idx = pair.IndexOf('=')
            if idx < 0 then
                result.[Uri.UnescapeDataString(pair)] <- ""
            else
                result.[Uri.UnescapeDataString(pair.Substring(0, idx))] <- Uri.UnescapeDataString(pair.Substring(idx + 1))
    result

let tryLaunchBrowser (url: string) : bool =
    try
        Process.Start(ProcessStartInfo(url, UseShellExecute = true)) |> ignore
        true
    with _ ->
        try
            if OperatingSystem.IsMacOS() then
                Process.Start("open", url) |> ignore
                true
            elif OperatingSystem.IsLinux() then
                Process.Start("xdg-open", url) |> ignore
                true
            elif OperatingSystem.IsWindows() then
                Process.Start(ProcessStartInfo("cmd", sprintf "/c start %s" url, CreateNoWindow = true)) |> ignore
                true
            else
                false
        with _ ->
            false

let runClipboardCommand (fileName: string) (args: string list) (text: string) : bool =
    try
        let psi = ProcessStartInfo(fileName, RedirectStandardInput = true, UseShellExecute = false, CreateNoWindow = true)
        for a in args do psi.ArgumentList.Add(a)
        use proc = Process.Start(psi)
        proc.StandardInput.Write(text)
        proc.StandardInput.Close()
        proc.WaitForExit()
        proc.ExitCode = 0
    with _ ->
        false

let tryCopyToClipboard (text: string) : bool =
    if OperatingSystem.IsMacOS() then
        runClipboardCommand "pbcopy" [] text
    elif OperatingSystem.IsWindows() then
        runClipboardCommand "clip" [] text
    elif OperatingSystem.IsLinux() then
        runClipboardCommand "wl-copy" [] text
        || runClipboardCommand "xclip" ["-selection"; "clipboard"] text
        || runClipboardCommand "xsel" ["--clipboard"; "--input"] text
    else
        false

let waitForCallbackAsync (callbackUrl: string) : Task<Dictionary<string, string>> =
    task {
        let uri = Uri(callbackUrl)
        let prefix = sprintf "%s://%s:%d/" uri.Scheme uri.Host uri.Port
        use listener = new HttpListener()
        listener.Prefixes.Add(prefix)
        try
            listener.Start()
        with :? HttpListenerException as ex ->
            raise (AuthResolutionException (sprintf "Could not start the local OAuth callback listener on %s (%s). Another process may be using this port \u2014 try a different callbackUrl in auth.json." prefix ex.Message))
        let! context = listener.GetContextAsync()
        let queryString = if isNull (box context.Request.Url) then "" else context.Request.Url.Query
        let result = parseQuery queryString
        let page = Encoding.UTF8.GetBytes("<html><body>Login complete \u2014 you can close this window and return to the terminal.</body></html>")
        context.Response.ContentType <- "text/html"
        context.Response.ContentLength64 <- int64 page.Length
        context.Response.OutputStream.Write(page, 0, page.Length)
        context.Response.OutputStream.Close()
        listener.Stop()
        return result
    }

let resolveOAuthEndpoints (profile: JsonElement) : string option * string option * string list =
    let preset = getProp profile "preset"
    let tenant = getProp profile "tenant"
    let explicitAuthUrl = match profile.TryGetProperty("authUrl") with | true, v -> Some (v.GetString()) | false, _ -> None
    let explicitTokenUrl = match profile.TryGetProperty("tokenUrl") with | true, v -> Some (v.GetString()) | false, _ -> None
    let scopes =
        match profile.TryGetProperty("scopes") with
        | true, scopesEl when scopesEl.ValueKind = JsonValueKind.Array ->
            scopesEl.EnumerateArray() |> Seq.choose (fun s -> match s.GetString() with | null -> None | sv -> Some sv) |> List.ofSeq
        | _ -> []
    if String.Equals(preset, "entra", StringComparison.OrdinalIgnoreCase) then
        let authUrl = explicitAuthUrl |> Option.orElseWith (fun () -> if tenant.Length > 0 then Some (sprintf "https://login.microsoftonline.com/%s/oauth2/v2.0/authorize" tenant) else None)
        let tokenUrl = explicitTokenUrl |> Option.orElseWith (fun () -> if tenant.Length > 0 then Some (sprintf "https://login.microsoftonline.com/%s/oauth2/v2.0/token" tenant) else None)
        let scopesWithOffline = if List.contains "offline_access" scopes then scopes else scopes @ ["offline_access"]
        (authUrl, tokenUrl, scopesWithOffline)
    else
        (explicitAuthUrl, explicitTokenUrl, scopes)

let buildAuthorizeUrl (authUrl: string) (clientId: string) (callbackUrl: string) (scopes: string list) (challenge: string) (state: string) (profile: JsonElement) : string =
    let qs = ResizeArray<string>()
    qs.Add("response_type=code")
    qs.Add(sprintf "client_id=%s" (Uri.EscapeDataString(clientId)))
    qs.Add(sprintf "redirect_uri=%s" (Uri.EscapeDataString(callbackUrl)))
    qs.Add(sprintf "code_challenge=%s" (Uri.EscapeDataString(challenge)))
    qs.Add("code_challenge_method=S256")
    qs.Add(sprintf "state=%s" (Uri.EscapeDataString(state)))
    if not (List.isEmpty scopes) then
        qs.Add(sprintf "scope=%s" (Uri.EscapeDataString(String.concat " " scopes)))
    match profile.TryGetProperty("authorizeRequest") with
    | true, arEl ->
        match arEl.TryGetProperty("body") with
        | true, bodyEl when bodyEl.ValueKind = JsonValueKind.Object ->
            for prop in bodyEl.EnumerateObject() do
                qs.Add(sprintf "%s=%s" (Uri.EscapeDataString(prop.Name)) (Uri.EscapeDataString(match prop.Value.GetString() with | null -> "" | s -> s)))
        | _ -> ()
    | _ -> ()
    let sep = if authUrl.Contains('?') then "&" else "?"
    authUrl + sep + String.concat "&" qs

let postTokenRequestAsync (http: HttpClient) (profile: JsonElement) (tokenUrl: string) (clientId: string) (form: Dictionary<string, string>) (secrets: JsonElement option) : Task<TokenResponse option> =
    task {
        let clientAuth = getProp profile "clientAuth"
        let clientSecretRaw = match profile.TryGetProperty("clientSecret") with | true, v -> (match v.GetString() with | null -> None | s -> Some s) | false, _ -> None
        let clientSecret =
            match clientSecretRaw with
            | Some raw when raw.Length > 0 -> Some (resolveSecretOrLiteral raw secrets)
            | _ -> None

        use request = new HttpRequestMessage(HttpMethod.Post, tokenUrl)
        match clientAuth, clientSecret with
        | "basic", Some cs ->
            form.Remove("client_id") |> ignore
            let basic = Convert.ToBase64String(Encoding.UTF8.GetBytes(sprintf "%s:%s" clientId cs))
            request.Headers.TryAddWithoutValidation("Authorization", sprintf "Basic %s" basic) |> ignore
        | _, Some cs ->
            form.["client_secret"] <- cs
        | _ -> ()

        match profile.TryGetProperty("tokenRequest") with
        | true, trEl ->
            match trEl.TryGetProperty("headers") with
            | true, hEl when hEl.ValueKind = JsonValueKind.Object ->
                for prop in hEl.EnumerateObject() do
                    request.Headers.TryAddWithoutValidation(prop.Name, (match prop.Value.GetString() with | null -> "" | s -> s)) |> ignore
            | _ -> ()
            match trEl.TryGetProperty("body") with
            | true, bEl when bEl.ValueKind = JsonValueKind.Object ->
                for prop in bEl.EnumerateObject() do
                    form.[prop.Name] <- (match prop.Value.GetString() with | null -> "" | s -> s)
            | _ -> ()
        | _ -> ()

        request.Content <- new FormUrlEncodedContent(form)
        let! response = http.SendAsync(request)
        let! text = response.Content.ReadAsStringAsync()
        if not response.IsSuccessStatusCode then
            return None
        else
            try
                use doc = JsonDocument.Parse(text)
                let root = doc.RootElement
                match root.TryGetProperty("access_token") with
                | true, atEl when atEl.GetString() <> null ->
                    let accessToken = atEl.GetString()
                    let refreshToken = match root.TryGetProperty("refresh_token") with | true, rtEl -> (match rtEl.GetString() with | null -> None | s -> Some s) | false, _ -> None
                    let expiresIn = match root.TryGetProperty("expires_in") with | true, eiEl -> (match eiEl.TryGetInt32() with | true, ei -> ei | false, _ -> 3600) | false, _ -> 3600
                    return Some { AccessToken = accessToken; RefreshToken = refreshToken; ExpiresIn = expiresIn }
                | _ -> return None
            with :? JsonException ->
                return None
    }

let exchangeCodeForTokenAsync (http: HttpClient) (profile: JsonElement) (tokenUrl: string) (clientId: string) (code: string) (verifier: string) (callbackUrl: string) (secrets: JsonElement option) : Task<TokenResponse option> =
    let form = Dictionary<string, string>(StringComparer.Ordinal)
    form.["grant_type"] <- "authorization_code"
    form.["code"] <- code
    form.["redirect_uri"] <- callbackUrl
    form.["code_verifier"] <- verifier
    form.["client_id"] <- clientId
    postTokenRequestAsync http profile tokenUrl clientId form secrets

let fetchClientCredentialsTokenAsync (http: HttpClient) (profile: JsonElement) (tokenUrl: string) (clientId: string) (secrets: JsonElement option) : Task<TokenResponse option> =
    let form = Dictionary<string, string>(StringComparer.Ordinal)
    form.["grant_type"] <- "client_credentials"
    form.["client_id"] <- clientId
    postTokenRequestAsync http profile tokenUrl clientId form secrets

let refreshOAuthTokenAsync (http: HttpClient) (profile: JsonElement) (tokenUrl: string) (clientId: string) (refreshToken: string) (secrets: JsonElement option) : Task<TokenResponse option> =
    let form = Dictionary<string, string>(StringComparer.Ordinal)
    form.["grant_type"] <- "refresh_token"
    form.["refresh_token"] <- refreshToken
    form.["client_id"] <- clientId
    postTokenRequestAsync http profile tokenUrl clientId form secrets

let tokenCachePath = IO.Path.Combine(__SOURCE_DIRECTORY__, "..", ".auth-cache.json")

let readTokenCacheAsync (path: string) : Task<Dictionary<string, JsonElement>> =
    task {
        let result = Dictionary<string, JsonElement>(StringComparer.Ordinal)
        if IO.File.Exists(path) then
            try
                let! text = IO.File.ReadAllTextAsync(path)
                use doc = JsonDocument.Parse(text)
                for prop in doc.RootElement.EnumerateObject() do
                    result.[prop.Name] <- prop.Value.Clone()
            with :? JsonException -> ()
        return result
    }

let writeTokenCacheAsync (path: string) (cache: Dictionary<string, JsonElement>) : Task<unit> =
    task {
        let obj = JsonObject()
        for kv in cache do
            obj.[kv.Key] <- JsonNode.Parse(kv.Value.GetRawText())
        let tmpPath = path + ".tmp-" + Guid.NewGuid().ToString("N")
        do! IO.File.WriteAllTextAsync(tmpPath, obj.ToJsonString(JsonSerializerOptions(WriteIndented = true)))
        if not (OperatingSystem.IsWindows()) then
            IO.File.SetUnixFileMode(tmpPath, IO.UnixFileMode.UserRead ||| IO.UnixFileMode.UserWrite)
        IO.File.Move(tmpPath, path, true)
    }

let storeTokenInCache (cache: Dictionary<string, JsonElement>) (profileName: string) (token: TokenResponse) : unit =
    let obj = JsonObject()
    obj.["access_token"] <- JsonValue.Create(token.AccessToken)
    obj.["expires_at"] <- JsonValue.Create(DateTimeOffset.UtcNow.AddSeconds(float token.ExpiresIn).ToString("o"))
    (match token.RefreshToken with
     | Some rt -> obj.["refresh_token"] <- JsonValue.Create(rt)
     | None -> ())
    cache.[profileName] <- JsonDocument.Parse(obj.ToJsonString()).RootElement.Clone()

let withTokenCacheLockAsync<'T> (action: unit -> Task<'T>) : Task<'T> =
    task {
        let lockPath = tokenCachePath + ".lock"
        let mutable lockStream : IO.FileStream option = None
        let mutable attempt = 0
        while lockStream.IsNone && attempt < 100 do
            try
                lockStream <- Some (new IO.FileStream(lockPath, IO.FileMode.OpenOrCreate, IO.FileAccess.ReadWrite, IO.FileShare.None))
            with :? IO.IOException ->
                do! Task.Delay(50)
            attempt <- attempt + 1
        if lockStream.IsNone then
            raise (AuthResolutionException "Could not acquire the token cache lock (.auth-cache.json.lock) after multiple attempts \u2014 another process may be stuck holding it.")
        let stream = lockStream.Value
        try
            return! action ()
        finally
            stream.Dispose()
    }

let tryClientCredentialsOrFail (http: HttpClient) (profile: JsonElement) (profileName: string) (tokenUrl: string) (clientId: string) (grant: string) (secrets: JsonElement option) (cache: Dictionary<string, JsonElement>) : Task<string> =
    task {
        if grant = "client_credentials" then
            let! fetched = fetchClientCredentialsTokenAsync http profile tokenUrl clientId secrets
            match fetched with
            | Some tr ->
                storeTokenInCache cache profileName tr
                do! writeTokenCacheAsync tokenCachePath cache
                return tr.AccessToken
            | None ->
                return raise (AuthResolutionException (sprintf "Failed to obtain a client_credentials token for auth profile '%s'." profileName))
        else
            return raise (AuthResolutionException (sprintf "No valid or refreshable token for auth profile '%s'. Run: dotnet fsi scripts/call.fsx -- login %s" profileName profileName))
    }

let resolveOAuthAccessTokenAsync (http: HttpClient) (profile: JsonElement) (profileName: string) (secrets: JsonElement option) : Task<string> =
    task {
        let (_, tokenUrlOpt, _) = resolveOAuthEndpoints profile
        match tokenUrlOpt with
        | None ->
            return raise (AuthResolutionException (sprintf "Auth profile '%s' (oauth2) has no tokenUrl configured (directly or via a preset)." profileName))
        | Some tokenUrl ->

        let clientId = resolveSecretOrLiteral (getProp profile "clientId") secrets
        let grant = getProp profile "grant"

        return! withTokenCacheLockAsync (fun () ->
            task {
                let! cache = readTokenCacheAsync tokenCachePath
                match cache.TryGetValue(profileName) with
                | false, _ ->
                    return! tryClientCredentialsOrFail http profile profileName tokenUrl clientId grant secrets cache
                | true, entry ->
                    let expiresAt =
                        match entry.TryGetProperty("expires_at") with
                        | true, eaEl -> (match DateTimeOffset.TryParse(eaEl.GetString()) with | true, ea -> ea | false, _ -> DateTimeOffset.MinValue)
                        | false, _ -> DateTimeOffset.MinValue
                    let cachedToken = match entry.TryGetProperty("access_token") with | true, atEl -> (match atEl.GetString() with | null -> None | s -> Some s) | false, _ -> None
                    match cachedToken with
                    | Some token when expiresAt > DateTimeOffset.UtcNow.AddSeconds(30.0) ->
                        return token
                    | _ ->
                        let refreshToken = match entry.TryGetProperty("refresh_token") with | true, rtEl -> (match rtEl.GetString() with | null -> None | s -> Some s) | false, _ -> None
                        match refreshToken with
                        | None ->
                            return! tryClientCredentialsOrFail http profile profileName tokenUrl clientId grant secrets cache
                        | Some rt ->
                            let! refreshed = refreshOAuthTokenAsync http profile tokenUrl clientId rt secrets
                            match refreshed with
                            | Some tr ->
                                storeTokenInCache cache profileName tr
                                do! writeTokenCacheAsync tokenCachePath cache
                                return tr.AccessToken
                            | None ->
                                return! tryClientCredentialsOrFail http profile profileName tokenUrl clientId grant secrets cache
            })
    }

let runScriptCommandAsync (command: string) : Task<int * string * string> =
    task {
        let psi = ProcessStartInfo()
        psi.RedirectStandardOutput <- true
        psi.RedirectStandardError <- true
        psi.UseShellExecute <- false
        if OperatingSystem.IsWindows() then
            psi.FileName <- "cmd.exe"
            psi.ArgumentList.Add("/c") |> ignore
            psi.ArgumentList.Add(command) |> ignore
        else
            psi.FileName <- "/bin/sh"
            psi.ArgumentList.Add("-c") |> ignore
            psi.ArgumentList.Add(command) |> ignore
        use proc = Process.Start(psi)
        let! stdout = proc.StandardOutput.ReadToEndAsync()
        let! stderr = proc.StandardError.ReadToEndAsync()
        do! proc.WaitForExitAsync()
        return (proc.ExitCode, stdout, stderr)
    }

let applyExplicitProfileAsync (http: HttpClient) (profile: JsonElement) (profileName: string) (secrets: JsonElement option) (query: ResizeArray<string>) (headers: ResizeArray<string * string>) : Task<unit> =
    task {
        let profType = getProp profile "type"
        match profType with
        | "bearer" ->
            let token = resolveSecretOrLiteral (getProp profile "token") secrets
            let value = if token.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase) then token else sprintf "Bearer %s" token
            headers.Add(("Authorization", value))
        | "basic" ->
            let user = resolveSecretOrLiteral (getProp profile "username") secrets
            let pass = resolveSecretOrLiteral (getProp profile "password") secrets
            let encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes(sprintf "%s:%s" user pass))
            headers.Add(("Authorization", sprintf "Basic %s" encoded))
        | "custom" ->
            match profile.TryGetProperty("headers") with
            | true, headersEl when headersEl.ValueKind = JsonValueKind.Array ->
                for h in headersEl.EnumerateArray() do
                    let name = getProp h "name"
                    let value = resolveSecretOrLiteral (getProp h "value") secrets
                    headers.Add((name, value))
            | _ -> ()
        | "oauth2" ->
            let! accessToken = resolveOAuthAccessTokenAsync http profile profileName secrets
            headers.Add(("Authorization", sprintf "Bearer %s" accessToken))
        | "script" ->
            let command = getProp profile "command"
            let headerName =
                let h = getProp profile "header"
                if String.IsNullOrEmpty(h) then "Authorization" else h
            let bearerPrefix =
                match profile.TryGetProperty("bearerPrefix") with
                | true, v -> v.ValueKind = JsonValueKind.True
                | _ -> false
            let! exitCode, stdout, stderr = runScriptCommandAsync command
            if exitCode <> 0 then
                return raise (AuthResolutionException (sprintf "Script command for auth profile '%s' exited with code %d: %s" profileName exitCode (stderr.Trim())))
            let token = stdout.Trim()
            let value = if bearerPrefix && not (token.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase)) then sprintf "Bearer %s" token else token
            headers.Add((headerName, value))
        | other ->
            raise (AuthResolutionException (sprintf "Auth profile type '%s' is not supported by this generated dispatcher yet." other))
    }

let loginAsync (profileName: string) : Task<int> =
    task {
        try
            let authConfig = loadAuthConfig ()
            let profilesEl =
                match authConfig with
                | Some cfg -> (match cfg.TryGetProperty("profiles") with | true, p -> Some p | false, _ -> None)
                | None -> None
            match findProfile profilesEl profileName with
            | None ->
                eprintfn "No auth profile named '%s' in auth.json." profileName
                return 2
            | Some profile ->

            let profType = getProp profile "type"
            if profType <> "oauth2" then
                eprintfn "Profile '%s' is type '%s', not 'oauth2' \u2014 login is only applicable to oauth2 profiles." profileName profType
                return 2
            else

            let grant = getProp profile "grant"
            if grant = "client_credentials" then
                printfn "Profile '%s' uses client_credentials \u2014 not applicable: no interactive login is needed, a token is obtained automatically at call time." profileName
                return 0
            else

            let (authUrlOpt, tokenUrlOpt, scopes) = resolveOAuthEndpoints profile
            match authUrlOpt, tokenUrlOpt with
            | None, _ | _, None ->
                eprintfn "Profile '%s' is missing authUrl/tokenUrl (directly or via a preset)." profileName
                return 2
            | Some authUrl, Some tokenUrl ->

            let callbackUrlRaw = getProp profile "callbackUrl"
            let callbackUrl = if callbackUrlRaw.Length = 0 then "http://localhost:8400/callback" else callbackUrlRaw
            let secrets = loadSecrets ()
            let clientId = resolveSecretOrLiteral (getProp profile "clientId") secrets

            let (verifier, challenge) = generatePkce ()
            let state = generateState ()
            let authorizeUrl = buildAuthorizeUrl authUrl clientId callbackUrl scopes challenge state profile

            let browserLaunch = getProp profile "browserLaunch"
            if browserLaunch = "clipboard" then
                let copied = tryCopyToClipboard authorizeUrl
                printfn "%s" (if copied then sprintf "Copied the sign-in URL to your clipboard for profile '%s'. Paste it into your browser:" profileName else sprintf "Could not copy the sign-in URL to the clipboard automatically. Open this URL to sign in for profile '%s':" profileName)
                printfn "%s" authorizeUrl
            else
                printfn "Opening your browser to sign in for profile '%s'..." profileName
                let browserLaunched = tryLaunchBrowser authorizeUrl
                printfn "%s" (if browserLaunched then "If it did not open, visit this URL to sign in:" else "Could not launch a browser automatically. Open this URL to sign in:")
                printfn "%s" authorizeUrl

            let! callbackParams = waitForCallbackAsync callbackUrl

            let stateMatches = match callbackParams.TryGetValue("state") with | true, returnedState -> returnedState = state | false, _ -> false
            if not stateMatches then
                eprintfn "The callback's state did not match what was sent \u2014 rejecting (possible CSRF/mix-up). No token was stored. Run login again."
                return 2
            else

            match callbackParams.TryGetValue("code") with
            | false, _ ->
                let err = match callbackParams.TryGetValue("error") with | true, e -> e | false, _ -> "no authorization code was returned"
                eprintfn "Login failed: %s" err
                return 2
            | true, code ->

            use http = new HttpClient()
            let! tokenResponse = exchangeCodeForTokenAsync http profile tokenUrl clientId code verifier callbackUrl secrets
            match tokenResponse with
            | None ->
                eprintfn "Failed to exchange the authorization code for a token."
                return 2
            | Some tr ->

            do! withTokenCacheLockAsync (fun () ->
                task {
                    let! cache = readTokenCacheAsync tokenCachePath
                    storeTokenInCache cache profileName tr
                    do! writeTokenCacheAsync tokenCachePath cache
                })

            printfn "Login succeeded for profile '%s'. You can now call operations that use it." profileName
            return 0
        with AuthResolutionException msg ->
            eprintfn "%s" msg
            return 2
    }

let run (args: string[]) : Task<int> =
    task {
        if args.Length > 0 && args.[0] = "login" then
            if args.Length < 2 then
                eprintfn "Usage: dotnet fsi call.fsx -- login <profile>"
                return 2
            else
                return! loginAsync args.[1]
        else

        if args.Length = 0 || args.[0] = "-h" || args.[0] = "--help" then
            eprintfn "Usage: dotnet fsi call.fsx -- <operationId> [--<param> <value> ...] [--body <json|@file>]"
            eprintfn "Known operations: %s" (String.concat ", " (operations.Keys |> Seq.sort))
            return 2
        else

        let operationId = args.[0]
        match operations.TryFind(operationId) with
        | None ->
            eprintfn "Unknown operationId '%s'." operationId
            eprintfn "Known operations: %s" (String.concat ", " (operations.Keys |> Seq.sort))
            return 2
        | Some op ->

        let (paramValues, bodyOpt) = parseArgs (args.[1..])
        let secrets = loadSecrets ()

        let configuredBaseUrl = (topLevelSecret secrets "baseUrl") |> Option.defaultValue "https://petstore.example.com/v2"
        let baseUrl =
            match Environment.GetEnvironmentVariable("API2SKILL_BASE_URL") with
            | null -> configuredBaseUrl
            | v -> v
        if String.IsNullOrWhiteSpace(baseUrl) then
            eprintfn "No base URL configured. Set API2SKILL_BASE_URL or add \"baseUrl\" to secrets.json."
            return 2
        else

        let mutable path = op.PathTemplate
        let query = ResizeArray<string>()
        let headers = ResizeArray<string * string>()
        for p in op.Parameters do
            match paramValues.TryGetValue(p.Name) with
            | false, _ -> ()
            | true, value ->
                match p.Location with
                | "path" -> path <- path.Replace("{" + p.Name + "}", Uri.EscapeDataString(value))
                | "query" -> query.Add(sprintf "%s=%s" (Uri.EscapeDataString(p.Name)) (Uri.EscapeDataString(value)))
                | "header" -> headers.Add((p.Name, value))
                | _ -> ()

        use handler = new HttpClientHandler()
        let insecureDefault = "0"
        let insecure =
            match Environment.GetEnvironmentVariable("API2SKILL_INSECURE") with
            | null -> insecureDefault
            | v -> v
        if insecure = "1" then
            // Dev-only: accepts self-signed/invalid TLS certificates. Never enable in production.
            handler.ServerCertificateCustomValidationCallback <- HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
        use http = new HttpClient(handler)

        try
            let tokenCache = Dictionary<string, string>()
            if not (List.isEmpty op.AuthProfileNames) then
                let authConfig = loadAuthConfig ()
                let profilesEl =
                    match authConfig with
                    | Some cfg -> (match cfg.TryGetProperty("profiles") with | true, p -> Some p | false, _ -> None)
                    | None -> None
                for profileName in op.AuthProfileNames do
                    match findProfile profilesEl profileName with
                    | None -> raise (AuthResolutionException (sprintf "auth.json has no profile named '%s' (referenced by operation '%s')." profileName operationId))
                    | Some profile -> do! applyExplicitProfileAsync http profile profileName secrets query headers
            else
                for schemeId in op.SecuritySchemeIds do
                    match schemes.TryFind(schemeId) with
                    | None -> ()
                    | Some scheme -> do! applyAuth http scheme secrets query headers tokenCache

            let url =
                baseUrl.TrimEnd('/') + path +
                (if query.Count > 0 then "?" + String.concat "&" query else "")

            let invalidHeaderName =
                headers |> Seq.tryPick (fun (n, v) -> if v.IndexOfAny([| '\r'; '\n' |]) >= 0 then Some n else None)
            if invalidHeaderName.IsSome then
                eprintfn "Invalid value for header '%s': control characters are not allowed." invalidHeaderName.Value
                return 2
            else

            use request = new HttpRequestMessage(HttpMethod(op.Method), url)
            for (name, value) in headers do
                request.Headers.TryAddWithoutValidation(name, value) |> ignore

            if op.HasBody then
                let bodyText = bodyOpt |> Option.defaultValue "{}"
                let resolvedBody = if bodyText.StartsWith('@') then IO.File.ReadAllText(bodyText.Substring(1)) else bodyText
                let contentType = op.BodyContentType |> Option.defaultValue "application/json"
                request.Content <- new StringContent(resolvedBody, Encoding.UTF8, contentType)

            let! response = http.SendAsync(request)
            let! responseText = response.Content.ReadAsStringAsync()
            printfn "%s" responseText
            if not response.IsSuccessStatusCode then
                eprintfn "HTTP %d %s" (int response.StatusCode) (string response.StatusCode)
                return 1
            else
                return 0
        with
        | AuthResolutionException msg ->
            eprintfn "%s" msg
            return 2
        | :? HttpRequestException as ex ->
            eprintfn "Network error calling %s: %s" baseUrl ex.Message
            return 3
    }

let exitCode = run fsi.CommandLineArgs.[1..] |> Async.AwaitTask |> Async.RunSynchronously
exit exitCode
