// Generated by api2skill — do not edit by hand; re-run the generator instead.
// Usage: dotnet fsi call.fsx -- <operationId> [--<param> <value> ...] [--body <json|@file>]
open System
open System.Collections.Generic
open System.Net.Http
open System.Text
open System.Text.Json
open System.Threading.Tasks

type ParamSpec = { Name: string; Location: string }
type OperationSpec = { Method: string; PathTemplate: string; Parameters: ParamSpec list; HasBody: bool; BodyContentType: string option; SecuritySchemeIds: string list; AuthProfileNames: string list }
type SchemeSpec = { Id: string; Kind: string; ApiKeyName: string option; ApiKeyLocation: string option; OAuthTokenUrl: string option }

exception AuthResolutionException of string

let operations : Map<string, OperationSpec> =
    Map.ofList [
        "getPetById", { Method = "GET"; PathTemplate = "/pet/{petId}"; Parameters = [ { Name = "petId"; Location = "path" } ]; HasBody = false; BodyContentType = None; SecuritySchemeIds = [ "api_key" ]; AuthProfileNames = [] }
        "addPet", { Method = "POST"; PathTemplate = "/pet"; Parameters = []; HasBody = true; BodyContentType = Some "application/json"; SecuritySchemeIds = [ "petstore_auth" ]; AuthProfileNames = [] }
        "get_store_inventory", { Method = "GET"; PathTemplate = "/store/inventory"; Parameters = []; HasBody = false; BodyContentType = None; SecuritySchemeIds = [ "api_key" ]; AuthProfileNames = [] }
        "get_health", { Method = "GET"; PathTemplate = "/health"; Parameters = []; HasBody = false; BodyContentType = None; SecuritySchemeIds = []; AuthProfileNames = [] }
    ]

let schemes : Map<string, SchemeSpec> =
    Map.ofList [
        "api_key", { Id = "api_key"; Kind = "apiKey"; ApiKeyName = Some "api_key"; ApiKeyLocation = Some "header"; OAuthTokenUrl = None }
        "petstore_auth", { Id = "petstore_auth"; Kind = "oauth2"; ApiKeyName = None; ApiKeyLocation = None; OAuthTokenUrl = Some "https://petstore.example.com/oauth/token" }
    ]

let secretsPath = IO.Path.Combine(__SOURCE_DIRECTORY__, "..", "secrets.json")

let loadSecrets () : JsonElement option =
    if IO.File.Exists(secretsPath) then
        try
            use doc = JsonDocument.Parse(IO.File.ReadAllText(secretsPath))
            Some (doc.RootElement.Clone())
        with :? JsonException as ex ->
            eprintfn "warning: secrets.json is not valid JSON (%s); proceeding as if no secrets were configured." ex.Message
            None
    else
        None

let topLevelSecret (secrets: JsonElement option) (key: string) : string option =
    match secrets with
    | None -> None
    | Some root ->
        match root.TryGetProperty(key) with
        | true, v -> Some (v.GetString())
        | false, _ -> None

let schemeSecret (secrets: JsonElement option) (schemeId: string) (key: string) : string option =
    match secrets with
    | None -> None
    | Some root ->
        match root.TryGetProperty(schemeId) with
        | false, _ -> None
        | true, entry ->
            match entry.TryGetProperty(key) with
            | true, v -> Some (v.GetString())
            | false, _ -> None

let authConfigPath = IO.Path.Combine(__SOURCE_DIRECTORY__, "..", "auth.json")

let loadAuthConfig () : JsonElement option =
    if IO.File.Exists(authConfigPath) then
        try
            use doc = JsonDocument.Parse(IO.File.ReadAllText(authConfigPath))
            Some (doc.RootElement.Clone())
        with :? JsonException as ex ->
            raise (AuthResolutionException (sprintf "auth.json is not valid JSON (%s)." ex.Message))
    else
        None

let getProp (el: JsonElement) (name: string) : string =
    match el.TryGetProperty(name) with
    | true, v -> (match v.GetString() with | null -> "" | s -> s)
    | false, _ -> ""

let findProfile (profiles: JsonElement option) (name: string) : JsonElement option =
    match profiles with
    | Some arr when arr.ValueKind = JsonValueKind.Array ->
        arr.EnumerateArray()
        |> Seq.tryFind (fun p -> match p.TryGetProperty("name") with | true, n -> n.GetString() = name | false, _ -> false)
    | _ -> None

let resolveSecretOrLiteral (raw: string) (secrets: JsonElement option) : string =
    if raw.StartsWith("{secret:") && raw.EndsWith("}") then
        let key = raw.Substring(8, raw.Length - 9)
        let found =
            match secrets with
            | None -> None
            | Some root ->
                match root.TryGetProperty(key) with
                | true, value when value.GetString() <> null -> Some (value.GetString())
                | _ -> None
        match found with
        | Some s -> s
        | None -> raise (AuthResolutionException (sprintf "secrets.json has no value for \"%s\" (referenced by auth.json)." key))
    else
        raw

let applyExplicitProfile (profile: JsonElement) (secrets: JsonElement option) (query: ResizeArray<string>) (headers: ResizeArray<string * string>) : unit =
    let profType = getProp profile "type"
    match profType with
    | "bearer" ->
        let token = resolveSecretOrLiteral (getProp profile "token") secrets
        let value = if token.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase) then token else sprintf "Bearer %s" token
        headers.Add(("Authorization", value))
    | "basic" ->
        let user = resolveSecretOrLiteral (getProp profile "username") secrets
        let pass = resolveSecretOrLiteral (getProp profile "password") secrets
        let encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes(sprintf "%s:%s" user pass))
        headers.Add(("Authorization", sprintf "Basic %s" encoded))
    | "custom" ->
        match profile.TryGetProperty("headers") with
        | true, headersEl when headersEl.ValueKind = JsonValueKind.Array ->
            for h in headersEl.EnumerateArray() do
                let name = getProp h "name"
                let value = resolveSecretOrLiteral (getProp h "value") secrets
                headers.Add((name, value))
        | _ -> ()
    | other ->
        raise (AuthResolutionException (sprintf "Auth profile type '%s' is not supported by this generated dispatcher yet." other))

let parseArgs (rest: string[]) : Dictionary<string, string> * string option =
    let values = Dictionary<string, string>()
    let mutable body : string option = None
    let mutable i = 0
    while i < rest.Length do
        if rest.[i].StartsWith("--") && i + 1 < rest.Length then
            let key = rest.[i].Substring(2)
            let value = rest.[i + 1]
            if key = "body" then body <- Some value else values.[key] <- value
            i <- i + 2
        else
            i <- i + 1
    (values, body)

let fetchOAuth2Token (http: HttpClient) (tokenUrl: string) (clientId: string) (clientSecret: string) (tokenCache: Dictionary<string, string>) : Task<string option> =
    task {
        let cacheKey = tokenUrl + "|" + clientId
        match tokenCache.TryGetValue(cacheKey) with
        | true, cached -> return Some cached
        | false, _ ->

        let form = new FormUrlEncodedContent(dict [
            "grant_type", "client_credentials"
            "client_id", clientId
            "client_secret", clientSecret
        ])
        let! response = http.PostAsync(tokenUrl, form)
        if not response.IsSuccessStatusCode then
            return None
        else

        let! text = response.Content.ReadAsStringAsync()
        try
            use doc = JsonDocument.Parse(text)
            match doc.RootElement.TryGetProperty("access_token") with
            | false, _ -> return None
            | true, tokenEl ->
                let token = tokenEl.GetString()
                tokenCache.[cacheKey] <- token
                return Some token
        with :? JsonException ->
            // The token endpoint returned a 2xx with a body that isn't valid JSON — treat
            // the same as a failed token fetch rather than crashing the whole dispatch.
            return None
    }

let applyAuth (http: HttpClient) (scheme: SchemeSpec) (secrets: JsonElement option) (query: ResizeArray<string>) (headers: ResizeArray<string * string>) (tokenCache: Dictionary<string, string>) : Task<unit> =
    task {
        match scheme.Kind with
        | "apiKey" ->
            match schemeSecret secrets scheme.Id "apiKey" with
            | None -> eprintfn "warning: no apiKey configured for scheme '%s' in secrets.json — sending unauthenticated." scheme.Id
            | Some key ->
                let name = scheme.ApiKeyName |> Option.defaultValue ""
                if scheme.ApiKeyLocation = Some "query" then
                    query.Add(sprintf "%s=%s" (Uri.EscapeDataString(name)) (Uri.EscapeDataString(key)))
                else
                    headers.Add((name, key))
        | "bearer" ->
            match schemeSecret secrets scheme.Id "bearerToken" with
            | None -> eprintfn "warning: no bearerToken configured for scheme '%s' in secrets.json — sending unauthenticated." scheme.Id
            | Some token -> headers.Add(("Authorization", sprintf "Bearer %s" token))
        | "basic" ->
            let user = schemeSecret secrets scheme.Id "username"
            let pass = schemeSecret secrets scheme.Id "password"
            match user, pass with
            | Some u, Some p ->
                let encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes(sprintf "%s:%s" u p))
                headers.Add(("Authorization", sprintf "Basic %s" encoded))
            | _ -> eprintfn "warning: no username/password configured for scheme '%s' in secrets.json — sending unauthenticated." scheme.Id
        | "oauth2" ->
            let clientId = schemeSecret secrets scheme.Id "clientId"
            let clientSecret = schemeSecret secrets scheme.Id "clientSecret"
            let tokenUrl = (schemeSecret secrets scheme.Id "tokenUrl") |> Option.orElse scheme.OAuthTokenUrl
            match clientId, clientSecret, tokenUrl with
            | Some cid, Some cs, Some url ->
                let! token = fetchOAuth2Token http url cid cs tokenCache
                match token with
                | Some t -> headers.Add(("Authorization", sprintf "Bearer %s" t))
                | None -> eprintfn "warning: failed to obtain an OAuth2 token for scheme '%s' — sending unauthenticated." scheme.Id
            | _ -> eprintfn "warning: no clientId/clientSecret/tokenUrl configured for scheme '%s' in secrets.json — sending unauthenticated." scheme.Id
        | _ -> eprintfn "warning: scheme '%s' (%s) is not a supported auth kind — sending unauthenticated." scheme.Id scheme.Kind
    }

let run (args: string[]) : Task<int> =
    task {
        if args.Length = 0 || args.[0] = "-h" || args.[0] = "--help" then
            eprintfn "Usage: dotnet fsi call.fsx -- <operationId> [--<param> <value> ...] [--body <json|@file>]"
            eprintfn "Known operations: %s" (String.concat ", " (operations.Keys |> Seq.sort))
            return 2
        else

        let operationId = args.[0]
        match operations.TryFind(operationId) with
        | None ->
            eprintfn "Unknown operationId '%s'." operationId
            eprintfn "Known operations: %s" (String.concat ", " (operations.Keys |> Seq.sort))
            return 2
        | Some op ->

        let (paramValues, bodyOpt) = parseArgs (args.[1..])
        let secrets = loadSecrets ()

        let configuredBaseUrl = (topLevelSecret secrets "baseUrl") |> Option.defaultValue "https://petstore.example.com/v2"
        let baseUrl =
            match Environment.GetEnvironmentVariable("API2SKILL_BASE_URL") with
            | null -> configuredBaseUrl
            | v -> v
        if String.IsNullOrWhiteSpace(baseUrl) then
            eprintfn "No base URL configured. Set API2SKILL_BASE_URL or add \"baseUrl\" to secrets.json."
            return 2
        else

        let mutable path = op.PathTemplate
        let query = ResizeArray<string>()
        let headers = ResizeArray<string * string>()
        for p in op.Parameters do
            match paramValues.TryGetValue(p.Name) with
            | false, _ -> ()
            | true, value ->
                match p.Location with
                | "path" -> path <- path.Replace("{" + p.Name + "}", Uri.EscapeDataString(value))
                | "query" -> query.Add(sprintf "%s=%s" (Uri.EscapeDataString(p.Name)) (Uri.EscapeDataString(value)))
                | "header" -> headers.Add((p.Name, value))
                | _ -> ()

        use handler = new HttpClientHandler()
        let insecureDefault = "0"
        let insecure =
            match Environment.GetEnvironmentVariable("API2SKILL_INSECURE") with
            | null -> insecureDefault
            | v -> v
        if insecure = "1" then
            // Dev-only: accepts self-signed/invalid TLS certificates. Never enable in production.
            handler.ServerCertificateCustomValidationCallback <- HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
        use http = new HttpClient(handler)

        try
            let tokenCache = Dictionary<string, string>()
            if not (List.isEmpty op.AuthProfileNames) then
                let authConfig = loadAuthConfig ()
                let profilesEl =
                    match authConfig with
                    | Some cfg -> (match cfg.TryGetProperty("profiles") with | true, p -> Some p | false, _ -> None)
                    | None -> None
                for profileName in op.AuthProfileNames do
                    match findProfile profilesEl profileName with
                    | None -> raise (AuthResolutionException (sprintf "auth.json has no profile named '%s' (referenced by operation '%s')." profileName operationId))
                    | Some profile -> applyExplicitProfile profile secrets query headers
            else
                for schemeId in op.SecuritySchemeIds do
                    match schemes.TryFind(schemeId) with
                    | None -> ()
                    | Some scheme -> do! applyAuth http scheme secrets query headers tokenCache

            let url =
                baseUrl.TrimEnd('/') + path +
                (if query.Count > 0 then "?" + String.concat "&" query else "")

            let invalidHeaderName =
                headers |> Seq.tryPick (fun (n, v) -> if v.IndexOfAny([| '\r'; '\n' |]) >= 0 then Some n else None)
            if invalidHeaderName.IsSome then
                eprintfn "Invalid value for header '%s': control characters are not allowed." invalidHeaderName.Value
                return 2
            else

            use request = new HttpRequestMessage(HttpMethod(op.Method), url)
            for (name, value) in headers do
                request.Headers.TryAddWithoutValidation(name, value) |> ignore

            if op.HasBody then
                let bodyText = bodyOpt |> Option.defaultValue "{}"
                let resolvedBody = if bodyText.StartsWith('@') then IO.File.ReadAllText(bodyText.Substring(1)) else bodyText
                let contentType = op.BodyContentType |> Option.defaultValue "application/json"
                request.Content <- new StringContent(resolvedBody, Encoding.UTF8, contentType)

            let! response = http.SendAsync(request)
            let! responseText = response.Content.ReadAsStringAsync()
            printfn "%s" responseText
            if not response.IsSuccessStatusCode then
                eprintfn "HTTP %d %s" (int response.StatusCode) (string response.StatusCode)
                return 1
            else
                return 0
        with
        | AuthResolutionException msg ->
            eprintfn "%s" msg
            return 2
        | :? HttpRequestException as ex ->
            eprintfn "Network error calling %s: %s" baseUrl ex.Message
            return 3
    }

let exitCode = run fsi.CommandLineArgs.[1..] |> Async.AwaitTask |> Async.RunSynchronously
exit exitCode
