// Generated by api2skill — do not edit by hand; re-run the generator instead.
// Usage: dotnet run call.cs -- <operationId> [--<param> <value> ...] [--body <json|@file>]
using System.Net.Http;
using System.Net.Http.Headers;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;

return await Run(args);

static async Task<int> Run(string[] args)
{
    var operations = BuildOperations();
    var schemes = BuildSchemes();

    if (args.Length == 0 || args[0] is "-h" or "--help")
    {
        Console.Error.WriteLine("Usage: dotnet run call.cs -- <operationId> [--<param> <value> ...] [--body <json|@file>]");
        Console.Error.WriteLine("Known operations: " + string.Join(", ", operations.Keys.OrderBy(k => k, StringComparer.Ordinal)));
        return 2;
    }

    var operationId = args[0];
    if (!operations.TryGetValue(operationId, out var op))
    {
        Console.Error.WriteLine($"Unknown operationId '{operationId}'.");
        Console.Error.WriteLine("Known operations: " + string.Join(", ", operations.Keys.OrderBy(k => k, StringComparer.Ordinal)));
        return 2;
    }

    var (paramValues, body) = ParseArgs(args.Skip(1).ToArray());
    var secrets = LoadSecrets();

    var configuredBaseUrl = (secrets.HasValue && secrets.Value.TryGetProperty("baseUrl", out var baseUrlEl) ? baseUrlEl.GetString() : null) ?? "https://petstore.example.com/v2";
    var baseUrl = Environment.GetEnvironmentVariable("API2SKILL_BASE_URL") ?? configuredBaseUrl;
    if (string.IsNullOrWhiteSpace(baseUrl))
    {
        Console.Error.WriteLine("No base URL configured. Set API2SKILL_BASE_URL or add \"baseUrl\" to secrets.json.");
        return 2;
    }

    var path = op.PathTemplate;
    var query = new List<string>();
    var headers = new List<(string Name, string Value)>();
    foreach (var p in op.Parameters)
    {
        if (!paramValues.TryGetValue(p.Name, out var value)) continue;
        switch (p.Location)
        {
            case "path": path = path.Replace("{" + p.Name + "}", Uri.EscapeDataString(value)); break;
            case "query": query.Add($"{Uri.EscapeDataString(p.Name)}={Uri.EscapeDataString(value)}"); break;
            case "header": headers.Add((p.Name, value)); break;
        }
    }

    using var handler = new HttpClientHandler();
    var insecureDefault = "0";
    if ((Environment.GetEnvironmentVariable("API2SKILL_INSECURE") ?? insecureDefault) == "1")
    {
        // Dev-only: accepts self-signed/invalid TLS certificates. Never enable in production.
        handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
    }
    using var http = new HttpClient(handler);

    // Auth: resolved into `query`/`headers` BEFORE the URL is built, since apiKey
    // auth may live in the query string.
    var oauthTokenCache = new Dictionary<string, string>(StringComparer.Ordinal);
    try
    {
        foreach (var schemeId in op.SecuritySchemeIds)
        {
            if (!schemes.TryGetValue(schemeId, out var scheme))
            {
                continue;
            }
            await ApplyAuthAsync(http, scheme, secrets, query, headers, oauthTokenCache);
        }

        var url = baseUrl.TrimEnd('/') + path + (query.Count > 0 ? "?" + string.Join("&", query) : "");

        using var request = new HttpRequestMessage(new HttpMethod(op.Method), url);
        foreach (var (name, value) in headers)
        {
            if (value.AsSpan().IndexOfAny('\r', '\n') >= 0)
            {
                Console.Error.WriteLine($"Invalid value for header '{name}': control characters are not allowed.");
                return 2;
            }
            request.Headers.TryAddWithoutValidation(name, value);
        }

        if (op.HasBody)
        {
            var bodyText = body ?? "{}";
            if (bodyText.StartsWith('@'))
            {
                bodyText = File.ReadAllText(bodyText[1..]);
            }
            request.Content = new StringContent(bodyText, Encoding.UTF8, op.BodyContentType ?? "application/json");
        }

        using var response = await http.SendAsync(request);
        var responseText = await response.Content.ReadAsStringAsync();
        Console.WriteLine(responseText);
        if (!response.IsSuccessStatusCode)
        {
            Console.Error.WriteLine($"HTTP {(int)response.StatusCode} {response.StatusCode}");
            return 1;
        }
        return 0;
    }
    catch (HttpRequestException ex)
    {
        Console.Error.WriteLine($"Network error calling {baseUrl}: {ex.Message}");
        return 3;
    }
}

static JsonElement? LoadSecrets([CallerFilePath] string callerPath = "")
{
    var scriptDir = Path.GetDirectoryName(callerPath) ?? ".";
    var secretsPath = Path.Combine(scriptDir, "..", "secrets.json");
    if (!File.Exists(secretsPath))
    {
        return null;
    }
    try
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(secretsPath));
        return doc.RootElement.Clone();
    }
    catch (JsonException ex)
    {
        Console.Error.WriteLine($"warning: secrets.json is not valid JSON ({ex.Message}); proceeding as if no secrets were configured.");
        return null;
    }
}

static string? SecretValue(JsonElement? secrets, string schemeId, string key)
{
    if (secrets is not { } root) return null;
    if (!root.TryGetProperty(schemeId, out var entry)) return null;
    return entry.TryGetProperty(key, out var value) ? value.GetString() : null;
}

static async Task ApplyAuthAsync(HttpClient http, SchemeSpec scheme, JsonElement? secrets, List<string> query, List<(string Name, string Value)> headers, Dictionary<string, string> oauthTokenCache)
{
    switch (scheme.Kind)
    {
        case "apiKey":
        {
            var key = SecretValue(secrets, scheme.Id, "apiKey");
            if (key is null) { Console.Error.WriteLine($"warning: no apiKey configured for scheme '{scheme.Id}' in secrets.json — sending unauthenticated."); break; }
            if (scheme.ApiKeyLocation == "query") query.Add($"{Uri.EscapeDataString(scheme.ApiKeyName!)}={Uri.EscapeDataString(key)}");
            else headers.Add((scheme.ApiKeyName!, key));
            break;
        }
        case "bearer":
        {
            var token = SecretValue(secrets, scheme.Id, "bearerToken");
            if (token is null) { Console.Error.WriteLine($"warning: no bearerToken configured for scheme '{scheme.Id}' in secrets.json — sending unauthenticated."); break; }
            headers.Add(("Authorization", $"Bearer {token}"));
            break;
        }
        case "basic":
        {
            var user = SecretValue(secrets, scheme.Id, "username");
            var pass = SecretValue(secrets, scheme.Id, "password");
            if (user is null || pass is null) { Console.Error.WriteLine($"warning: no username/password configured for scheme '{scheme.Id}' in secrets.json — sending unauthenticated."); break; }
            var encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes($"{user}:{pass}"));
            headers.Add(("Authorization", $"Basic {encoded}"));
            break;
        }
        case "oauth2":
        {
            var clientId = SecretValue(secrets, scheme.Id, "clientId");
            var clientSecret = SecretValue(secrets, scheme.Id, "clientSecret");
            var tokenUrl = SecretValue(secrets, scheme.Id, "tokenUrl") ?? scheme.OAuthTokenUrl;
            if (clientId is null || clientSecret is null || tokenUrl is null) { Console.Error.WriteLine($"warning: no clientId/clientSecret/tokenUrl configured for scheme '{scheme.Id}' in secrets.json — sending unauthenticated."); break; }
            var token = await FetchOAuth2TokenAsync(http, tokenUrl, clientId, clientSecret, oauthTokenCache);
            if (token is null) { Console.Error.WriteLine($"warning: failed to obtain an OAuth2 token for scheme '{scheme.Id}' — sending unauthenticated."); break; }
            headers.Add(("Authorization", $"Bearer {token}"));
            break;
        }
        default:
            Console.Error.WriteLine($"warning: scheme '{scheme.Id}' ({scheme.Kind}) is not a supported auth kind — sending unauthenticated.");
            break;
    }
}

static async Task<string?> FetchOAuth2TokenAsync(HttpClient http, string tokenUrl, string clientId, string clientSecret, Dictionary<string, string> tokenCache)
{
    // Cached in memory for this process run only — never written to disk.
    var cacheKey = tokenUrl + "|" + clientId;
    if (tokenCache.TryGetValue(cacheKey, out var cached))
    {
        return cached;
    }
    var form = new FormUrlEncodedContent(new Dictionary<string, string>
    {
        ["grant_type"] = "client_credentials",
        ["client_id"] = clientId,
        ["client_secret"] = clientSecret,
    });
    using var response = await http.PostAsync(tokenUrl, form);
    if (!response.IsSuccessStatusCode)
    {
        return null;
    }
    try
    {
        using var doc = JsonDocument.Parse(await response.Content.ReadAsStringAsync());
        if (!doc.RootElement.TryGetProperty("access_token", out var tokenEl))
        {
            return null;
        }
        var token = tokenEl.GetString();
        if (token is not null)
        {
            tokenCache[cacheKey] = token;
        }
        return token;
    }
    catch (JsonException)
    {
        // The token endpoint returned a 2xx with a body that isn't valid JSON — treat
        // the same as a failed token fetch rather than crashing the whole dispatch.
        return null;
    }
}

static (Dictionary<string, string> Params, string? Body) ParseArgs(string[] rest)
{
    var values = new Dictionary<string, string>(StringComparer.Ordinal);
    string? body = null;
    for (var i = 0; i < rest.Length; i++)
    {
        if (!rest[i].StartsWith("--", StringComparison.Ordinal) || i + 1 >= rest.Length)
        {
            continue;
        }
        var key = rest[i][2..];
        var value = rest[++i];
        if (key == "body") { body = value; } else { values[key] = value; }
    }
    return (values, body);
}

static Dictionary<string, OperationSpec> BuildOperations() => new()
{
    ["getPetById"] = new("GET", "/pet/{petId}", [new("petId", "path")], false, null, ["api_key"]),
    ["addPet"] = new("POST", "/pet", [], true, "application/json", ["petstore_auth"]),
    ["get_store_inventory"] = new("GET", "/store/inventory", [], false, null, ["api_key"]),
    ["get_health"] = new("GET", "/health", [], false, null, []),
};

static Dictionary<string, SchemeSpec> BuildSchemes() => new()
{
    ["api_key"] = new("api_key", "apiKey", "api_key", "header", null),
    ["petstore_auth"] = new("petstore_auth", "oauth2", null, null, "https://petstore.example.com/oauth/token"),
};

sealed record ParamSpec(string Name, string Location);
sealed record OperationSpec(string Method, string PathTemplate, ParamSpec[] Parameters, bool HasBody, string? BodyContentType, string[] SecuritySchemeIds);
sealed record SchemeSpec(string Id, string Kind, string? ApiKeyName, string? ApiKeyLocation, string? OAuthTokenUrl);
