// Generated by api2skill — do not edit by hand; re-run the generator instead.
// Usage: dotnet run call.cs -- <operationId> [--<param> <value> ...] [--body <json|@file>]
using System.Net.Http;
using System.Text;
using System.Text.Json;

return await Run(args);

static async Task<int> Run(string[] args)
{
    var operations = BuildOperations();

    if (args.Length == 0 || args[0] is "-h" or "--help")
    {
        Console.Error.WriteLine("Usage: dotnet run call.cs -- <operationId> [--<param> <value> ...] [--body <json|@file>]");
        Console.Error.WriteLine("Known operations: " + string.Join(", ", operations.Keys.OrderBy(k => k, StringComparer.Ordinal)));
        return 2;
    }

    var operationId = args[0];
    if (!operations.TryGetValue(operationId, out var op))
    {
        Console.Error.WriteLine($"Unknown operationId '{operationId}'.");
        Console.Error.WriteLine("Known operations: " + string.Join(", ", operations.Keys.OrderBy(k => k, StringComparer.Ordinal)));
        return 2;
    }

    var (paramValues, body) = ParseArgs(args.Skip(1).ToArray());

    var baseUrl = Environment.GetEnvironmentVariable("API2SKILL_BASE_URL") ?? "https://petstore.example.com/v2";
    if (string.IsNullOrWhiteSpace(baseUrl))
    {
        Console.Error.WriteLine("No base URL configured. Set API2SKILL_BASE_URL or add \"baseUrl\" to secrets.json.");
        return 2;
    }

    var path = op.PathTemplate;
    var query = new List<string>();
    var headers = new List<(string Name, string Value)>();
    foreach (var p in op.Parameters)
    {
        if (!paramValues.TryGetValue(p.Name, out var value)) continue;
        switch (p.Location)
        {
            case "path": path = path.Replace("{" + p.Name + "}", Uri.EscapeDataString(value)); break;
            case "query": query.Add($"{Uri.EscapeDataString(p.Name)}={Uri.EscapeDataString(value)}"); break;
            case "header": headers.Add((p.Name, value)); break;
        }
    }

    var url = baseUrl.TrimEnd('/') + path + (query.Count > 0 ? "?" + string.Join("&", query) : "");

    using var handler = new HttpClientHandler();
    if (Environment.GetEnvironmentVariable("API2SKILL_INSECURE") == "1")
    {
        // Dev-only: accepts self-signed/invalid TLS certificates. Never enable in production.
        handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
    }
    using var http = new HttpClient(handler);

    using var request = new HttpRequestMessage(new HttpMethod(op.Method), url);
    foreach (var (name, value) in headers)
    {
        request.Headers.TryAddWithoutValidation(name, value);
    }

    if (op.HasBody)
    {
        var bodyText = body ?? "{}";
        if (bodyText.StartsWith('@'))
        {
            bodyText = File.ReadAllText(bodyText[1..]);
        }
        request.Content = new StringContent(bodyText, Encoding.UTF8, op.BodyContentType ?? "application/json");
    }

    if (op.SecuritySchemeIds.Length > 0)
    {
        // TODO (auth): header/token injection lands in a follow-up; op.SecuritySchemeIds
        // already names which scheme(s) are required, for when that's wired in.
        var schemes = string.Join(", ", op.SecuritySchemeIds);
        Console.Error.WriteLine($"warning: operation requires auth scheme(s) [{schemes}] — auth injection is not implemented yet; sending request without auth headers.");
    }

    using var response = await http.SendAsync(request);
    var responseText = await response.Content.ReadAsStringAsync();
    Console.WriteLine(responseText);
    if (!response.IsSuccessStatusCode)
    {
        Console.Error.WriteLine($"HTTP {(int)response.StatusCode} {response.StatusCode}");
        return 1;
    }
    return 0;
}

static (Dictionary<string, string> Params, string? Body) ParseArgs(string[] rest)
{
    var values = new Dictionary<string, string>(StringComparer.Ordinal);
    string? body = null;
    for (var i = 0; i < rest.Length; i++)
    {
        if (!rest[i].StartsWith("--", StringComparison.Ordinal) || i + 1 >= rest.Length)
        {
            continue;
        }
        var key = rest[i][2..];
        var value = rest[++i];
        if (key == "body") { body = value; } else { values[key] = value; }
    }
    return (values, body);
}

static Dictionary<string, OperationSpec> BuildOperations() => new()
{
    ["getPetById"] = new("GET", "/pet/{petId}", [new("petId", "path")], false, null, ["api_key"]),
    ["addPet"] = new("POST", "/pet", [], true, "application/json", ["petstore_auth"]),
    ["get_store_inventory"] = new("GET", "/store/inventory", [], false, null, ["api_key"]),
    ["get_health"] = new("GET", "/health", [], false, null, []),
};

sealed record ParamSpec(string Name, string Location);
sealed record OperationSpec(string Method, string PathTemplate, ParamSpec[] Parameters, bool HasBody, string? BodyContentType, string[] SecuritySchemeIds);
