using System.Text;
using Api2Skill.Model;

namespace Api2Skill.Emit;

/// <summary>
/// Default emitter (D3): a .NET 10 file-based single-file app (<c>dotnet run call.cs --</c>),
/// no separate build step, no NuGet dependency — plain <c>System.Net.Http.HttpClient</c> +
/// <c>System.Text.Json</c> only (Constitution II; ADR-0002 explains why not Refit).
///
/// Auth header/token injection is NOT wired yet — that lands in US2 (T024). Each generated
/// operation already carries its required security-scheme ids in the emitted
/// <c>OperationSpec</c> table, so that follow-up is a localized change to the generated
/// dispatch logic in <see cref="Generate"/>, not a redesign.
/// </summary>
public sealed class CsFileEmitter : IScriptEmitter
{
    public string Key => "cs";

    public string FileExtension => "cs";

    public string RunnerDescription => "dotnet run scripts/call.cs --";

    public void Emit(SkillModel model, DirectoryInfo skillDirectory)
    {
        var scriptsDirectory = Directory.CreateDirectory(Path.Combine(skillDirectory.FullName, "scripts"));
        var content = Generate(model);
        File.WriteAllText(Path.Combine(scriptsDirectory.FullName, "call.cs"), content);
    }

    private static string Generate(SkillModel model)
    {
        // .NET 10 file-based apps are top-level-statement programs: only ONE simple statement
        // is safe at the top level (`static readonly` fields aren't valid there — that was a
        // real bug caught by actually running the generated output). Everything else — the
        // operation table, arg parsing, the dispatch logic — lives in ordinary local functions
        // declared after that single statement, which top-level statements can forward-reference.
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by api2skill — do not edit by hand; re-run the generator instead.");
        sb.AppendLine("// Usage: dotnet run call.cs -- <operationId> [--<param> <value> ...] [--body <json|@file>]");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine();
        sb.AppendLine("return await Run(args);");
        sb.AppendLine();

        sb.AppendLine("static async Task<int> Run(string[] args)");
        sb.AppendLine("{");
        sb.AppendLine("    var operations = BuildOperations();");
        sb.AppendLine();
        sb.AppendLine("    if (args.Length == 0 || args[0] is \"-h\" or \"--help\")");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine(\"Usage: dotnet run call.cs -- <operationId> [--<param> <value> ...] [--body <json|@file>]\");");
        sb.AppendLine("        Console.Error.WriteLine(\"Known operations: \" + string.Join(\", \", operations.Keys.OrderBy(k => k, StringComparer.Ordinal)));");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    var operationId = args[0];");
        sb.AppendLine("    if (!operations.TryGetValue(operationId, out var op))");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine($\"Unknown operationId '{operationId}'.\");");
        sb.AppendLine("        Console.Error.WriteLine(\"Known operations: \" + string.Join(\", \", operations.Keys.OrderBy(k => k, StringComparer.Ordinal)));");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    var (paramValues, body) = ParseArgs(args.Skip(1).ToArray());");
        sb.AppendLine();
        sb.AppendLine($"    var baseUrl = Environment.GetEnvironmentVariable(\"API2SKILL_BASE_URL\") ?? {Literal(model.BaseUrl ?? string.Empty)};");
        sb.AppendLine("    if (string.IsNullOrWhiteSpace(baseUrl))");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine(\"No base URL configured. Set API2SKILL_BASE_URL or add \\\"baseUrl\\\" to secrets.json.\");");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    var path = op.PathTemplate;");
        sb.AppendLine("    var query = new List<string>();");
        sb.AppendLine("    var headers = new List<(string Name, string Value)>();");
        sb.AppendLine("    foreach (var p in op.Parameters)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!paramValues.TryGetValue(p.Name, out var value)) continue;");
        sb.AppendLine("        switch (p.Location)");
        sb.AppendLine("        {");
        sb.AppendLine("            case \"path\": path = path.Replace(\"{\" + p.Name + \"}\", Uri.EscapeDataString(value)); break;");
        sb.AppendLine("            case \"query\": query.Add($\"{Uri.EscapeDataString(p.Name)}={Uri.EscapeDataString(value)}\"); break;");
        sb.AppendLine("            case \"header\": headers.Add((p.Name, value)); break;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    var url = baseUrl.TrimEnd('/') + path + (query.Count > 0 ? \"?\" + string.Join(\"&\", query) : \"\");");
        sb.AppendLine();
        sb.AppendLine("    using var handler = new HttpClientHandler();");
        sb.AppendLine("    if (Environment.GetEnvironmentVariable(\"API2SKILL_INSECURE\") == \"1\")");
        sb.AppendLine("    {");
        sb.AppendLine("        // Dev-only: accepts self-signed/invalid TLS certificates. Never enable in production.");
        sb.AppendLine("        handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;");
        sb.AppendLine("    }");
        sb.AppendLine("    using var http = new HttpClient(handler);");
        sb.AppendLine();
        sb.AppendLine("    using var request = new HttpRequestMessage(new HttpMethod(op.Method), url);");
        sb.AppendLine("    foreach (var (name, value) in headers)");
        sb.AppendLine("    {");
        sb.AppendLine("        request.Headers.TryAddWithoutValidation(name, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    if (op.HasBody)");
        sb.AppendLine("    {");
        sb.AppendLine("        var bodyText = body ?? \"{}\";");
        sb.AppendLine("        if (bodyText.StartsWith('@'))");
        sb.AppendLine("        {");
        sb.AppendLine("            bodyText = File.ReadAllText(bodyText[1..]);");
        sb.AppendLine("        }");
        sb.AppendLine("        request.Content = new StringContent(bodyText, Encoding.UTF8, op.BodyContentType ?? \"application/json\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    if (op.SecuritySchemeIds.Length > 0)");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO (auth): header/token injection lands in a follow-up; op.SecuritySchemeIds");
        sb.AppendLine("        // already names which scheme(s) are required, for when that's wired in.");
        sb.AppendLine("        var schemes = string.Join(\", \", op.SecuritySchemeIds);");
        sb.AppendLine("        Console.Error.WriteLine($\"warning: operation requires auth scheme(s) [{schemes}] — auth injection is not implemented yet; sending request without auth headers.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    using var response = await http.SendAsync(request);");
        sb.AppendLine("    var responseText = await response.Content.ReadAsStringAsync();");
        sb.AppendLine("    Console.WriteLine(responseText);");
        sb.AppendLine("    if (!response.IsSuccessStatusCode)");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine($\"HTTP {(int)response.StatusCode} {response.StatusCode}\");");
        sb.AppendLine("        return 1;");
        sb.AppendLine("    }");
        sb.AppendLine("    return 0;");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static (Dictionary<string, string> Params, string? Body) ParseArgs(string[] rest)");
        sb.AppendLine("{");
        sb.AppendLine("    var values = new Dictionary<string, string>(StringComparer.Ordinal);");
        sb.AppendLine("    string? body = null;");
        sb.AppendLine("    for (var i = 0; i < rest.Length; i++)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!rest[i].StartsWith(\"--\", StringComparison.Ordinal) || i + 1 >= rest.Length)");
        sb.AppendLine("        {");
        sb.AppendLine("            continue;");
        sb.AppendLine("        }");
        sb.AppendLine("        var key = rest[i][2..];");
        sb.AppendLine("        var value = rest[++i];");
        sb.AppendLine("        if (key == \"body\") { body = value; } else { values[key] = value; }");
        sb.AppendLine("    }");
        sb.AppendLine("    return (values, body);");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static Dictionary<string, OperationSpec> BuildOperations() => new()");
        sb.AppendLine("{");
        foreach (var tag in model.Tags)
        {
            foreach (var op in tag.Operations)
            {
                sb.Append("    [").Append(Literal(op.OperationId)).Append("] = new(")
                  .Append(Literal(op.Method.Method)).Append(", ")
                  .Append(Literal(op.PathTemplate)).Append(", [")
                  .Append(string.Join(", ", op.Parameters.Select(p => $"new({Literal(p.Name)}, {Literal(LocationKey(p.In))})")))
                  .Append("], ")
                  .Append(op.RequestBody is not null ? "true" : "false").Append(", ")
                  .Append(op.RequestBody?.ContentType is { } ct ? Literal(ct) : "null").Append(", [")
                  .Append(string.Join(", ", op.SecuritySchemeIds.Select(Literal)))
                  .Append("]),")
                  .AppendLine();
            }
        }
        sb.AppendLine("};");
        sb.AppendLine();

        sb.AppendLine("sealed record ParamSpec(string Name, string Location);");
        sb.AppendLine("sealed record OperationSpec(string Method, string PathTemplate, ParamSpec[] Parameters, bool HasBody, string? BodyContentType, string[] SecuritySchemeIds);");

        return sb.ToString();
    }

    private static string LocationKey(ParameterLocation location) => location switch
    {
        ParameterLocation.Path => "path",
        ParameterLocation.Header => "header",
        _ => "query",
    };

    /// <summary>Renders a C# string literal, escaping backslashes/quotes/control characters.</summary>
    private static string Literal(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
