using System.Text;
using Api2Skill.Model;

namespace Api2Skill.Emit;

/// <summary>
/// Default emitter (D3): a .NET 10 file-based single-file app (<c>dotnet run call.cs --</c>),
/// no separate build step, no NuGet dependency — plain <c>System.Net.Http.HttpClient</c> +
/// <c>System.Text.Json</c> only (Constitution II; ADR-0002 explains why not Refit).
///
/// Applies auth for all four supported schemes (apiKey/bearer/basic/oauth2
/// client-credentials) by loading <c>secrets.json</c> from next to the script itself —
/// located via <c>[CallerFilePath]</c>, since <c>AppContext.BaseDirectory</c> resolves to a
/// throwaway build-cache directory for file-based apps, not the script's real location
/// (confirmed empirically, not documented).
/// </summary>
public sealed class CsFileEmitter : IScriptEmitter
{
    public string Key => "cs";

    public string FileExtension => "cs";

    public string RunnerDescription => "dotnet run scripts/call.cs --";

    public void Emit(SkillModel model, DirectoryInfo skillDirectory)
    {
        var scriptsDirectory = Directory.CreateDirectory(Path.Combine(skillDirectory.FullName, "scripts"));
        var content = Generate(model);
        File.WriteAllText(Path.Combine(scriptsDirectory.FullName, "call.cs"), content);
    }

    private static string Generate(SkillModel model)
    {
        // .NET 10 file-based apps are top-level-statement programs: only ONE simple statement
        // is safe at the top level (`static readonly` fields aren't valid there — that was a
        // real bug caught by actually running the generated output). Everything else — the
        // operation/scheme tables, arg parsing, auth, dispatch — lives in ordinary local
        // functions declared after that single statement, which can forward-reference them.
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by api2skill — do not edit by hand; re-run the generator instead.");
        sb.AppendLine("// Usage: dotnet run call.cs -- <operationId> [--<param> <value> ...] [--body <json|@file>]");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Net;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Headers;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Security.Cryptography;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Nodes;");
        sb.AppendLine();
        sb.AppendLine("return await Run(args);");
        sb.AppendLine();

        AppendRunFunction(sb, model);
        AppendAuthFunctions(sb);
        AppendParseArgsFunction(sb);
        AppendDataTables(sb, model);

        return sb.ToString();
    }

    private static void AppendRunFunction(StringBuilder sb, SkillModel model)
    {
        sb.AppendLine("static async Task<int> Run(string[] args)");
        sb.AppendLine("{");
        sb.AppendLine("    if (args.Length > 0 && args[0] == \"login\")");
        sb.AppendLine("    {");
        sb.AppendLine("        if (args.Length < 2)");
        sb.AppendLine("        {");
        sb.AppendLine("            Console.Error.WriteLine(\"Usage: dotnet run call.cs -- login <profile>\");");
        sb.AppendLine("            return 2;");
        sb.AppendLine("        }");
        sb.AppendLine("        return await LoginAsync(args[1]);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    var operations = BuildOperations();");
        sb.AppendLine("    var schemes = BuildSchemes();");
        sb.AppendLine();
        sb.AppendLine("    if (args.Length == 0 || args[0] is \"-h\" or \"--help\")");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine(\"Usage: dotnet run call.cs -- <operationId> [--<param> <value> ...] [--body <json|@file>]\");");
        sb.AppendLine("        Console.Error.WriteLine(\"Known operations: \" + string.Join(\", \", operations.Keys.OrderBy(k => k, StringComparer.Ordinal)));");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    var operationId = args[0];");
        sb.AppendLine("    if (!operations.TryGetValue(operationId, out var op))");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine($\"Unknown operationId '{operationId}'.\");");
        sb.AppendLine("        Console.Error.WriteLine(\"Known operations: \" + string.Join(\", \", operations.Keys.OrderBy(k => k, StringComparer.Ordinal)));");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    var (paramValues, body) = ParseArgs(args.Skip(1).ToArray());");
        sb.AppendLine("    var secrets = LoadSecrets();");
        sb.AppendLine();
        sb.AppendLine($"    var configuredBaseUrl = {SecretsLookup("baseUrl")} ?? {Literal(model.BaseUrl ?? string.Empty)};");
        sb.AppendLine("    var baseUrl = Environment.GetEnvironmentVariable(\"API2SKILL_BASE_URL\") ?? configuredBaseUrl;");
        sb.AppendLine("    if (string.IsNullOrWhiteSpace(baseUrl))");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine(\"No base URL configured. Set API2SKILL_BASE_URL or add \\\"baseUrl\\\" to secrets.json.\");");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    var path = op.PathTemplate;");
        sb.AppendLine("    var query = new List<string>();");
        sb.AppendLine("    var headers = new List<(string Name, string Value)>();");
        sb.AppendLine("    foreach (var p in op.Parameters)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!paramValues.TryGetValue(p.Name, out var value)) continue;");
        sb.AppendLine("        switch (p.Location)");
        sb.AppendLine("        {");
        sb.AppendLine("            case \"path\": path = path.Replace(\"{\" + p.Name + \"}\", Uri.EscapeDataString(value)); break;");
        sb.AppendLine("            case \"query\": query.Add($\"{Uri.EscapeDataString(p.Name)}={Uri.EscapeDataString(value)}\"); break;");
        sb.AppendLine("            case \"header\": headers.Add((p.Name, value)); break;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    using var handler = new HttpClientHandler();");
        sb.AppendLine($"    var insecureDefault = {Literal(model.InsecureDefault ? "1" : "0")};");
        sb.AppendLine("    if ((Environment.GetEnvironmentVariable(\"API2SKILL_INSECURE\") ?? insecureDefault) == \"1\")");
        sb.AppendLine("    {");
        sb.AppendLine("        // Dev-only: accepts self-signed/invalid TLS certificates. Never enable in production.");
        sb.AppendLine("        handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;");
        sb.AppendLine("    }");
        sb.AppendLine("    using var http = new HttpClient(handler);");
        sb.AppendLine();
        sb.AppendLine("    // Auth: resolved into `query`/`headers` BEFORE the URL is built, since apiKey");
        sb.AppendLine("    // auth may live in the query string. An operation covered by explicit auth.json");
        sb.AppendLine("    // profiles (AuthProfileNames non-empty) uses those, overriding spec-derived auth for");
        sb.AppendLine("    // this operation entirely (FR-006); otherwise spec-derived schemes apply as before.");
        sb.AppendLine("    var oauthTokenCache = new Dictionary<string, string>(StringComparer.Ordinal);");
        sb.AppendLine("    try");
        sb.AppendLine("    {");
        sb.AppendLine("        if (op.AuthProfileNames.Length > 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            var authConfig = LoadAuthConfig();");
        sb.AppendLine("            var profiles = authConfig is { } cfg && cfg.TryGetProperty(\"profiles\", out var profilesEl) ? profilesEl : (JsonElement?)null;");
        sb.AppendLine("            foreach (var profileName in op.AuthProfileNames)");
        sb.AppendLine("            {");
        sb.AppendLine("                var profile = FindProfile(profiles, profileName);");
        sb.AppendLine("                if (profile is null)");
        sb.AppendLine("                {");
        sb.AppendLine("                    throw new AuthResolutionException($\"auth.json has no profile named '{profileName}' (referenced by operation '{operationId}').\");");
        sb.AppendLine("                }");
        sb.AppendLine("                await ApplyExplicitProfileAsync(http, profile.Value, profileName, secrets, query, headers);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var schemeId in op.SecuritySchemeIds)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (!schemes.TryGetValue(schemeId, out var scheme))");
        sb.AppendLine("                {");
        sb.AppendLine("                    continue;");
        sb.AppendLine("                }");
        sb.AppendLine("                await ApplyAuthAsync(http, scheme, secrets, query, headers, oauthTokenCache);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var url = baseUrl.TrimEnd('/') + path + (query.Count > 0 ? \"?\" + string.Join(\"&\", query) : \"\");");
        sb.AppendLine();
        sb.AppendLine("        using var request = new HttpRequestMessage(new HttpMethod(op.Method), url);");
        sb.AppendLine("        foreach (var (name, value) in headers)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (value.AsSpan().IndexOfAny('\\r', '\\n') >= 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                Console.Error.WriteLine($\"Invalid value for header '{name}': control characters are not allowed.\");");
        sb.AppendLine("                return 2;");
        sb.AppendLine("            }");
        sb.AppendLine("            request.Headers.TryAddWithoutValidation(name, value);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (op.HasBody)");
        sb.AppendLine("        {");
        sb.AppendLine("            var bodyText = body ?? \"{}\";");
        sb.AppendLine("            if (bodyText.StartsWith('@'))");
        sb.AppendLine("            {");
        sb.AppendLine("                bodyText = File.ReadAllText(bodyText[1..]);");
        sb.AppendLine("            }");
        sb.AppendLine("            request.Content = new StringContent(bodyText, Encoding.UTF8, op.BodyContentType ?? \"application/json\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        using var response = await http.SendAsync(request);");
        sb.AppendLine("        var responseText = await response.Content.ReadAsStringAsync();");
        sb.AppendLine("        Console.WriteLine(responseText);");
        sb.AppendLine("        if (!response.IsSuccessStatusCode)");
        sb.AppendLine("        {");
        sb.AppendLine("            Console.Error.WriteLine($\"HTTP {(int)response.StatusCode} {response.StatusCode}\");");
        sb.AppendLine("            return 1;");
        sb.AppendLine("        }");
        sb.AppendLine("        return 0;");
        sb.AppendLine("    }");
        sb.AppendLine("    catch (AuthResolutionException ex)");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine(ex.Message);");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine("    catch (HttpRequestException ex)");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine($\"Network error calling {baseUrl}: {ex.Message}\");");
        sb.AppendLine("        return 3;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string SecretsLookup(string key) =>
        $"(secrets.HasValue && secrets.Value.TryGetProperty({Literal(key)}, out var {key}El) ? {key}El.GetString() : null)";

    private static void AppendAuthFunctions(StringBuilder sb)
    {
        sb.AppendLine("static JsonElement? LoadSecrets([CallerFilePath] string callerPath = \"\")");
        sb.AppendLine("{");
        sb.AppendLine("    var scriptDir = Path.GetDirectoryName(callerPath) ?? \".\";");
        sb.AppendLine("    var secretsPath = Path.Combine(scriptDir, \"..\", \"secrets.json\");");
        sb.AppendLine("    if (!File.Exists(secretsPath))");
        sb.AppendLine("    {");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("    try");
        sb.AppendLine("    {");
        sb.AppendLine("        using var doc = JsonDocument.Parse(File.ReadAllText(secretsPath));");
        sb.AppendLine("        return doc.RootElement.Clone();");
        sb.AppendLine("    }");
        sb.AppendLine("    catch (JsonException ex)");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine($\"warning: secrets.json is not valid JSON ({ex.Message}); proceeding as if no secrets were configured.\");");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Explicit auth.json profiles (FR-006..FR-021a): a distinct code path from the
        // spec-derived schemes above. Raised as a typed exception (caught in Run) rather than a
        // printed warning, since an unresolved secret or unknown profile/type must FAIL the
        // call, never send a partial/unauthenticated request silently (contracts/dispatcher-auth.md).
        // NOTE: the AuthResolutionException *type declaration* itself is emitted at the very end
        // of the file (AppendDataTables), not here — in a file-based app's top-level-statement
        // region, once ANY type declaration appears, every local function after it becomes
        // illegal (CS8803: top-level statements must precede type declarations). All local
        // functions using it below only *reference* the type; that's fine anywhere.
        sb.AppendLine("static JsonElement? LoadAuthConfig([CallerFilePath] string callerPath = \"\")");
        sb.AppendLine("{");
        sb.AppendLine("    var scriptDir = Path.GetDirectoryName(callerPath) ?? \".\";");
        sb.AppendLine("    var authConfigPath = Path.Combine(scriptDir, \"..\", \"auth.json\");");
        sb.AppendLine("    if (!File.Exists(authConfigPath))");
        sb.AppendLine("    {");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("    try");
        sb.AppendLine("    {");
        sb.AppendLine("        using var doc = JsonDocument.Parse(File.ReadAllText(authConfigPath));");
        sb.AppendLine("        return doc.RootElement.Clone();");
        sb.AppendLine("    }");
        sb.AppendLine("    catch (JsonException ex)");
        sb.AppendLine("    {");
        sb.AppendLine("        throw new AuthResolutionException($\"auth.json is not valid JSON ({ex.Message}).\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static JsonElement? FindProfile(JsonElement? profiles, string name)");
        sb.AppendLine("{");
        sb.AppendLine("    if (profiles is not { } arr || arr.ValueKind != JsonValueKind.Array)");
        sb.AppendLine("    {");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("    foreach (var p in arr.EnumerateArray())");
        sb.AppendLine("    {");
        sb.AppendLine("        if (p.TryGetProperty(\"name\", out var n) && n.GetString() == name)");
        sb.AppendLine("        {");
        sb.AppendLine("            return p;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("    return null;");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static string ResolveSecretOrLiteral(string raw, JsonElement? secrets)");
        sb.AppendLine("{");
        sb.AppendLine("    if (raw.StartsWith(\"{secret:\", StringComparison.Ordinal) && raw.EndsWith('}'))");
        sb.AppendLine("    {");
        sb.AppendLine("        var key = raw[8..^1];");
        sb.AppendLine("        if (secrets is { } root && root.TryGetProperty(key, out var value) && value.GetString() is { } s)");
        sb.AppendLine("        {");
        sb.AppendLine("            return s;");
        sb.AppendLine("        }");
        sb.AppendLine("        throw new AuthResolutionException($\"secrets.json has no value for \\\"{key}\\\" (referenced by auth.json).\");");
        sb.AppendLine("    }");
        sb.AppendLine("    return raw;");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static string GetProp(JsonElement el, string name) => el.TryGetProperty(name, out var v) ? v.GetString() ?? \"\" : \"\";");
        sb.AppendLine();

        sb.AppendLine("static async Task<(int ExitCode, string Stdout, string Stderr)> RunScriptCommandAsync(string command, string skillRoot)");
        sb.AppendLine("{");
        sb.AppendLine("    var psi = new ProcessStartInfo");
        sb.AppendLine("    {");
        sb.AppendLine("        RedirectStandardOutput = true,");
        sb.AppendLine("        RedirectStandardError = true,");
        sb.AppendLine("        UseShellExecute = false,");
        sb.AppendLine("        WorkingDirectory = skillRoot,");
        sb.AppendLine("    };");
        sb.AppendLine("    if (OperatingSystem.IsWindows())");
        sb.AppendLine("    {");
        sb.AppendLine("        psi.FileName = \"cmd.exe\";");
        sb.AppendLine("        psi.ArgumentList.Add(\"/c\");");
        sb.AppendLine("        psi.ArgumentList.Add(command);");
        sb.AppendLine("    }");
        sb.AppendLine("    else");
        sb.AppendLine("    {");
        sb.AppendLine("        psi.FileName = \"/bin/sh\";");
        sb.AppendLine("        psi.ArgumentList.Add(\"-c\");");
        sb.AppendLine("        psi.ArgumentList.Add(command);");
        sb.AppendLine("    }");
        sb.AppendLine("    using var process = Process.Start(psi)!;");
        sb.AppendLine("    var stdoutTask = process.StandardOutput.ReadToEndAsync();");
        sb.AppendLine("    var stderrTask = process.StandardError.ReadToEndAsync();");
        sb.AppendLine("    await process.WaitForExitAsync();");
        sb.AppendLine("    return (process.ExitCode, await stdoutTask, await stderrTask);");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static async Task ApplyExplicitProfileAsync(HttpClient http, JsonElement profile, string profileName, JsonElement? secrets, List<string> query, List<(string Name, string Value)> headers, [CallerFilePath] string callerPath = \"\")");
        sb.AppendLine("{");
        sb.AppendLine("    var type = GetProp(profile, \"type\");");
        sb.AppendLine("    switch (type)");
        sb.AppendLine("    {");
        sb.AppendLine("        case \"bearer\":");
        sb.AppendLine("        {");
        sb.AppendLine("            var token = ResolveSecretOrLiteral(GetProp(profile, \"token\"), secrets);");
        sb.AppendLine("            var value = token.StartsWith(\"Bearer \", StringComparison.OrdinalIgnoreCase) ? token : $\"Bearer {token}\";");
        sb.AppendLine("            headers.Add((\"Authorization\", value));");
        sb.AppendLine("            break;");
        sb.AppendLine("        }");
        sb.AppendLine("        case \"basic\":");
        sb.AppendLine("        {");
        sb.AppendLine("            var user = ResolveSecretOrLiteral(GetProp(profile, \"username\"), secrets);");
        sb.AppendLine("            var pass = ResolveSecretOrLiteral(GetProp(profile, \"password\"), secrets);");
        sb.AppendLine("            var encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes($\"{user}:{pass}\"));");
        sb.AppendLine("            headers.Add((\"Authorization\", $\"Basic {encoded}\"));");
        sb.AppendLine("            break;");
        sb.AppendLine("        }");
        sb.AppendLine("        case \"custom\":");
        sb.AppendLine("        {");
        sb.AppendLine("            if (profile.TryGetProperty(\"headers\", out var headersEl) && headersEl.ValueKind == JsonValueKind.Array)");
        sb.AppendLine("            {");
        sb.AppendLine("                foreach (var h in headersEl.EnumerateArray())");
        sb.AppendLine("                {");
        sb.AppendLine("                    var name = GetProp(h, \"name\");");
        sb.AppendLine("                    var value = ResolveSecretOrLiteral(GetProp(h, \"value\"), secrets);");
        sb.AppendLine("                    headers.Add((name, value));");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            break;");
        sb.AppendLine("        }");
        sb.AppendLine("        case \"oauth2\":");
        sb.AppendLine("        {");
        sb.AppendLine("            var accessToken = await ResolveOAuthAccessTokenAsync(http, profile, profileName, secrets);");
        sb.AppendLine("            headers.Add((\"Authorization\", $\"Bearer {accessToken}\"));");
        sb.AppendLine("            break;");
        sb.AppendLine("        }");
        sb.AppendLine("        case \"script\":");
        sb.AppendLine("        {");
        sb.AppendLine("            var command = GetProp(profile, \"command\");");
        sb.AppendLine("            var headerName = GetProp(profile, \"header\");");
        sb.AppendLine("            if (string.IsNullOrEmpty(headerName)) headerName = \"Authorization\";");
        sb.AppendLine("            var bearerPrefix = profile.TryGetProperty(\"bearerPrefix\", out var bpEl) && bpEl.ValueKind == JsonValueKind.True;");
        sb.AppendLine("            var scriptDir = Path.GetDirectoryName(callerPath) ?? \".\";");
        sb.AppendLine("            var skillRoot = Path.GetFullPath(Path.Combine(scriptDir, \"..\"));");
        sb.AppendLine("            var (exitCode, stdout, stderr) = await RunScriptCommandAsync(command, skillRoot);");
        sb.AppendLine("            if (exitCode != 0)");
        sb.AppendLine("                throw new AuthResolutionException($\"Script command for auth profile '{profileName}' exited with code {exitCode}: {stderr.Trim()}\");");
        sb.AppendLine("            var token = stdout.Trim();");
        sb.AppendLine("            if (bearerPrefix && !token.StartsWith(\"Bearer \", StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("                token = $\"Bearer {token}\";");
        sb.AppendLine("            headers.Add((headerName, token));");
        sb.AppendLine("            break;");
        sb.AppendLine("        }");
        sb.AppendLine("        default:");
        sb.AppendLine("            throw new AuthResolutionException($\"Auth profile type '{type}' is not supported by this generated dispatcher yet.\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // OAuth2 (US3): PKCE + state generation, entra-preset endpoint resolution (duplicated
        // here from the generator's EntraPreset.cs — the dispatcher is a standalone script with
        // no reference to the generator's assembly), the interactive `login` flow (loopback
        // HttpListener callback + browser launch, headless URL-print fallback), token exchange/
        // refresh/client_credentials requests (Postman-parity custom headers/body), and a
        // file-locked on-disk token cache (contracts/dispatcher-auth.md).
        sb.AppendLine("static (string Verifier, string Challenge) GeneratePkce()");
        sb.AppendLine("{");
        sb.AppendLine("    var bytes = new byte[32];");
        sb.AppendLine("    RandomNumberGenerator.Fill(bytes);");
        sb.AppendLine("    var verifier = Convert.ToBase64String(bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_');");
        sb.AppendLine("    var challengeBytes = SHA256.HashData(Encoding.ASCII.GetBytes(verifier));");
        sb.AppendLine("    var challenge = Convert.ToBase64String(challengeBytes).TrimEnd('=').Replace('+', '-').Replace('/', '_');");
        sb.AppendLine("    return (verifier, challenge);");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static string GenerateState()");
        sb.AppendLine("{");
        sb.AppendLine("    var bytes = new byte[16];");
        sb.AppendLine("    RandomNumberGenerator.Fill(bytes);");
        sb.AppendLine("    return Convert.ToBase64String(bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_');");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static Dictionary<string, string> ParseQuery(string query)");
        sb.AppendLine("{");
        sb.AppendLine("    var result = new Dictionary<string, string>(StringComparer.Ordinal);");
        sb.AppendLine("    var q = query.TrimStart('?');");
        sb.AppendLine("    if (q.Length == 0) return result;");
        sb.AppendLine("    foreach (var pair in q.Split('&'))");
        sb.AppendLine("    {");
        sb.AppendLine("        var idx = pair.IndexOf('=');");
        sb.AppendLine("        if (idx < 0) { result[Uri.UnescapeDataString(pair)] = \"\"; continue; }");
        sb.AppendLine("        result[Uri.UnescapeDataString(pair[..idx])] = Uri.UnescapeDataString(pair[(idx + 1)..]);");
        sb.AppendLine("    }");
        sb.AppendLine("    return result;");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static bool TryLaunchBrowser(string url)");
        sb.AppendLine("{");
        sb.AppendLine("    try { Process.Start(new ProcessStartInfo(url) { UseShellExecute = true }); return true; }");
        sb.AppendLine("    catch");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            if (OperatingSystem.IsMacOS()) { Process.Start(\"open\", url); return true; }");
        sb.AppendLine("            if (OperatingSystem.IsLinux()) { Process.Start(\"xdg-open\", url); return true; }");
        sb.AppendLine("            if (OperatingSystem.IsWindows()) { Process.Start(new ProcessStartInfo(\"cmd\", $\"/c start {url}\") { CreateNoWindow = true }); return true; }");
        sb.AppendLine("        }");
        sb.AppendLine("        catch { }");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        AppendClipboardFunctions(sb);

        sb.AppendLine("static void AddCallbackPrefixes(HttpListener listener, Uri uri)");
        sb.AppendLine("{");
        sb.AppendLine("    var scheme = uri.Scheme;");
        sb.AppendLine("    var port = uri.Port;");
        sb.AppendLine("    var host = uri.Host;");
        sb.AppendLine("    listener.Prefixes.Add($\"{scheme}://{host}:{port}/\");");
        sb.AppendLine("    if (host.Equals(\"localhost\", StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("        listener.Prefixes.Add($\"{scheme}://127.0.0.1:{port}/\");");
        sb.AppendLine("    else if (host is \"127.0.0.1\" or \"::1\")");
        sb.AppendLine("        listener.Prefixes.Add($\"{scheme}://localhost:{port}/\");");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static HttpListener BeginCallbackListener(string callbackUrl)");
        sb.AppendLine("{");
        sb.AppendLine("    var uri = new Uri(callbackUrl);");
        sb.AppendLine("    var listener = new HttpListener();");
        sb.AppendLine("    AddCallbackPrefixes(listener, uri);");
        sb.AppendLine("    try");
        sb.AppendLine("    {");
        sb.AppendLine("        listener.Start();");
        sb.AppendLine("    }");
        sb.AppendLine("    catch (HttpListenerException ex)");
        sb.AppendLine("    {");
        sb.AppendLine("        throw new AuthResolutionException($\"Could not start the local OAuth callback listener on {uri.Host}:{uri.Port} ({ex.Message}). Another process may be using this port \\u2014 try a different callbackUrl in auth.json.\");");
        sb.AppendLine("    }");
        sb.AppendLine("    return listener;");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static async Task<Dictionary<string, string>> AwaitOAuthCallbackAsync(HttpListener listener)");
        sb.AppendLine("{");
        sb.AppendLine("  try");
        sb.AppendLine("  {");
        sb.AppendLine("    while (true)");
        sb.AppendLine("    {");
        sb.AppendLine("        var context = await listener.GetContextAsync();");
        sb.AppendLine("        var result = ParseQuery(context.Request.Url?.Query ?? \"\");");
        sb.AppendLine("        if (result.ContainsKey(\"code\") || result.ContainsKey(\"error\"))");
        sb.AppendLine("        {");
        sb.AppendLine("            var page = Encoding.UTF8.GetBytes(\"<html><body>Login complete \\u2014 you can close this window and return to the terminal.</body></html>\");");
        sb.AppendLine("            context.Response.StatusCode = 200;");
        sb.AppendLine("            context.Response.ContentType = \"text/html; charset=utf-8\";");
        sb.AppendLine("            context.Response.ContentLength64 = page.Length;");
        sb.AppendLine("            context.Response.OutputStream.Write(page, 0, page.Length);");
        sb.AppendLine("            context.Response.Close();");
        sb.AppendLine("            return result;");
        sb.AppendLine("        }");
        sb.AppendLine("        context.Response.StatusCode = 404;");
        sb.AppendLine("        context.Response.Close();");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("  finally");
        sb.AppendLine("  {");
        sb.AppendLine("      listener.Stop();");
        sb.AppendLine("      listener.Close();");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static (string? AuthUrl, string? TokenUrl, List<string> Scopes) ResolveOAuthEndpoints(JsonElement profile)");
        sb.AppendLine("{");
        sb.AppendLine("    var preset = GetProp(profile, \"preset\");");
        sb.AppendLine("    var tenant = GetProp(profile, \"tenant\");");
        sb.AppendLine("    string? authUrl = profile.TryGetProperty(\"authUrl\", out var a) ? a.GetString() : null;");
        sb.AppendLine("    string? tokenUrl = profile.TryGetProperty(\"tokenUrl\", out var t) ? t.GetString() : null;");
        sb.AppendLine("    var scopes = new List<string>();");
        sb.AppendLine("    if (profile.TryGetProperty(\"scopes\", out var scopesEl) && scopesEl.ValueKind == JsonValueKind.Array)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var s in scopesEl.EnumerateArray()) { if (s.GetString() is { } sv) scopes.Add(sv); }");
        sb.AppendLine("    }");
        sb.AppendLine("    if (string.Equals(preset, \"entra\", StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("    {");
        sb.AppendLine("        authUrl ??= tenant.Length > 0 ? $\"https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize\" : null;");
        sb.AppendLine("        tokenUrl ??= tenant.Length > 0 ? $\"https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token\" : null;");
        sb.AppendLine("        if (!scopes.Contains(\"offline_access\", StringComparer.Ordinal)) scopes.Add(\"offline_access\");");
        sb.AppendLine("    }");
        sb.AppendLine("    return (authUrl, tokenUrl, scopes);");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static string BuildAuthorizeUrl(string authUrl, string clientId, string callbackUrl, List<string> scopes, string challenge, string state, JsonElement profile)");
        sb.AppendLine("{");
        sb.AppendLine("    var qs = new List<string>");
        sb.AppendLine("    {");
        sb.AppendLine("        \"response_type=code\",");
        sb.AppendLine("        $\"client_id={Uri.EscapeDataString(clientId)}\",");
        sb.AppendLine("        $\"redirect_uri={Uri.EscapeDataString(callbackUrl)}\",");
        sb.AppendLine("        $\"code_challenge={Uri.EscapeDataString(challenge)}\",");
        sb.AppendLine("        \"code_challenge_method=S256\",");
        sb.AppendLine("        $\"state={Uri.EscapeDataString(state)}\",");
        sb.AppendLine("    };");
        sb.AppendLine("    if (scopes.Count > 0) qs.Add($\"scope={Uri.EscapeDataString(string.Join(' ', scopes))}\");");
        sb.AppendLine("    if (profile.TryGetProperty(\"authorizeRequest\", out var arEl) && arEl.TryGetProperty(\"body\", out var bodyEl) && bodyEl.ValueKind == JsonValueKind.Object)");
        sb.AppendLine("    {");
        sb.AppendLine("        // authorizeRequest.headers has no effect here: there is no way to attach custom HTTP");
        sb.AppendLine("        // headers to a browser navigation, only extra parameters on the URL itself.");
        sb.AppendLine("        foreach (var prop in bodyEl.EnumerateObject())");
        sb.AppendLine("        {");
        sb.AppendLine("            qs.Add($\"{Uri.EscapeDataString(prop.Name)}={Uri.EscapeDataString(prop.Value.GetString() ?? \"\")}\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("    var sep = authUrl.Contains('?') ? \"&\" : \"?\";");
        sb.AppendLine("    return authUrl + sep + string.Join(\"&\", qs);");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static string? SecretValue(JsonElement? secrets, string schemeId, string key)");
        sb.AppendLine("{");
        sb.AppendLine("    if (secrets is not { } root) return null;");
        sb.AppendLine("    if (!root.TryGetProperty(schemeId, out var entry)) return null;");
        sb.AppendLine("    return entry.TryGetProperty(key, out var value) ? value.GetString() : null;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Per-scheme application: mutates `query`/`headers` (auth resolved before the URL is
        // built, since apiKey auth may add a query parameter).
        sb.AppendLine("static async Task ApplyAuthAsync(HttpClient http, SchemeSpec scheme, JsonElement? secrets, List<string> query, List<(string Name, string Value)> headers, Dictionary<string, string> oauthTokenCache)");
        sb.AppendLine("{");
        sb.AppendLine("    switch (scheme.Kind)");
        sb.AppendLine("    {");
        sb.AppendLine("        case \"apiKey\":");
        sb.AppendLine("        {");
        sb.AppendLine("            var key = SecretValue(secrets, scheme.Id, \"apiKey\");");
        sb.AppendLine("            if (key is null) { Console.Error.WriteLine($\"warning: no apiKey configured for scheme '{scheme.Id}' in secrets.json — sending unauthenticated.\"); break; }");
        sb.AppendLine("            if (scheme.ApiKeyLocation == \"query\") query.Add($\"{Uri.EscapeDataString(scheme.ApiKeyName!)}={Uri.EscapeDataString(key)}\");");
        sb.AppendLine("            else headers.Add((scheme.ApiKeyName!, key));");
        sb.AppendLine("            break;");
        sb.AppendLine("        }");
        sb.AppendLine("        case \"bearer\":");
        sb.AppendLine("        {");
        sb.AppendLine("            var token = SecretValue(secrets, scheme.Id, \"bearerToken\");");
        sb.AppendLine("            if (token is null) { Console.Error.WriteLine($\"warning: no bearerToken configured for scheme '{scheme.Id}' in secrets.json — sending unauthenticated.\"); break; }");
        sb.AppendLine("            headers.Add((\"Authorization\", $\"Bearer {token}\"));");
        sb.AppendLine("            break;");
        sb.AppendLine("        }");
        sb.AppendLine("        case \"basic\":");
        sb.AppendLine("        {");
        sb.AppendLine("            var user = SecretValue(secrets, scheme.Id, \"username\");");
        sb.AppendLine("            var pass = SecretValue(secrets, scheme.Id, \"password\");");
        sb.AppendLine("            if (user is null || pass is null) { Console.Error.WriteLine($\"warning: no username/password configured for scheme '{scheme.Id}' in secrets.json — sending unauthenticated.\"); break; }");
        sb.AppendLine("            var encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes($\"{user}:{pass}\"));");
        sb.AppendLine("            headers.Add((\"Authorization\", $\"Basic {encoded}\"));");
        sb.AppendLine("            break;");
        sb.AppendLine("        }");
        sb.AppendLine("        case \"oauth2\":");
        sb.AppendLine("        {");
        sb.AppendLine("            var clientId = SecretValue(secrets, scheme.Id, \"clientId\");");
        sb.AppendLine("            var clientSecret = SecretValue(secrets, scheme.Id, \"clientSecret\");");
        sb.AppendLine("            var tokenUrl = SecretValue(secrets, scheme.Id, \"tokenUrl\") ?? scheme.OAuthTokenUrl;");
        sb.AppendLine("            if (clientId is null || clientSecret is null || tokenUrl is null) { Console.Error.WriteLine($\"warning: no clientId/clientSecret/tokenUrl configured for scheme '{scheme.Id}' in secrets.json — sending unauthenticated.\"); break; }");
        sb.AppendLine("            var token = await FetchOAuth2TokenAsync(http, tokenUrl, clientId, clientSecret, oauthTokenCache);");
        sb.AppendLine("            if (token is null) { Console.Error.WriteLine($\"warning: failed to obtain an OAuth2 token for scheme '{scheme.Id}' — sending unauthenticated.\"); break; }");
        sb.AppendLine("            headers.Add((\"Authorization\", $\"Bearer {token}\"));");
        sb.AppendLine("            break;");
        sb.AppendLine("        }");
        sb.AppendLine("        default:");
        sb.AppendLine("            Console.Error.WriteLine($\"warning: scheme '{scheme.Id}' ({scheme.Kind}) is not a supported auth kind — sending unauthenticated.\");");
        sb.AppendLine("            break;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static async Task<string?> FetchOAuth2TokenAsync(HttpClient http, string tokenUrl, string clientId, string clientSecret, Dictionary<string, string> tokenCache)");
        sb.AppendLine("{");
        sb.AppendLine("    // Cached in memory for this process run only — never written to disk.");
        sb.AppendLine("    var cacheKey = tokenUrl + \"|\" + clientId;");
        sb.AppendLine("    if (tokenCache.TryGetValue(cacheKey, out var cached))");
        sb.AppendLine("    {");
        sb.AppendLine("        return cached;");
        sb.AppendLine("    }");
        sb.AppendLine("    var form = new FormUrlEncodedContent(new Dictionary<string, string>");
        sb.AppendLine("    {");
        sb.AppendLine("        [\"grant_type\"] = \"client_credentials\",");
        sb.AppendLine("        [\"client_id\"] = clientId,");
        sb.AppendLine("        [\"client_secret\"] = clientSecret,");
        sb.AppendLine("    });");
        sb.AppendLine("    using var response = await http.PostAsync(tokenUrl, form);");
        sb.AppendLine("    if (!response.IsSuccessStatusCode)");
        sb.AppendLine("    {");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("    try");
        sb.AppendLine("    {");
        sb.AppendLine("        using var doc = JsonDocument.Parse(await response.Content.ReadAsStringAsync());");
        sb.AppendLine("        if (!doc.RootElement.TryGetProperty(\"access_token\", out var tokenEl))");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine("        var token = tokenEl.GetString();");
        sb.AppendLine("        if (token is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            tokenCache[cacheKey] = token;");
        sb.AppendLine("        }");
        sb.AppendLine("        return token;");
        sb.AppendLine("    }");
        sb.AppendLine("    catch (JsonException)");
        sb.AppendLine("    {");
        sb.AppendLine("        // The token endpoint returned a 2xx with a body that isn't valid JSON — treat");
        sb.AppendLine("        // the same as a failed token fetch rather than crashing the whole dispatch.");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        AppendOAuthTokenRequestFunctions(sb);
        AppendOAuthTokenCacheFunctions(sb);
        AppendOAuthLoginFunction(sb);
    }

    private static void AppendOAuthTokenRequestFunctions(StringBuilder sb)
    {
        sb.AppendLine("static async Task<(string AccessToken, string? RefreshToken, int ExpiresIn)?> PostTokenRequestAsync(HttpClient http, JsonElement profile, string tokenUrl, string clientId, Dictionary<string, string> form, JsonElement? secrets)");
        sb.AppendLine("{");
        sb.AppendLine("    var clientAuth = GetProp(profile, \"clientAuth\");");
        sb.AppendLine("    var clientSecretRaw = profile.TryGetProperty(\"clientSecret\", out var csEl) ? csEl.GetString() : null;");
        sb.AppendLine("    var clientSecret = clientSecretRaw is { Length: > 0 } ? ResolveSecretOrLiteral(clientSecretRaw, secrets) : null;");
        sb.AppendLine();
        sb.AppendLine("    using var request = new HttpRequestMessage(HttpMethod.Post, tokenUrl);");
        sb.AppendLine("    if (clientAuth == \"basic\" && clientSecret is not null)");
        sb.AppendLine("    {");
        sb.AppendLine("        form.Remove(\"client_id\");");
        sb.AppendLine("        var basic = Convert.ToBase64String(Encoding.UTF8.GetBytes($\"{clientId}:{clientSecret}\"));");
        sb.AppendLine("        request.Headers.TryAddWithoutValidation(\"Authorization\", $\"Basic {basic}\");");
        sb.AppendLine("    }");
        sb.AppendLine("    else if (clientSecret is not null)");
        sb.AppendLine("    {");
        sb.AppendLine("        form[\"client_secret\"] = clientSecret;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    if (profile.TryGetProperty(\"tokenRequest\", out var trEl))");
        sb.AppendLine("    {");
        sb.AppendLine("        if (trEl.TryGetProperty(\"headers\", out var hEl) && hEl.ValueKind == JsonValueKind.Object)");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var prop in hEl.EnumerateObject()) request.Headers.TryAddWithoutValidation(prop.Name, prop.Value.GetString() ?? \"\");");
        sb.AppendLine("        }");
        sb.AppendLine("        if (trEl.TryGetProperty(\"body\", out var bEl) && bEl.ValueKind == JsonValueKind.Object)");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var prop in bEl.EnumerateObject()) form[prop.Name] = prop.Value.GetString() ?? \"\";");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    request.Content = new FormUrlEncodedContent(form);");
        sb.AppendLine("    using var response = await http.SendAsync(request);");
        sb.AppendLine("    var text = await response.Content.ReadAsStringAsync();");
        sb.AppendLine("    if (!response.IsSuccessStatusCode) return null;");
        sb.AppendLine("    try");
        sb.AppendLine("    {");
        sb.AppendLine("        using var doc = JsonDocument.Parse(text);");
        sb.AppendLine("        var root = doc.RootElement;");
        sb.AppendLine("        if (!root.TryGetProperty(\"access_token\", out var atEl) || atEl.GetString() is not { } accessToken) return null;");
        sb.AppendLine("        var refreshToken = root.TryGetProperty(\"refresh_token\", out var rtEl) ? rtEl.GetString() : null;");
        sb.AppendLine("        var expiresIn = root.TryGetProperty(\"expires_in\", out var eiEl) && eiEl.TryGetInt32(out var ei) ? ei : 3600;");
        sb.AppendLine("        return (accessToken, refreshToken, expiresIn);");
        sb.AppendLine("    }");
        sb.AppendLine("    catch (JsonException)");
        sb.AppendLine("    {");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static Task<(string AccessToken, string? RefreshToken, int ExpiresIn)?> ExchangeCodeForTokenAsync(HttpClient http, JsonElement profile, string tokenUrl, string clientId, string code, string verifier, string callbackUrl, JsonElement? secrets) =>");
        sb.AppendLine("    PostTokenRequestAsync(http, profile, tokenUrl, clientId, new Dictionary<string, string> { [\"grant_type\"] = \"authorization_code\", [\"code\"] = code, [\"redirect_uri\"] = callbackUrl, [\"code_verifier\"] = verifier, [\"client_id\"] = clientId }, secrets);");
        sb.AppendLine();

        sb.AppendLine("static Task<(string AccessToken, string? RefreshToken, int ExpiresIn)?> FetchClientCredentialsTokenAsync(HttpClient http, JsonElement profile, string tokenUrl, string clientId, JsonElement? secrets) =>");
        sb.AppendLine("    PostTokenRequestAsync(http, profile, tokenUrl, clientId, new Dictionary<string, string> { [\"grant_type\"] = \"client_credentials\", [\"client_id\"] = clientId }, secrets);");
        sb.AppendLine();

        sb.AppendLine("static Task<(string AccessToken, string? RefreshToken, int ExpiresIn)?> RefreshOAuthTokenAsync(HttpClient http, JsonElement profile, string tokenUrl, string clientId, string refreshToken, JsonElement? secrets) =>");
        sb.AppendLine("    PostTokenRequestAsync(http, profile, tokenUrl, clientId, new Dictionary<string, string> { [\"grant_type\"] = \"refresh_token\", [\"refresh_token\"] = refreshToken, [\"client_id\"] = clientId }, secrets);");
        sb.AppendLine();
    }

    private static void AppendOAuthTokenCacheFunctions(StringBuilder sb)
    {
        sb.AppendLine("static string TokenCachePath([CallerFilePath] string callerPath = \"\")");
        sb.AppendLine("{");
        sb.AppendLine("    var scriptDir = Path.GetDirectoryName(callerPath) ?? \".\";");
        sb.AppendLine("    return Path.Combine(scriptDir, \"..\", \".auth-cache.json\");");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static async Task<Dictionary<string, JsonElement>> ReadTokenCacheAsync(string path)");
        sb.AppendLine("{");
        sb.AppendLine("    var result = new Dictionary<string, JsonElement>(StringComparer.Ordinal);");
        sb.AppendLine("    if (!File.Exists(path)) return result;");
        sb.AppendLine("    try");
        sb.AppendLine("    {");
        sb.AppendLine("        using var doc = JsonDocument.Parse(await File.ReadAllTextAsync(path));");
        sb.AppendLine("        foreach (var prop in doc.RootElement.EnumerateObject()) result[prop.Name] = prop.Value.Clone();");
        sb.AppendLine("    }");
        sb.AppendLine("    catch (JsonException) { }");
        sb.AppendLine("    return result;");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static async Task WriteTokenCacheAsync(string path, Dictionary<string, JsonElement> cache)");
        sb.AppendLine("{");
        sb.AppendLine("    var obj = new JsonObject();");
        sb.AppendLine("    foreach (var (key, value) in cache) obj[key] = JsonNode.Parse(value.GetRawText());");
        sb.AppendLine("    var tmpPath = path + \".tmp-\" + Guid.NewGuid().ToString(\"N\");");
        sb.AppendLine("    await File.WriteAllTextAsync(tmpPath, obj.ToJsonString(new JsonSerializerOptions { WriteIndented = true }));");
        sb.AppendLine("    if (!OperatingSystem.IsWindows())");
        sb.AppendLine("    {");
        sb.AppendLine("        File.SetUnixFileMode(tmpPath, UnixFileMode.UserRead | UnixFileMode.UserWrite);");
        sb.AppendLine("    }");
        sb.AppendLine("    File.Move(tmpPath, path, overwrite: true);");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static void StoreTokenInCache(Dictionary<string, JsonElement> cache, string profileName, (string AccessToken, string? RefreshToken, int ExpiresIn) token)");
        sb.AppendLine("{");
        sb.AppendLine("    var obj = new JsonObject { [\"access_token\"] = token.AccessToken, [\"expires_at\"] = DateTimeOffset.UtcNow.AddSeconds(token.ExpiresIn).ToString(\"o\") };");
        sb.AppendLine("    if (token.RefreshToken is not null) obj[\"refresh_token\"] = token.RefreshToken;");
        sb.AppendLine("    cache[profileName] = JsonDocument.Parse(obj.ToJsonString()).RootElement.Clone();");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static async Task<T> WithTokenCacheLockAsync<T>(Func<Task<T>> action)");
        sb.AppendLine("{");
        sb.AppendLine("    var lockPath = TokenCachePath() + \".lock\";");
        sb.AppendLine("    FileStream? lockStream = null;");
        sb.AppendLine("    for (var attempt = 0; attempt < 100 && lockStream is null; attempt++)");
        sb.AppendLine("    {");
        sb.AppendLine("        try { lockStream = new FileStream(lockPath, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None); }");
        sb.AppendLine("        catch (IOException) { await Task.Delay(50); }");
        sb.AppendLine("    }");
        sb.AppendLine("    if (lockStream is null)");
        sb.AppendLine("    {");
        sb.AppendLine("        throw new AuthResolutionException(\"Could not acquire the token cache lock (.auth-cache.json.lock) after multiple attempts \\u2014 another process may be stuck holding it.\");");
        sb.AppendLine("    }");
        sb.AppendLine("    try { return await action(); }");
        sb.AppendLine("    finally { lockStream.Dispose(); }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static async Task<string> ResolveOAuthAccessTokenAsync(HttpClient http, JsonElement profile, string profileName, JsonElement? secrets)");
        sb.AppendLine("{");
        sb.AppendLine("    var (_, tokenUrl, _) = ResolveOAuthEndpoints(profile);");
        sb.AppendLine("    if (tokenUrl is null) throw new AuthResolutionException($\"Auth profile '{profileName}' (oauth2) has no tokenUrl configured (directly or via a preset).\");");
        sb.AppendLine("    var clientId = ResolveSecretOrLiteral(GetProp(profile, \"clientId\"), secrets);");
        sb.AppendLine("    var grant = GetProp(profile, \"grant\");");
        sb.AppendLine("    var cachePath = TokenCachePath();");
        sb.AppendLine();
        sb.AppendLine("    return await WithTokenCacheLockAsync(async () =>");
        sb.AppendLine("    {");
        sb.AppendLine("        var cache = await ReadTokenCacheAsync(cachePath);");
        sb.AppendLine("        if (cache.TryGetValue(profileName, out var entry))");
        sb.AppendLine("        {");
        sb.AppendLine("            var expiresAt = entry.TryGetProperty(\"expires_at\", out var eaEl) && DateTimeOffset.TryParse(eaEl.GetString(), out var ea) ? ea : DateTimeOffset.MinValue;");
        sb.AppendLine("            var cachedToken = entry.TryGetProperty(\"access_token\", out var atEl) ? atEl.GetString() : null;");
        sb.AppendLine("            if (cachedToken is not null && expiresAt > DateTimeOffset.UtcNow.AddSeconds(30))");
        sb.AppendLine("            {");
        sb.AppendLine("                return cachedToken;");
        sb.AppendLine("            }");
        sb.AppendLine("            var refreshToken = entry.TryGetProperty(\"refresh_token\", out var rtEl) ? rtEl.GetString() : null;");
        sb.AppendLine("            if (refreshToken is not null)");
        sb.AppendLine("            {");
        sb.AppendLine("                var refreshed = await RefreshOAuthTokenAsync(http, profile, tokenUrl, clientId, refreshToken, secrets);");
        sb.AppendLine("                if (refreshed is not null)");
        sb.AppendLine("                {");
        sb.AppendLine("                    StoreTokenInCache(cache, profileName, refreshed.Value);");
        sb.AppendLine("                    await WriteTokenCacheAsync(cachePath, cache);");
        sb.AppendLine("                    return refreshed.Value.AccessToken;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (grant == \"client_credentials\")");
        sb.AppendLine("        {");
        sb.AppendLine("            var fetched = await FetchClientCredentialsTokenAsync(http, profile, tokenUrl, clientId, secrets);");
        sb.AppendLine("            if (fetched is not null)");
        sb.AppendLine("            {");
        sb.AppendLine("                StoreTokenInCache(cache, profileName, fetched.Value);");
        sb.AppendLine("                await WriteTokenCacheAsync(cachePath, cache);");
        sb.AppendLine("                return fetched.Value.AccessToken;");
        sb.AppendLine("            }");
        sb.AppendLine("            throw new AuthResolutionException($\"Failed to obtain a client_credentials token for auth profile '{profileName}'.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        throw new AuthResolutionException($\"No valid or refreshable token for auth profile '{profileName}'. Run: dotnet run scripts/call.cs -- login {profileName}\");");
        sb.AppendLine("    });");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendOAuthLoginFunction(StringBuilder sb)
    {
        sb.AppendLine("static async Task<int> LoginAsync(string profileName)");
        sb.AppendLine("{");
        sb.AppendLine("    var authConfig = LoadAuthConfig();");
        sb.AppendLine("    var profiles = authConfig is { } cfg && cfg.TryGetProperty(\"profiles\", out var profilesEl) ? profilesEl : (JsonElement?)null;");
        sb.AppendLine("    var profile = FindProfile(profiles, profileName);");
        sb.AppendLine("    if (profile is null)");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine($\"No auth profile named '{profileName}' in auth.json.\");");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine("    var type = GetProp(profile.Value, \"type\");");
        sb.AppendLine("    if (type != \"oauth2\")");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine($\"Profile '{profileName}' is type '{type}', not 'oauth2' \\u2014 login is only applicable to oauth2 profiles.\");");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine("    var grant = GetProp(profile.Value, \"grant\");");
        sb.AppendLine("    if (grant == \"client_credentials\")");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.WriteLine($\"Profile '{profileName}' uses client_credentials \\u2014 not applicable: no interactive login is needed, a token is obtained automatically at call time.\");");
        sb.AppendLine("        return 0;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    var (authUrl, tokenUrl, scopes) = ResolveOAuthEndpoints(profile.Value);");
        sb.AppendLine("    if (authUrl is null || tokenUrl is null)");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine($\"Profile '{profileName}' is missing authUrl/tokenUrl (directly or via a preset).\");");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine("    var callbackUrl = GetProp(profile.Value, \"callbackUrl\");");
        sb.AppendLine("    if (callbackUrl.Length == 0) callbackUrl = \"http://localhost:8400/callback\";");
        sb.AppendLine("    var secrets = LoadSecrets();");
        sb.AppendLine("    var clientId = ResolveSecretOrLiteral(GetProp(profile.Value, \"clientId\"), secrets);");
        sb.AppendLine();
        sb.AppendLine("    var (verifier, challenge) = GeneratePkce();");
        sb.AppendLine("    var state = GenerateState();");
        sb.AppendLine("    var authorizeUrl = BuildAuthorizeUrl(authUrl, clientId, callbackUrl, scopes, challenge, state, profile.Value);");
        sb.AppendLine();
        sb.AppendLine("    HttpListener callbackListener;");
        sb.AppendLine("    try { callbackListener = BeginCallbackListener(callbackUrl); }");
        sb.AppendLine("    catch (AuthResolutionException ex) { Console.Error.WriteLine(ex.Message); return 2; }");
        sb.AppendLine("    Console.WriteLine($\"Listening for OAuth callback on {callbackUrl} ...\");");
        sb.AppendLine();
        sb.AppendLine("    var browserLaunch = GetProp(profile.Value, \"browserLaunch\");");
        sb.AppendLine("    if (browserLaunch == \"clipboard\")");
        sb.AppendLine("    {");
        sb.AppendLine("        var copied = TryCopyToClipboard(authorizeUrl);");
        sb.AppendLine("        Console.WriteLine(copied");
        sb.AppendLine("            ? $\"Copied the sign-in URL to your clipboard for profile '{profileName}'. Paste it into your browser:\"");
        sb.AppendLine("            : $\"Could not copy the sign-in URL to the clipboard automatically. Open this URL to sign in for profile '{profileName}':\");");
        sb.AppendLine("        Console.WriteLine(authorizeUrl);");
        sb.AppendLine("    }");
        sb.AppendLine("    else");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.WriteLine($\"Opening your browser to sign in for profile '{profileName}'...\");");
        sb.AppendLine("        var browserLaunched = TryLaunchBrowser(authorizeUrl);");
        sb.AppendLine("        Console.WriteLine(browserLaunched");
        sb.AppendLine("            ? \"If it did not open, visit this URL to sign in:\"");
        sb.AppendLine("            : \"Could not launch a browser automatically. Open this URL to sign in:\");");
        sb.AppendLine("        Console.WriteLine(authorizeUrl);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    Dictionary<string, string> callbackParams;");
        sb.AppendLine("    try { callbackParams = await AwaitOAuthCallbackAsync(callbackListener); }");
        sb.AppendLine("    catch (AuthResolutionException ex) { Console.Error.WriteLine(ex.Message); return 2; }");
        sb.AppendLine();
        sb.AppendLine("    if (!callbackParams.TryGetValue(\"state\", out var returnedState) || returnedState != state)");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine(\"The callback's state did not match what was sent \\u2014 rejecting (possible CSRF/mix-up). No token was stored. Run login again.\");");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine("    if (!callbackParams.TryGetValue(\"code\", out var code))");
        sb.AppendLine("    {");
        sb.AppendLine("        var err = callbackParams.TryGetValue(\"error\", out var e) ? e : \"no authorization code was returned\";");
        sb.AppendLine("        Console.Error.WriteLine($\"Login failed: {err}\");");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    using var http = new HttpClient();");
        sb.AppendLine("    var tokenResponse = await ExchangeCodeForTokenAsync(http, profile.Value, tokenUrl, clientId, code, verifier, callbackUrl, secrets);");
        sb.AppendLine("    if (tokenResponse is null)");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine(\"Failed to exchange the authorization code for a token.\");");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    await WithTokenCacheLockAsync(async () =>");
        sb.AppendLine("    {");
        sb.AppendLine("        var cachePath = TokenCachePath();");
        sb.AppendLine("        var cache = await ReadTokenCacheAsync(cachePath);");
        sb.AppendLine("        StoreTokenInCache(cache, profileName, tokenResponse.Value);");
        sb.AppendLine("        await WriteTokenCacheAsync(cachePath, cache);");
        sb.AppendLine("        return true;");
        sb.AppendLine("    });");
        sb.AppendLine();
        sb.AppendLine("    Console.WriteLine($\"Login succeeded for profile '{profileName}'. You can now call operations that use it.\");");
        sb.AppendLine("    return 0;");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// <c>browserLaunch: "clipboard"</c> (US OAuth manual-browser login): copies the authorize URL
    /// to the system clipboard via native OS tools instead of launching a browser — no new NuGet
    /// dependency, mirroring how <c>TryLaunchBrowser</c> already shells out to <c>open</c>/<c>xdg-open</c>/<c>cmd</c>.
    /// </summary>
    private static void AppendClipboardFunctions(StringBuilder sb)
    {
        sb.AppendLine("static bool RunClipboardCommand(string fileName, string[] args, string text)");
        sb.AppendLine("{");
        sb.AppendLine("    try");
        sb.AppendLine("    {");
        sb.AppendLine("        var psi = new ProcessStartInfo(fileName) { RedirectStandardInput = true, UseShellExecute = false, CreateNoWindow = true };");
        sb.AppendLine("        foreach (var a in args) psi.ArgumentList.Add(a);");
        sb.AppendLine("        using var process = Process.Start(psi);");
        sb.AppendLine("        if (process is null) return false;");
        sb.AppendLine("        process.StandardInput.Write(text);");
        sb.AppendLine("        process.StandardInput.Close();");
        sb.AppendLine("        process.WaitForExit();");
        sb.AppendLine("        return process.ExitCode == 0;");
        sb.AppendLine("    }");
        sb.AppendLine("    catch");
        sb.AppendLine("    {");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("static bool TryCopyToClipboard(string text)");
        sb.AppendLine("{");
        sb.AppendLine("    if (OperatingSystem.IsMacOS()) return RunClipboardCommand(\"pbcopy\", Array.Empty<string>(), text);");
        sb.AppendLine("    if (OperatingSystem.IsWindows()) return RunClipboardCommand(\"clip\", Array.Empty<string>(), text);");
        sb.AppendLine("    if (OperatingSystem.IsLinux())");
        sb.AppendLine("    {");
        sb.AppendLine("        return RunClipboardCommand(\"wl-copy\", Array.Empty<string>(), text)");
        sb.AppendLine("            || RunClipboardCommand(\"xclip\", new[] { \"-selection\", \"clipboard\" }, text)");
        sb.AppendLine("            || RunClipboardCommand(\"xsel\", new[] { \"--clipboard\", \"--input\" }, text);");
        sb.AppendLine("    }");
        sb.AppendLine("    return false;");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendParseArgsFunction(StringBuilder sb)
    {
        sb.AppendLine("static (Dictionary<string, string> Params, string? Body) ParseArgs(string[] rest)");
        sb.AppendLine("{");
        sb.AppendLine("    var values = new Dictionary<string, string>(StringComparer.Ordinal);");
        sb.AppendLine("    string? body = null;");
        sb.AppendLine("    for (var i = 0; i < rest.Length; i++)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!rest[i].StartsWith(\"--\", StringComparison.Ordinal) || i + 1 >= rest.Length)");
        sb.AppendLine("        {");
        sb.AppendLine("            continue;");
        sb.AppendLine("        }");
        sb.AppendLine("        var key = rest[i][2..];");
        sb.AppendLine("        var value = rest[++i];");
        sb.AppendLine("        if (key == \"body\") { body = value; } else { values[key] = value; }");
        sb.AppendLine("    }");
        sb.AppendLine("    return (values, body);");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendDataTables(StringBuilder sb, SkillModel model)
    {
        sb.AppendLine("static Dictionary<string, OperationSpec> BuildOperations() => new()");
        sb.AppendLine("{");
        foreach (var op in EmitterOperations.DistinctByOperationId(model))
        {
            sb.Append("    [").Append(Literal(op.OperationId)).Append("] = new(")
              .Append(Literal(op.Method.Method)).Append(", ")
              .Append(Literal(op.PathTemplate)).Append(", [")
              .Append(string.Join(", ", op.Parameters.Select(p => $"new({Literal(p.Name)}, {Literal(LocationKey(p.In))})")))
              .Append("], ")
              .Append(op.RequestBody is not null ? "true" : "false").Append(", ")
              .Append(op.RequestBody?.ContentType is { } ct ? Literal(ct) : "null").Append(", [")
              .Append(string.Join(", ", op.SecuritySchemeIds.Select(Literal)))
              .Append("], [")
              .Append(string.Join(", ", op.AuthProfileNames.Select(Literal)))
              .Append("]),")
              .AppendLine();
        }
        sb.AppendLine("};");
        sb.AppendLine();

        sb.AppendLine("static Dictionary<string, SchemeSpec> BuildSchemes() => new()");
        sb.AppendLine("{");
        foreach (var scheme in model.SecuritySchemes)
        {
            sb.Append("    [").Append(Literal(scheme.Id)).Append("] = new(")
              .Append(Literal(scheme.Id)).Append(", ")
              .Append(Literal(SchemeKindKey(scheme.Kind))).Append(", ")
              .Append(scheme.ApiKeyName is { } akn ? Literal(akn) : "null").Append(", ")
              .Append(scheme.ApiKeyLocation == ApiKeyLocation.Query ? Literal("query") : scheme.ApiKeyLocation is not null ? Literal("header") : "null").Append(", ")
              .Append(scheme.OAuthTokenUrl is { } url ? Literal(url) : "null")
              .Append("),")
              .AppendLine();
        }
        sb.AppendLine("};");
        sb.AppendLine();

        sb.AppendLine("sealed record ParamSpec(string Name, string Location);");
        sb.AppendLine("sealed record OperationSpec(string Method, string PathTemplate, ParamSpec[] Parameters, bool HasBody, string? BodyContentType, string[] SecuritySchemeIds, string[] AuthProfileNames);");
        sb.AppendLine("sealed record SchemeSpec(string Id, string Kind, string? ApiKeyName, string? ApiKeyLocation, string? OAuthTokenUrl);");
        sb.AppendLine("sealed class AuthResolutionException(string message) : Exception(message);");
    }

    private static string LocationKey(ParameterLocation location) => location switch
    {
        ParameterLocation.Path => "path",
        ParameterLocation.Header => "header",
        _ => "query",
    };

    private static string SchemeKindKey(SecuritySchemeKind kind) => kind switch
    {
        SecuritySchemeKind.ApiKey => "apiKey",
        SecuritySchemeKind.Bearer => "bearer",
        SecuritySchemeKind.Basic => "basic",
        SecuritySchemeKind.OAuth2 => "oauth2",
        _ => "unsupported",
    };

    /// <summary>Renders a C# string literal, escaping backslashes/quotes/control characters.</summary>
    private static string Literal(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
