using System.Text;
using Api2Skill.Model;

namespace Api2Skill.Emit;

/// <summary>
/// The <c>.csx</c> emitter (D3/US4): a C# script run via the <c>dotnet-script</c> global tool
/// (<c>dotnet script call.csx --</c>). Requires <c>dotnet tool install -g dotnet-script</c> —
/// the only one of the three emitters with an extra install (FR-006b; SKILL.md says so).
///
/// Verified empirically that dotnet-script's top-level scripting is meaningfully MORE
/// permissive than a .NET 10 file-based app: `static readonly` fields, `await` directly at the
/// top level, and local functions are all fine there — none of the restructuring
/// <see cref="CsFileEmitter"/> needed (the earlier top-level-statement bugs) apply here, so
/// this emitter is a flatter, more direct translation of the same dispatch logic.
/// </summary>
public sealed class CsxEmitter : IScriptEmitter
{
    public string Key => "csx";

    public string FileExtension => "csx";

    public string RunnerDescription => "dotnet script scripts/call.csx --";

    public void Emit(SkillModel model, DirectoryInfo skillDirectory)
    {
        var scriptsDirectory = Directory.CreateDirectory(Path.Combine(skillDirectory.FullName, "scripts"));
        File.WriteAllText(Path.Combine(scriptsDirectory.FullName, "call.csx"), Generate(model));
    }

    private static string Generate(SkillModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by api2skill — do not edit by hand; re-run the generator instead.");
        sb.AppendLine("// Requires: dotnet tool install -g dotnet-script");
        sb.AppendLine("// Usage: dotnet script call.csx -- <operationId> [--<param> <value> ...] [--body <json|@file>]");
        // dotnet-script does NOT enable nullable-reference-types by default (unlike a
        // modern .csproj) — without this, the `string?` annotations below fail with CS8632.
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Headers;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine();

        sb.AppendLine("var scriptDir = Path.GetDirectoryName(GetScriptPath());");
        sb.AppendLine("return await Run(Args.ToArray(), scriptDir!);");
        sb.AppendLine();

        sb.AppendLine("string GetScriptPath([System.Runtime.CompilerServices.CallerFilePath] string path = \"\") => path;");
        sb.AppendLine();

        AppendRunFunction(sb, model);
        AppendAuthFunctions(sb);
        AppendParseArgsFunction(sb);
        AppendDataTables(sb, model);

        return sb.ToString();
    }

    private static void AppendRunFunction(StringBuilder sb, SkillModel model)
    {
        sb.AppendLine("async Task<int> Run(string[] args, string scriptDir)");
        sb.AppendLine("{");
        sb.AppendLine("    var operations = BuildOperations();");
        sb.AppendLine("    var schemes = BuildSchemes();");
        sb.AppendLine();
        sb.AppendLine("    if (args.Length == 0 || args[0] is \"-h\" or \"--help\")");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine(\"Usage: dotnet script call.csx -- <operationId> [--<param> <value> ...] [--body <json|@file>]\");");
        sb.AppendLine("        Console.Error.WriteLine(\"Known operations: \" + string.Join(\", \", operations.Keys.OrderBy(k => k, StringComparer.Ordinal)));");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    var operationId = args[0];");
        sb.AppendLine("    if (!operations.TryGetValue(operationId, out var op))");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine($\"Unknown operationId '{operationId}'.\");");
        sb.AppendLine("        Console.Error.WriteLine(\"Known operations: \" + string.Join(\", \", operations.Keys.OrderBy(k => k, StringComparer.Ordinal)));");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    var (paramValues, body) = ParseArgs(args.Skip(1).ToArray());");
        sb.AppendLine("    var secrets = LoadSecrets(scriptDir);");
        sb.AppendLine();
        sb.AppendLine($"    var configuredBaseUrl = {SecretsLookup("baseUrl")} ?? {Literal(model.BaseUrl ?? string.Empty)};");
        sb.AppendLine("    var baseUrl = Environment.GetEnvironmentVariable(\"API2SKILL_BASE_URL\") ?? configuredBaseUrl;");
        sb.AppendLine("    if (string.IsNullOrWhiteSpace(baseUrl))");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine(\"No base URL configured. Set API2SKILL_BASE_URL or add \\\"baseUrl\\\" to secrets.json.\");");
        sb.AppendLine("        return 2;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    var path = op.PathTemplate;");
        sb.AppendLine("    var query = new List<string>();");
        sb.AppendLine("    var headers = new List<(string Name, string Value)>();");
        sb.AppendLine("    foreach (var p in op.Parameters)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!paramValues.TryGetValue(p.Name, out var value)) continue;");
        sb.AppendLine("        switch (p.Location)");
        sb.AppendLine("        {");
        sb.AppendLine("            case \"path\": path = path.Replace(\"{\" + p.Name + \"}\", Uri.EscapeDataString(value)); break;");
        sb.AppendLine("            case \"query\": query.Add($\"{Uri.EscapeDataString(p.Name)}={Uri.EscapeDataString(value)}\"); break;");
        sb.AppendLine("            case \"header\": headers.Add((p.Name, value)); break;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    using var handler = new HttpClientHandler();");
        sb.AppendLine($"    var insecureDefault = {Literal(model.InsecureDefault ? "1" : "0")};");
        sb.AppendLine("    if ((Environment.GetEnvironmentVariable(\"API2SKILL_INSECURE\") ?? insecureDefault) == \"1\")");
        sb.AppendLine("    {");
        sb.AppendLine("        // Dev-only: accepts self-signed/invalid TLS certificates. Never enable in production.");
        sb.AppendLine("        handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;");
        sb.AppendLine("    }");
        sb.AppendLine("    using var http = new HttpClient(handler);");
        sb.AppendLine();
        sb.AppendLine("    try");
        sb.AppendLine("    {");
        sb.AppendLine("        var oauthTokenCache = new Dictionary<string, string>(StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var schemeId in op.SecuritySchemeIds)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!schemes.TryGetValue(schemeId, out var scheme))");
        sb.AppendLine("            {");
        sb.AppendLine("                continue;");
        sb.AppendLine("            }");
        sb.AppendLine("            await ApplyAuthAsync(http, scheme, secrets, query, headers, oauthTokenCache);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var url = baseUrl.TrimEnd('/') + path + (query.Count > 0 ? \"?\" + string.Join(\"&\", query) : \"\");");
        sb.AppendLine();
        sb.AppendLine("        using var request = new HttpRequestMessage(new HttpMethod(op.Method), url);");
        sb.AppendLine("        foreach (var (name, value) in headers)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (value.AsSpan().IndexOfAny('\\r', '\\n') >= 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                Console.Error.WriteLine($\"Invalid value for header '{name}': control characters are not allowed.\");");
        sb.AppendLine("                return 2;");
        sb.AppendLine("            }");
        sb.AppendLine("            request.Headers.TryAddWithoutValidation(name, value);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (op.HasBody)");
        sb.AppendLine("        {");
        sb.AppendLine("            var bodyText = body ?? \"{}\";");
        sb.AppendLine("            if (bodyText.StartsWith('@'))");
        sb.AppendLine("            {");
        sb.AppendLine("                bodyText = File.ReadAllText(bodyText[1..]);");
        sb.AppendLine("            }");
        sb.AppendLine("            request.Content = new StringContent(bodyText, Encoding.UTF8, op.BodyContentType ?? \"application/json\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        using var response = await http.SendAsync(request);");
        sb.AppendLine("        var responseText = await response.Content.ReadAsStringAsync();");
        sb.AppendLine("        Console.WriteLine(responseText);");
        sb.AppendLine("        if (!response.IsSuccessStatusCode)");
        sb.AppendLine("        {");
        sb.AppendLine("            Console.Error.WriteLine($\"HTTP {(int)response.StatusCode} {response.StatusCode}\");");
        sb.AppendLine("            return 1;");
        sb.AppendLine("        }");
        sb.AppendLine("        return 0;");
        sb.AppendLine("    }");
        sb.AppendLine("    catch (HttpRequestException ex)");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine($\"Network error calling {baseUrl}: {ex.Message}\");");
        sb.AppendLine("        return 3;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string SecretsLookup(string key) =>
        $"(secrets.HasValue && secrets.Value.TryGetProperty({Literal(key)}, out var {key}El) ? {key}El.GetString() : null)";

    private static void AppendAuthFunctions(StringBuilder sb)
    {
        // Unlike CsFileEmitter, the script's own directory is passed in explicitly (resolved
        // once at the top via CallerFilePath) rather than re-resolved per call — dotnet-script
        // doesn't need the [CallerFilePath] default-parameter trick repeated per function since
        // ordinary closures over a script-level variable work fine here.
        sb.AppendLine("JsonElement? LoadSecrets(string scriptDir)");
        sb.AppendLine("{");
        sb.AppendLine("    var secretsPath = Path.Combine(scriptDir, \"..\", \"secrets.json\");");
        sb.AppendLine("    if (!File.Exists(secretsPath))");
        sb.AppendLine("    {");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("    try");
        sb.AppendLine("    {");
        sb.AppendLine("        using var doc = JsonDocument.Parse(File.ReadAllText(secretsPath));");
        sb.AppendLine("        return doc.RootElement.Clone();");
        sb.AppendLine("    }");
        sb.AppendLine("    catch (JsonException ex)");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.Error.WriteLine($\"warning: secrets.json is not valid JSON ({ex.Message}); proceeding as if no secrets were configured.\");");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("string? SecretValue(JsonElement? secrets, string schemeId, string key)");
        sb.AppendLine("{");
        sb.AppendLine("    if (secrets is not { } root) return null;");
        sb.AppendLine("    if (!root.TryGetProperty(schemeId, out var entry)) return null;");
        sb.AppendLine("    return entry.TryGetProperty(key, out var value) ? value.GetString() : null;");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("async Task ApplyAuthAsync(HttpClient http, SchemeSpec scheme, JsonElement? secrets, List<string> query, List<(string Name, string Value)> headers, Dictionary<string, string> oauthTokenCache)");
        sb.AppendLine("{");
        sb.AppendLine("    switch (scheme.Kind)");
        sb.AppendLine("    {");
        sb.AppendLine("        case \"apiKey\":");
        sb.AppendLine("        {");
        sb.AppendLine("            var key = SecretValue(secrets, scheme.Id, \"apiKey\");");
        sb.AppendLine("            if (key is null) { Console.Error.WriteLine($\"warning: no apiKey configured for scheme '{scheme.Id}' in secrets.json — sending unauthenticated.\"); break; }");
        sb.AppendLine("            if (scheme.ApiKeyLocation == \"query\") query.Add($\"{Uri.EscapeDataString(scheme.ApiKeyName!)}={Uri.EscapeDataString(key)}\");");
        sb.AppendLine("            else headers.Add((scheme.ApiKeyName!, key));");
        sb.AppendLine("            break;");
        sb.AppendLine("        }");
        sb.AppendLine("        case \"bearer\":");
        sb.AppendLine("        {");
        sb.AppendLine("            var token = SecretValue(secrets, scheme.Id, \"bearerToken\");");
        sb.AppendLine("            if (token is null) { Console.Error.WriteLine($\"warning: no bearerToken configured for scheme '{scheme.Id}' in secrets.json — sending unauthenticated.\"); break; }");
        sb.AppendLine("            headers.Add((\"Authorization\", $\"Bearer {token}\"));");
        sb.AppendLine("            break;");
        sb.AppendLine("        }");
        sb.AppendLine("        case \"basic\":");
        sb.AppendLine("        {");
        sb.AppendLine("            var user = SecretValue(secrets, scheme.Id, \"username\");");
        sb.AppendLine("            var pass = SecretValue(secrets, scheme.Id, \"password\");");
        sb.AppendLine("            if (user is null || pass is null) { Console.Error.WriteLine($\"warning: no username/password configured for scheme '{scheme.Id}' in secrets.json — sending unauthenticated.\"); break; }");
        sb.AppendLine("            var encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes($\"{user}:{pass}\"));");
        sb.AppendLine("            headers.Add((\"Authorization\", $\"Basic {encoded}\"));");
        sb.AppendLine("            break;");
        sb.AppendLine("        }");
        sb.AppendLine("        case \"oauth2\":");
        sb.AppendLine("        {");
        sb.AppendLine("            var clientId = SecretValue(secrets, scheme.Id, \"clientId\");");
        sb.AppendLine("            var clientSecret = SecretValue(secrets, scheme.Id, \"clientSecret\");");
        sb.AppendLine("            var tokenUrl = SecretValue(secrets, scheme.Id, \"tokenUrl\") ?? scheme.OAuthTokenUrl;");
        sb.AppendLine("            if (clientId is null || clientSecret is null || tokenUrl is null) { Console.Error.WriteLine($\"warning: no clientId/clientSecret/tokenUrl configured for scheme '{scheme.Id}' in secrets.json — sending unauthenticated.\"); break; }");
        sb.AppendLine("            var token = await FetchOAuth2TokenAsync(http, tokenUrl, clientId, clientSecret, oauthTokenCache);");
        sb.AppendLine("            if (token is null) { Console.Error.WriteLine($\"warning: failed to obtain an OAuth2 token for scheme '{scheme.Id}' — sending unauthenticated.\"); break; }");
        sb.AppendLine("            headers.Add((\"Authorization\", $\"Bearer {token}\"));");
        sb.AppendLine("            break;");
        sb.AppendLine("        }");
        sb.AppendLine("        default:");
        sb.AppendLine("            Console.Error.WriteLine($\"warning: scheme '{scheme.Id}' ({scheme.Kind}) is not a supported auth kind — sending unauthenticated.\");");
        sb.AppendLine("            break;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("async Task<string?> FetchOAuth2TokenAsync(HttpClient http, string tokenUrl, string clientId, string clientSecret, Dictionary<string, string> tokenCache)");
        sb.AppendLine("{");
        sb.AppendLine("    var cacheKey = tokenUrl + \"|\" + clientId;");
        sb.AppendLine("    if (tokenCache.TryGetValue(cacheKey, out var cached))");
        sb.AppendLine("    {");
        sb.AppendLine("        return cached;");
        sb.AppendLine("    }");
        sb.AppendLine("    var form = new FormUrlEncodedContent(new Dictionary<string, string>");
        sb.AppendLine("    {");
        sb.AppendLine("        [\"grant_type\"] = \"client_credentials\",");
        sb.AppendLine("        [\"client_id\"] = clientId,");
        sb.AppendLine("        [\"client_secret\"] = clientSecret,");
        sb.AppendLine("    });");
        sb.AppendLine("    using var response = await http.PostAsync(tokenUrl, form);");
        sb.AppendLine("    if (!response.IsSuccessStatusCode)");
        sb.AppendLine("    {");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("    try");
        sb.AppendLine("    {");
        sb.AppendLine("        using var doc = JsonDocument.Parse(await response.Content.ReadAsStringAsync());");
        sb.AppendLine("        if (!doc.RootElement.TryGetProperty(\"access_token\", out var tokenEl))");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine("        var token = tokenEl.GetString();");
        sb.AppendLine("        if (token is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            tokenCache[cacheKey] = token;");
        sb.AppendLine("        }");
        sb.AppendLine("        return token;");
        sb.AppendLine("    }");
        sb.AppendLine("    catch (JsonException)");
        sb.AppendLine("    {");
        sb.AppendLine("        // The token endpoint returned a 2xx with a body that isn't valid JSON — treat");
        sb.AppendLine("        // the same as a failed token fetch rather than crashing the whole dispatch.");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendParseArgsFunction(StringBuilder sb)
    {
        sb.AppendLine("(Dictionary<string, string> Params, string? Body) ParseArgs(string[] rest)");
        sb.AppendLine("{");
        sb.AppendLine("    var values = new Dictionary<string, string>(StringComparer.Ordinal);");
        sb.AppendLine("    string? body = null;");
        sb.AppendLine("    for (var i = 0; i < rest.Length; i++)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!rest[i].StartsWith(\"--\", StringComparison.Ordinal) || i + 1 >= rest.Length)");
        sb.AppendLine("        {");
        sb.AppendLine("            continue;");
        sb.AppendLine("        }");
        sb.AppendLine("        var key = rest[i][2..];");
        sb.AppendLine("        var value = rest[++i];");
        sb.AppendLine("        if (key == \"body\") { body = value; } else { values[key] = value; }");
        sb.AppendLine("    }");
        sb.AppendLine("    return (values, body);");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendDataTables(StringBuilder sb, SkillModel model)
    {
        sb.AppendLine("Dictionary<string, OperationSpec> BuildOperations() => new()");
        sb.AppendLine("{");
        foreach (var tag in model.Tags)
        {
            foreach (var op in tag.Operations)
            {
                sb.Append("    [").Append(Literal(op.OperationId)).Append("] = new(")
                  .Append(Literal(op.Method.Method)).Append(", ")
                  .Append(Literal(op.PathTemplate)).Append(", [")
                  .Append(string.Join(", ", op.Parameters.Select(p => $"new({Literal(p.Name)}, {Literal(LocationKey(p.In))})")))
                  .Append("], ")
                  .Append(op.RequestBody is not null ? "true" : "false").Append(", ")
                  .Append(op.RequestBody?.ContentType is { } ct ? Literal(ct) : "null").Append(", [")
                  .Append(string.Join(", ", op.SecuritySchemeIds.Select(Literal)))
                  .Append("]),")
                  .AppendLine();
            }
        }
        sb.AppendLine("};");
        sb.AppendLine();

        sb.AppendLine("Dictionary<string, SchemeSpec> BuildSchemes() => new()");
        sb.AppendLine("{");
        foreach (var scheme in model.SecuritySchemes)
        {
            sb.Append("    [").Append(Literal(scheme.Id)).Append("] = new(")
              .Append(Literal(scheme.Id)).Append(", ")
              .Append(Literal(SchemeKindKey(scheme.Kind))).Append(", ")
              .Append(scheme.ApiKeyName is { } akn ? Literal(akn) : "null").Append(", ")
              .Append(scheme.ApiKeyLocation == ApiKeyLocation.Query ? Literal("query") : scheme.ApiKeyLocation is not null ? Literal("header") : "null").Append(", ")
              .Append(scheme.OAuthTokenUrl is { } url ? Literal(url) : "null")
              .Append("),")
              .AppendLine();
        }
        sb.AppendLine("};");
        sb.AppendLine();

        sb.AppendLine("record ParamSpec(string Name, string Location);");
        sb.AppendLine("record OperationSpec(string Method, string PathTemplate, ParamSpec[] Parameters, bool HasBody, string? BodyContentType, string[] SecuritySchemeIds);");
        sb.AppendLine("record SchemeSpec(string Id, string Kind, string? ApiKeyName, string? ApiKeyLocation, string? OAuthTokenUrl);");
    }

    private static string LocationKey(ParameterLocation location) => location switch
    {
        ParameterLocation.Path => "path",
        ParameterLocation.Header => "header",
        _ => "query",
    };

    private static string SchemeKindKey(SecuritySchemeKind kind) => kind switch
    {
        SecuritySchemeKind.ApiKey => "apiKey",
        SecuritySchemeKind.Bearer => "bearer",
        SecuritySchemeKind.Basic => "basic",
        SecuritySchemeKind.OAuth2 => "oauth2",
        _ => "unsupported",
    };

    /// <summary>Renders a C# string literal, escaping backslashes/quotes/control characters.</summary>
    private static string Literal(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
