using System.Text;
using Api2Skill.Model;

namespace Api2Skill.Emit;

/// <summary>
/// The <c>.fsx</c> emitter (D3/US4): an F# script run via <c>dotnet fsi call.fsx --</c>. Ships
/// with the .NET SDK — no extra install. Feature parity with <see cref="CsFileEmitter"/>: all
/// four auth schemes, the untrusted-HTTPS opt-in, and a clean network-error message.
///
/// F# scripts locate their own directory via the compiler-provided <c>__SOURCE_DIRECTORY__</c>
/// constant (verified empirically — the F# analogue of the <c>[CallerFilePath]</c> trick
/// <see cref="CsFileEmitter"/> needs, but built into the language). Async flow uses F#'s
/// <c>task { }</c> computation expression throughout, converted to synchronous execution only
/// once, at the very end, via <c>Async.AwaitTask |> Async.RunSynchronously</c>.
/// </summary>
public sealed class FsxEmitter : IScriptEmitter
{
    public string Key => "fsx";

    public string FileExtension => "fsx";

    public string RunnerDescription => "dotnet fsi scripts/call.fsx --";

    public void Emit(SkillModel model, DirectoryInfo skillDirectory)
    {
        var scriptsDirectory = Directory.CreateDirectory(Path.Combine(skillDirectory.FullName, "scripts"));
        File.WriteAllText(Path.Combine(scriptsDirectory.FullName, "call.fsx"), Generate(model));
    }

    private static string Generate(SkillModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by api2skill — do not edit by hand; re-run the generator instead.");
        sb.AppendLine("// Usage: dotnet fsi call.fsx -- <operationId> [--<param> <value> ...] [--body <json|@file>]");
        sb.AppendLine("open System");
        sb.AppendLine("open System.Collections.Generic");
        sb.AppendLine("open System.Net.Http");
        sb.AppendLine("open System.Text");
        sb.AppendLine("open System.Text.Json");
        sb.AppendLine("open System.Threading.Tasks");
        sb.AppendLine();

        sb.AppendLine("type ParamSpec = { Name: string; Location: string }");
        sb.AppendLine("type OperationSpec = { Method: string; PathTemplate: string; Parameters: ParamSpec list; HasBody: bool; BodyContentType: string option; SecuritySchemeIds: string list }");
        sb.AppendLine("type SchemeSpec = { Id: string; Kind: string; ApiKeyName: string option; ApiKeyLocation: string option; OAuthTokenUrl: string option }");
        sb.AppendLine();

        AppendOperationsMap(sb, model);
        AppendSchemesMap(sb, model);

        sb.AppendLine("let secretsPath = IO.Path.Combine(__SOURCE_DIRECTORY__, \"..\", \"secrets.json\")");
        sb.AppendLine();
        sb.AppendLine("let loadSecrets () : JsonElement option =");
        sb.AppendLine("    if IO.File.Exists(secretsPath) then");
        sb.AppendLine("        try");
        sb.AppendLine("            use doc = JsonDocument.Parse(IO.File.ReadAllText(secretsPath))");
        sb.AppendLine("            Some (doc.RootElement.Clone())");
        sb.AppendLine("        with :? JsonException as ex ->");
        sb.AppendLine("            eprintfn \"warning: secrets.json is not valid JSON (%s); proceeding as if no secrets were configured.\" ex.Message");
        sb.AppendLine("            None");
        sb.AppendLine("    else");
        sb.AppendLine("        None");
        sb.AppendLine();
        sb.AppendLine("let topLevelSecret (secrets: JsonElement option) (key: string) : string option =");
        sb.AppendLine("    match secrets with");
        sb.AppendLine("    | None -> None");
        sb.AppendLine("    | Some root ->");
        sb.AppendLine("        match root.TryGetProperty(key) with");
        sb.AppendLine("        | true, v -> Some (v.GetString())");
        sb.AppendLine("        | false, _ -> None");
        sb.AppendLine();
        sb.AppendLine("let schemeSecret (secrets: JsonElement option) (schemeId: string) (key: string) : string option =");
        sb.AppendLine("    match secrets with");
        sb.AppendLine("    | None -> None");
        sb.AppendLine("    | Some root ->");
        sb.AppendLine("        match root.TryGetProperty(schemeId) with");
        sb.AppendLine("        | false, _ -> None");
        sb.AppendLine("        | true, entry ->");
        sb.AppendLine("            match entry.TryGetProperty(key) with");
        sb.AppendLine("            | true, v -> Some (v.GetString())");
        sb.AppendLine("            | false, _ -> None");
        sb.AppendLine();

        sb.AppendLine("let parseArgs (rest: string[]) : Dictionary<string, string> * string option =");
        sb.AppendLine("    let values = Dictionary<string, string>()");
        sb.AppendLine("    let mutable body : string option = None");
        sb.AppendLine("    let mutable i = 0");
        sb.AppendLine("    while i < rest.Length do");
        sb.AppendLine("        if rest.[i].StartsWith(\"--\") && i + 1 < rest.Length then");
        sb.AppendLine("            let key = rest.[i].Substring(2)");
        sb.AppendLine("            let value = rest.[i + 1]");
        sb.AppendLine("            if key = \"body\" then body <- Some value else values.[key] <- value");
        sb.AppendLine("            i <- i + 2");
        sb.AppendLine("        else");
        sb.AppendLine("            i <- i + 1");
        sb.AppendLine("    (values, body)");
        sb.AppendLine();

        sb.AppendLine("let fetchOAuth2Token (http: HttpClient) (tokenUrl: string) (clientId: string) (clientSecret: string) (tokenCache: Dictionary<string, string>) : Task<string option> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        let cacheKey = tokenUrl + \"|\" + clientId");
        sb.AppendLine("        match tokenCache.TryGetValue(cacheKey) with");
        sb.AppendLine("        | true, cached -> return Some cached");
        sb.AppendLine("        | false, _ ->");
        sb.AppendLine();
        sb.AppendLine("        let form = new FormUrlEncodedContent(dict [");
        sb.AppendLine("            \"grant_type\", \"client_credentials\"");
        sb.AppendLine("            \"client_id\", clientId");
        sb.AppendLine("            \"client_secret\", clientSecret");
        sb.AppendLine("        ])");
        sb.AppendLine("        let! response = http.PostAsync(tokenUrl, form)");
        sb.AppendLine("        if not response.IsSuccessStatusCode then");
        sb.AppendLine("            return None");
        sb.AppendLine("        else");
        sb.AppendLine();
        sb.AppendLine("        let! text = response.Content.ReadAsStringAsync()");
        sb.AppendLine("        try");
        sb.AppendLine("            use doc = JsonDocument.Parse(text)");
        sb.AppendLine("            match doc.RootElement.TryGetProperty(\"access_token\") with");
        sb.AppendLine("            | false, _ -> return None");
        sb.AppendLine("            | true, tokenEl ->");
        sb.AppendLine("                let token = tokenEl.GetString()");
        sb.AppendLine("                tokenCache.[cacheKey] <- token");
        sb.AppendLine("                return Some token");
        sb.AppendLine("        with :? JsonException ->");
        sb.AppendLine("            // The token endpoint returned a 2xx with a body that isn't valid JSON — treat");
        sb.AppendLine("            // the same as a failed token fetch rather than crashing the whole dispatch.");
        sb.AppendLine("            return None");
        sb.AppendLine("    }");
        sb.AppendLine();

        AppendApplyAuth(sb);
        AppendRunFunction(sb, model);

        sb.AppendLine("let exitCode = run fsi.CommandLineArgs.[1..] |> Async.AwaitTask |> Async.RunSynchronously");
        sb.AppendLine("exit exitCode");

        return sb.ToString();
    }

    private static void AppendOperationsMap(StringBuilder sb, SkillModel model)
    {
        sb.AppendLine("let operations : Map<string, OperationSpec> =");
        sb.AppendLine("    Map.ofList [");
        foreach (var tag in model.Tags)
        {
            foreach (var op in tag.Operations)
            {
                var parameters = op.Parameters.Count == 0
                    ? "[]"
                    : "[ " + string.Join("; ", op.Parameters.Select(p => $"{{ Name = {Literal(p.Name)}; Location = {Literal(LocationKey(p.In))} }}")) + " ]";
                var schemeIds = op.SecuritySchemeIds.Count == 0
                    ? "[]"
                    : "[ " + string.Join("; ", op.SecuritySchemeIds.Select(Literal)) + " ]";
                var bodyContentType = op.RequestBody?.ContentType is { } ct ? $"Some {Literal(ct)}" : "None";

                sb.Append("        ").Append(Literal(op.OperationId)).Append(", { Method = ").Append(Literal(op.Method.Method))
                  .Append("; PathTemplate = ").Append(Literal(op.PathTemplate))
                  .Append("; Parameters = ").Append(parameters)
                  .Append("; HasBody = ").Append(op.RequestBody is not null ? "true" : "false")
                  .Append("; BodyContentType = ").Append(bodyContentType)
                  .Append("; SecuritySchemeIds = ").Append(schemeIds)
                  .Append(" }")
                  .AppendLine();
            }
        }
        sb.AppendLine("    ]");
        sb.AppendLine();
    }

    private static void AppendSchemesMap(StringBuilder sb, SkillModel model)
    {
        sb.AppendLine("let schemes : Map<string, SchemeSpec> =");
        sb.AppendLine("    Map.ofList [");
        foreach (var scheme in model.SecuritySchemes)
        {
            var apiKeyName = scheme.ApiKeyName is { } n ? $"Some {Literal(n)}" : "None";
            var apiKeyLocation = scheme.ApiKeyLocation == ApiKeyLocation.Query ? "Some \"query\""
                : scheme.ApiKeyLocation is not null ? "Some \"header\"" : "None";
            var tokenUrl = scheme.OAuthTokenUrl is { } u ? $"Some {Literal(u)}" : "None";

            sb.Append("        ").Append(Literal(scheme.Id)).Append(", { Id = ").Append(Literal(scheme.Id))
              .Append("; Kind = ").Append(Literal(SchemeKindKey(scheme.Kind)))
              .Append("; ApiKeyName = ").Append(apiKeyName)
              .Append("; ApiKeyLocation = ").Append(apiKeyLocation)
              .Append("; OAuthTokenUrl = ").Append(tokenUrl)
              .Append(" }")
              .AppendLine();
        }
        sb.AppendLine("    ]");
        sb.AppendLine();
    }

    private static void AppendApplyAuth(StringBuilder sb)
    {
        sb.AppendLine("let applyAuth (http: HttpClient) (scheme: SchemeSpec) (secrets: JsonElement option) (query: ResizeArray<string>) (headers: ResizeArray<string * string>) (tokenCache: Dictionary<string, string>) : Task<unit> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        match scheme.Kind with");
        sb.AppendLine("        | \"apiKey\" ->");
        sb.AppendLine("            match schemeSecret secrets scheme.Id \"apiKey\" with");
        sb.AppendLine("            | None -> eprintfn \"warning: no apiKey configured for scheme '%s' in secrets.json — sending unauthenticated.\" scheme.Id");
        sb.AppendLine("            | Some key ->");
        sb.AppendLine("                let name = scheme.ApiKeyName |> Option.defaultValue \"\"");
        sb.AppendLine("                if scheme.ApiKeyLocation = Some \"query\" then");
        sb.AppendLine("                    query.Add(sprintf \"%s=%s\" (Uri.EscapeDataString(name)) (Uri.EscapeDataString(key)))");
        sb.AppendLine("                else");
        sb.AppendLine("                    headers.Add((name, key))");
        sb.AppendLine("        | \"bearer\" ->");
        sb.AppendLine("            match schemeSecret secrets scheme.Id \"bearerToken\" with");
        sb.AppendLine("            | None -> eprintfn \"warning: no bearerToken configured for scheme '%s' in secrets.json — sending unauthenticated.\" scheme.Id");
        sb.AppendLine("            | Some token -> headers.Add((\"Authorization\", sprintf \"Bearer %s\" token))");
        sb.AppendLine("        | \"basic\" ->");
        sb.AppendLine("            let user = schemeSecret secrets scheme.Id \"username\"");
        sb.AppendLine("            let pass = schemeSecret secrets scheme.Id \"password\"");
        sb.AppendLine("            match user, pass with");
        sb.AppendLine("            | Some u, Some p ->");
        sb.AppendLine("                let encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes(sprintf \"%s:%s\" u p))");
        sb.AppendLine("                headers.Add((\"Authorization\", sprintf \"Basic %s\" encoded))");
        sb.AppendLine("            | _ -> eprintfn \"warning: no username/password configured for scheme '%s' in secrets.json — sending unauthenticated.\" scheme.Id");
        sb.AppendLine("        | \"oauth2\" ->");
        sb.AppendLine("            let clientId = schemeSecret secrets scheme.Id \"clientId\"");
        sb.AppendLine("            let clientSecret = schemeSecret secrets scheme.Id \"clientSecret\"");
        sb.AppendLine("            let tokenUrl = (schemeSecret secrets scheme.Id \"tokenUrl\") |> Option.orElse scheme.OAuthTokenUrl");
        sb.AppendLine("            match clientId, clientSecret, tokenUrl with");
        sb.AppendLine("            | Some cid, Some cs, Some url ->");
        sb.AppendLine("                let! token = fetchOAuth2Token http url cid cs tokenCache");
        sb.AppendLine("                match token with");
        sb.AppendLine("                | Some t -> headers.Add((\"Authorization\", sprintf \"Bearer %s\" t))");
        sb.AppendLine("                | None -> eprintfn \"warning: failed to obtain an OAuth2 token for scheme '%s' — sending unauthenticated.\" scheme.Id");
        sb.AppendLine("            | _ -> eprintfn \"warning: no clientId/clientSecret/tokenUrl configured for scheme '%s' in secrets.json — sending unauthenticated.\" scheme.Id");
        sb.AppendLine("        | _ -> eprintfn \"warning: scheme '%s' (%s) is not a supported auth kind — sending unauthenticated.\" scheme.Id scheme.Kind");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendRunFunction(StringBuilder sb, SkillModel model)
    {
        sb.AppendLine("let run (args: string[]) : Task<int> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        if args.Length = 0 || args.[0] = \"-h\" || args.[0] = \"--help\" then");
        sb.AppendLine("            eprintfn \"Usage: dotnet fsi call.fsx -- <operationId> [--<param> <value> ...] [--body <json|@file>]\"");
        sb.AppendLine("            eprintfn \"Known operations: %s\" (String.concat \", \" (operations.Keys |> Seq.sort))");
        sb.AppendLine("            return 2");
        sb.AppendLine("        else");
        sb.AppendLine();
        sb.AppendLine("        let operationId = args.[0]");
        sb.AppendLine("        match operations.TryFind(operationId) with");
        sb.AppendLine("        | None ->");
        sb.AppendLine("            eprintfn \"Unknown operationId '%s'.\" operationId");
        sb.AppendLine("            eprintfn \"Known operations: %s\" (String.concat \", \" (operations.Keys |> Seq.sort))");
        sb.AppendLine("            return 2");
        sb.AppendLine("        | Some op ->");
        sb.AppendLine();
        sb.AppendLine("        let (paramValues, bodyOpt) = parseArgs (args.[1..])");
        sb.AppendLine("        let secrets = loadSecrets ()");
        sb.AppendLine();
        sb.AppendLine($"        let configuredBaseUrl = (topLevelSecret secrets \"baseUrl\") |> Option.defaultValue {Literal(model.BaseUrl ?? string.Empty)}");
        sb.AppendLine("        let baseUrl =");
        sb.AppendLine("            match Environment.GetEnvironmentVariable(\"API2SKILL_BASE_URL\") with");
        sb.AppendLine("            | null -> configuredBaseUrl");
        sb.AppendLine("            | v -> v");
        sb.AppendLine("        if String.IsNullOrWhiteSpace(baseUrl) then");
        sb.AppendLine("            eprintfn \"No base URL configured. Set API2SKILL_BASE_URL or add \\\"baseUrl\\\" to secrets.json.\"");
        sb.AppendLine("            return 2");
        sb.AppendLine("        else");
        sb.AppendLine();
        sb.AppendLine("        let mutable path = op.PathTemplate");
        sb.AppendLine("        let query = ResizeArray<string>()");
        sb.AppendLine("        let headers = ResizeArray<string * string>()");
        sb.AppendLine("        for p in op.Parameters do");
        sb.AppendLine("            match paramValues.TryGetValue(p.Name) with");
        sb.AppendLine("            | false, _ -> ()");
        sb.AppendLine("            | true, value ->");
        sb.AppendLine("                match p.Location with");
        sb.AppendLine("                | \"path\" -> path <- path.Replace(\"{\" + p.Name + \"}\", Uri.EscapeDataString(value))");
        sb.AppendLine("                | \"query\" -> query.Add(sprintf \"%s=%s\" (Uri.EscapeDataString(p.Name)) (Uri.EscapeDataString(value)))");
        sb.AppendLine("                | \"header\" -> headers.Add((p.Name, value))");
        sb.AppendLine("                | _ -> ()");
        sb.AppendLine();
        sb.AppendLine("        use handler = new HttpClientHandler()");
        sb.AppendLine($"        let insecureDefault = {Literal(model.InsecureDefault ? "1" : "0")}");
        sb.AppendLine("        let insecure =");
        sb.AppendLine("            match Environment.GetEnvironmentVariable(\"API2SKILL_INSECURE\") with");
        sb.AppendLine("            | null -> insecureDefault");
        sb.AppendLine("            | v -> v");
        sb.AppendLine("        if insecure = \"1\" then");
        sb.AppendLine("            // Dev-only: accepts self-signed/invalid TLS certificates. Never enable in production.");
        sb.AppendLine("            handler.ServerCertificateCustomValidationCallback <- HttpClientHandler.DangerousAcceptAnyServerCertificateValidator");
        sb.AppendLine("        use http = new HttpClient(handler)");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("            let tokenCache = Dictionary<string, string>()");
        sb.AppendLine("            for schemeId in op.SecuritySchemeIds do");
        sb.AppendLine("                match schemes.TryFind(schemeId) with");
        sb.AppendLine("                | None -> ()");
        sb.AppendLine("                | Some scheme -> do! applyAuth http scheme secrets query headers tokenCache");
        sb.AppendLine();
        sb.AppendLine("            let url =");
        sb.AppendLine("                baseUrl.TrimEnd('/') + path +");
        sb.AppendLine("                (if query.Count > 0 then \"?\" + String.concat \"&\" query else \"\")");
        sb.AppendLine();
        sb.AppendLine("            let invalidHeaderName =");
        sb.AppendLine("                headers |> Seq.tryPick (fun (n, v) -> if v.IndexOfAny([| '\\r'; '\\n' |]) >= 0 then Some n else None)");
        sb.AppendLine("            if invalidHeaderName.IsSome then");
        sb.AppendLine("                eprintfn \"Invalid value for header '%s': control characters are not allowed.\" invalidHeaderName.Value");
        sb.AppendLine("                return 2");
        sb.AppendLine("            else");
        sb.AppendLine();
        sb.AppendLine("            use request = new HttpRequestMessage(HttpMethod(op.Method), url)");
        sb.AppendLine("            for (name, value) in headers do");
        sb.AppendLine("                request.Headers.TryAddWithoutValidation(name, value) |> ignore");
        sb.AppendLine();
        sb.AppendLine("            if op.HasBody then");
        sb.AppendLine("                let bodyText = bodyOpt |> Option.defaultValue \"{}\"");
        sb.AppendLine("                let resolvedBody = if bodyText.StartsWith('@') then IO.File.ReadAllText(bodyText.Substring(1)) else bodyText");
        sb.AppendLine("                let contentType = op.BodyContentType |> Option.defaultValue \"application/json\"");
        sb.AppendLine("                request.Content <- new StringContent(resolvedBody, Encoding.UTF8, contentType)");
        sb.AppendLine();
        sb.AppendLine("            let! response = http.SendAsync(request)");
        sb.AppendLine("            let! responseText = response.Content.ReadAsStringAsync()");
        sb.AppendLine("            printfn \"%s\" responseText");
        sb.AppendLine("            if not response.IsSuccessStatusCode then");
        sb.AppendLine("                eprintfn \"HTTP %d %s\" (int response.StatusCode) (string response.StatusCode)");
        sb.AppendLine("                return 1");
        sb.AppendLine("            else");
        sb.AppendLine("                return 0");
        sb.AppendLine("        with");
        sb.AppendLine("        | :? HttpRequestException as ex ->");
        sb.AppendLine("            eprintfn \"Network error calling %s: %s\" baseUrl ex.Message");
        sb.AppendLine("            return 3");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string LocationKey(ParameterLocation location) => location switch
    {
        ParameterLocation.Path => "path",
        ParameterLocation.Header => "header",
        _ => "query",
    };

    private static string SchemeKindKey(SecuritySchemeKind kind) => kind switch
    {
        SecuritySchemeKind.ApiKey => "apiKey",
        SecuritySchemeKind.Bearer => "bearer",
        SecuritySchemeKind.Basic => "basic",
        SecuritySchemeKind.OAuth2 => "oauth2",
        _ => "unsupported",
    };

    /// <summary>Renders an F# string literal (escaping rules are the same subset C# uses).</summary>
    private static string Literal(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
