using System.Text;
using Api2Skill.Model;

namespace Api2Skill.Emit;

/// <summary>
/// The <c>.fsx</c> emitter (D3/US4): an F# script run via <c>dotnet fsi call.fsx --</c>. Ships
/// with the .NET SDK — no extra install. Feature parity with <see cref="CsFileEmitter"/>: all
/// four auth schemes, the untrusted-HTTPS opt-in, and a clean network-error message.
///
/// F# scripts locate their own directory via the compiler-provided <c>__SOURCE_DIRECTORY__</c>
/// constant (verified empirically — the F# analogue of the <c>[CallerFilePath]</c> trick
/// <see cref="CsFileEmitter"/> needs, but built into the language). Async flow uses F#'s
/// <c>task { }</c> computation expression throughout, converted to synchronous execution only
/// once, at the very end, via <c>Async.AwaitTask |> Async.RunSynchronously</c>.
/// </summary>
public sealed class FsxEmitter : IScriptEmitter
{
    public string Key => "fsx";

    public string FileExtension => "fsx";

    public string RunnerDescription => "dotnet fsi scripts/call.fsx --";

    public void Emit(SkillModel model, DirectoryInfo skillDirectory)
    {
        var scriptsDirectory = Directory.CreateDirectory(Path.Combine(skillDirectory.FullName, "scripts"));
        File.WriteAllText(Path.Combine(scriptsDirectory.FullName, "call.fsx"), Generate(model));
    }

    private static string Generate(SkillModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by api2skill — do not edit by hand; re-run the generator instead.");
        sb.AppendLine("// Usage: dotnet fsi call.fsx -- <operationId> [--<param> <value> ...] [--body <json|@file>]");
        sb.AppendLine("open System");
        sb.AppendLine("open System.Collections.Generic");
        sb.AppendLine("open System.Diagnostics");
        sb.AppendLine("open System.IO");
        sb.AppendLine("open System.Net");
        sb.AppendLine("open System.Net.Http");
        sb.AppendLine("open System.Security.Cryptography");
        sb.AppendLine("open System.Text");
        sb.AppendLine("open System.Text.Json");
        sb.AppendLine("open System.Text.Json.Nodes");
        sb.AppendLine("open System.Threading.Tasks");
        sb.AppendLine();

        sb.AppendLine("type ParamSpec = { Name: string; Location: string }");
        sb.AppendLine("type OperationSpec = { Method: string; PathTemplate: string; Parameters: ParamSpec list; HasBody: bool; BodyContentType: string option; SecuritySchemeIds: string list; AuthProfileNames: string list }");
        sb.AppendLine("type SchemeSpec = { Id: string; Kind: string; ApiKeyName: string option; ApiKeyLocation: string option; OAuthTokenUrl: string option }");
        sb.AppendLine("type TokenResponse = { AccessToken: string; RefreshToken: string option; ExpiresIn: int; IdToken: string option }");
        sb.AppendLine();
        sb.AppendLine("exception AuthResolutionException of string");
        sb.AppendLine();

        AppendOperationsMap(sb, model);
        AppendSchemesMap(sb, model);

        sb.AppendLine("let secretsPath = IO.Path.Combine(__SOURCE_DIRECTORY__, \"..\", \"secrets.json\")");
        sb.AppendLine();
        sb.AppendLine("let loadSecrets () : JsonElement option =");
        sb.AppendLine("    if IO.File.Exists(secretsPath) then");
        sb.AppendLine("        try");
        sb.AppendLine("            use doc = JsonDocument.Parse(IO.File.ReadAllText(secretsPath))");
        sb.AppendLine("            Some (doc.RootElement.Clone())");
        sb.AppendLine("        with :? JsonException as ex ->");
        sb.AppendLine("            eprintfn \"warning: secrets.json is not valid JSON (%s); proceeding as if no secrets were configured.\" ex.Message");
        sb.AppendLine("            None");
        sb.AppendLine("    else");
        sb.AppendLine("        None");
        sb.AppendLine();
        sb.AppendLine("let topLevelSecret (secrets: JsonElement option) (key: string) : string option =");
        sb.AppendLine("    match secrets with");
        sb.AppendLine("    | None -> None");
        sb.AppendLine("    | Some root ->");
        sb.AppendLine("        match root.TryGetProperty(key) with");
        sb.AppendLine("        | true, v -> Some (v.GetString())");
        sb.AppendLine("        | false, _ -> None");
        sb.AppendLine();
        sb.AppendLine("let schemeSecret (secrets: JsonElement option) (schemeId: string) (key: string) : string option =");
        sb.AppendLine("    match secrets with");
        sb.AppendLine("    | None -> None");
        sb.AppendLine("    | Some root ->");
        sb.AppendLine("        match root.TryGetProperty(schemeId) with");
        sb.AppendLine("        | false, _ -> None");
        sb.AppendLine("        | true, entry ->");
        sb.AppendLine("            match entry.TryGetProperty(key) with");
        sb.AppendLine("            | true, v -> Some (v.GetString())");
        sb.AppendLine("            | false, _ -> None");
        sb.AppendLine();

        sb.AppendLine("let authConfigPath = IO.Path.Combine(__SOURCE_DIRECTORY__, \"..\", \"auth.json\")");
        sb.AppendLine();
        sb.AppendLine("let loadAuthConfig () : JsonElement option =");
        sb.AppendLine("    if IO.File.Exists(authConfigPath) then");
        sb.AppendLine("        try");
        sb.AppendLine("            use doc = JsonDocument.Parse(IO.File.ReadAllText(authConfigPath))");
        sb.AppendLine("            Some (doc.RootElement.Clone())");
        sb.AppendLine("        with :? JsonException as ex ->");
        sb.AppendLine("            raise (AuthResolutionException (sprintf \"auth.json is not valid JSON (%s).\" ex.Message))");
        sb.AppendLine("    else");
        sb.AppendLine("        None");
        sb.AppendLine();
        sb.AppendLine("let getProp (el: JsonElement) (name: string) : string =");
        sb.AppendLine("    match el.TryGetProperty(name) with");
        sb.AppendLine("    | true, v -> (match v.GetString() with | null -> \"\" | s -> s)");
        sb.AppendLine("    | false, _ -> \"\"");
        sb.AppendLine();
        sb.AppendLine("let findProfile (profiles: JsonElement option) (name: string) : JsonElement option =");
        sb.AppendLine("    match profiles with");
        sb.AppendLine("    | Some arr when arr.ValueKind = JsonValueKind.Array ->");
        sb.AppendLine("        arr.EnumerateArray()");
        sb.AppendLine("        |> Seq.tryFind (fun p -> match p.TryGetProperty(\"name\") with | true, n -> n.GetString() = name | false, _ -> false)");
        sb.AppendLine("    | _ -> None");
        sb.AppendLine();
        sb.AppendLine("let resolveSecretOrLiteral (raw: string) (secrets: JsonElement option) : string =");
        sb.AppendLine("    if raw.StartsWith(\"{secret:\") && raw.EndsWith(\"}\") then");
        sb.AppendLine("        let key = raw.Substring(8, raw.Length - 9)");
        sb.AppendLine("        let found =");
        sb.AppendLine("            match secrets with");
        sb.AppendLine("            | None -> None");
        sb.AppendLine("            | Some root ->");
        sb.AppendLine("                match root.TryGetProperty(key) with");
        sb.AppendLine("                | true, value when value.GetString() <> null -> Some (value.GetString())");
        sb.AppendLine("                | _ -> None");
        sb.AppendLine("        match found with");
        sb.AppendLine("        | Some s -> s");
        sb.AppendLine("        | None -> raise (AuthResolutionException (sprintf \"secrets.json has no value for \\\"%s\\\" (referenced by auth.json).\" key))");
        sb.AppendLine("    else");
        sb.AppendLine("        raw");
        sb.AppendLine();
        sb.AppendLine("let parseArgs (rest: string[]) : Dictionary<string, string> * string option =");
        sb.AppendLine("    let values = Dictionary<string, string>()");
        sb.AppendLine("    let mutable body : string option = None");
        sb.AppendLine("    let mutable i = 0");
        sb.AppendLine("    while i < rest.Length do");
        sb.AppendLine("        if rest.[i].StartsWith(\"--\") && i + 1 < rest.Length then");
        sb.AppendLine("            let key = rest.[i].Substring(2)");
        sb.AppendLine("            let value = rest.[i + 1]");
        sb.AppendLine("            if key = \"body\" then body <- Some value else values.[key] <- value");
        sb.AppendLine("            i <- i + 2");
        sb.AppendLine("        else");
        sb.AppendLine("            i <- i + 1");
        sb.AppendLine("    (values, body)");
        sb.AppendLine();

        sb.AppendLine("let fetchOAuth2Token (http: HttpClient) (tokenUrl: string) (clientId: string) (clientSecret: string) (tokenCache: Dictionary<string, string>) : Task<string option> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        let cacheKey = tokenUrl + \"|\" + clientId");
        sb.AppendLine("        match tokenCache.TryGetValue(cacheKey) with");
        sb.AppendLine("        | true, cached -> return Some cached");
        sb.AppendLine("        | false, _ ->");
        sb.AppendLine();
        sb.AppendLine("        let form = new FormUrlEncodedContent(dict [");
        sb.AppendLine("            \"grant_type\", \"client_credentials\"");
        sb.AppendLine("            \"client_id\", clientId");
        sb.AppendLine("            \"client_secret\", clientSecret");
        sb.AppendLine("        ])");
        sb.AppendLine("        let! response = http.PostAsync(tokenUrl, form)");
        sb.AppendLine("        if not response.IsSuccessStatusCode then");
        sb.AppendLine("            return None");
        sb.AppendLine("        else");
        sb.AppendLine();
        sb.AppendLine("        let! text = response.Content.ReadAsStringAsync()");
        sb.AppendLine("        try");
        sb.AppendLine("            use doc = JsonDocument.Parse(text)");
        sb.AppendLine("            match doc.RootElement.TryGetProperty(\"access_token\") with");
        sb.AppendLine("            | false, _ -> return None");
        sb.AppendLine("            | true, tokenEl ->");
        sb.AppendLine("                let token = tokenEl.GetString()");
        sb.AppendLine("                tokenCache.[cacheKey] <- token");
        sb.AppendLine("                return Some token");
        sb.AppendLine("        with :? JsonException ->");
        sb.AppendLine("            // The token endpoint returned a 2xx with a body that isn't valid JSON — treat");
        sb.AppendLine("            // the same as a failed token fetch rather than crashing the whole dispatch.");
        sb.AppendLine("            return None");
        sb.AppendLine("    }");
        sb.AppendLine();

        AppendApplyAuth(sb);
        AppendOAuthFunctions(sb);
        AppendRunFunction(sb, model);

        sb.AppendLine("let exitCode = run fsi.CommandLineArgs.[1..] |> Async.AwaitTask |> Async.RunSynchronously");
        sb.AppendLine("exit exitCode");

        return sb.ToString();
    }

    private static void AppendOperationsMap(StringBuilder sb, SkillModel model)
    {
        sb.AppendLine("let operations : Map<string, OperationSpec> =");
        sb.AppendLine("    Map.ofList [");
        foreach (var op in EmitterOperations.DistinctByOperationId(model))
        {
            var parameters = op.Parameters.Count == 0
                ? "[]"
                : "[ " + string.Join("; ", op.Parameters.Select(p => $"{{ Name = {Literal(p.Name)}; Location = {Literal(LocationKey(p.In))} }}")) + " ]";
            var schemeIds = op.SecuritySchemeIds.Count == 0
                ? "[]"
                : "[ " + string.Join("; ", op.SecuritySchemeIds.Select(Literal)) + " ]";
            var authProfileNames = op.AuthProfileNames.Count == 0
                ? "[]"
                : "[ " + string.Join("; ", op.AuthProfileNames.Select(Literal)) + " ]";
            var bodyContentType = op.RequestBody?.ContentType is { } ct ? $"Some {Literal(ct)}" : "None";

            sb.Append("        ").Append(Literal(op.OperationId)).Append(", { Method = ").Append(Literal(op.Method.Method))
              .Append("; PathTemplate = ").Append(Literal(op.PathTemplate))
              .Append("; Parameters = ").Append(parameters)
              .Append("; HasBody = ").Append(op.RequestBody is not null ? "true" : "false")
              .Append("; BodyContentType = ").Append(bodyContentType)
              .Append("; SecuritySchemeIds = ").Append(schemeIds)
              .Append("; AuthProfileNames = ").Append(authProfileNames)
              .Append(" }")
              .AppendLine();
        }
        sb.AppendLine("    ]");
        sb.AppendLine();
    }

    private static void AppendSchemesMap(StringBuilder sb, SkillModel model)
    {
        sb.AppendLine("let schemes : Map<string, SchemeSpec> =");
        sb.AppendLine("    Map.ofList [");
        foreach (var scheme in model.SecuritySchemes)
        {
            var apiKeyName = scheme.ApiKeyName is { } n ? $"Some {Literal(n)}" : "None";
            var apiKeyLocation = scheme.ApiKeyLocation == ApiKeyLocation.Query ? "Some \"query\""
                : scheme.ApiKeyLocation is not null ? "Some \"header\"" : "None";
            var tokenUrl = scheme.OAuthTokenUrl is { } u ? $"Some {Literal(u)}" : "None";

            sb.Append("        ").Append(Literal(scheme.Id)).Append(", { Id = ").Append(Literal(scheme.Id))
              .Append("; Kind = ").Append(Literal(SchemeKindKey(scheme.Kind)))
              .Append("; ApiKeyName = ").Append(apiKeyName)
              .Append("; ApiKeyLocation = ").Append(apiKeyLocation)
              .Append("; OAuthTokenUrl = ").Append(tokenUrl)
              .Append(" }")
              .AppendLine();
        }
        sb.AppendLine("    ]");
        sb.AppendLine();
    }

    private static void AppendApplyAuth(StringBuilder sb)
    {
        sb.AppendLine("let applyAuth (http: HttpClient) (scheme: SchemeSpec) (secrets: JsonElement option) (query: ResizeArray<string>) (headers: ResizeArray<string * string>) (tokenCache: Dictionary<string, string>) : Task<unit> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        match scheme.Kind with");
        sb.AppendLine("        | \"apiKey\" ->");
        sb.AppendLine("            match schemeSecret secrets scheme.Id \"apiKey\" with");
        sb.AppendLine("            | None -> eprintfn \"warning: no apiKey configured for scheme '%s' in secrets.json — sending unauthenticated.\" scheme.Id");
        sb.AppendLine("            | Some key ->");
        sb.AppendLine("                let name = scheme.ApiKeyName |> Option.defaultValue \"\"");
        sb.AppendLine("                if scheme.ApiKeyLocation = Some \"query\" then");
        sb.AppendLine("                    query.Add(sprintf \"%s=%s\" (Uri.EscapeDataString(name)) (Uri.EscapeDataString(key)))");
        sb.AppendLine("                else");
        sb.AppendLine("                    headers.Add((name, key))");
        sb.AppendLine("        | \"bearer\" ->");
        sb.AppendLine("            match schemeSecret secrets scheme.Id \"bearerToken\" with");
        sb.AppendLine("            | None -> eprintfn \"warning: no bearerToken configured for scheme '%s' in secrets.json — sending unauthenticated.\" scheme.Id");
        sb.AppendLine("            | Some token -> headers.Add((\"Authorization\", sprintf \"Bearer %s\" token))");
        sb.AppendLine("        | \"basic\" ->");
        sb.AppendLine("            let user = schemeSecret secrets scheme.Id \"username\"");
        sb.AppendLine("            let pass = schemeSecret secrets scheme.Id \"password\"");
        sb.AppendLine("            match user, pass with");
        sb.AppendLine("            | Some u, Some p ->");
        sb.AppendLine("                let encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes(sprintf \"%s:%s\" u p))");
        sb.AppendLine("                headers.Add((\"Authorization\", sprintf \"Basic %s\" encoded))");
        sb.AppendLine("            | _ -> eprintfn \"warning: no username/password configured for scheme '%s' in secrets.json — sending unauthenticated.\" scheme.Id");
        sb.AppendLine("        | \"oauth2\" ->");
        sb.AppendLine("            let clientId = schemeSecret secrets scheme.Id \"clientId\"");
        sb.AppendLine("            let clientSecret = schemeSecret secrets scheme.Id \"clientSecret\"");
        sb.AppendLine("            let tokenUrl = (schemeSecret secrets scheme.Id \"tokenUrl\") |> Option.orElse scheme.OAuthTokenUrl");
        sb.AppendLine("            match clientId, clientSecret, tokenUrl with");
        sb.AppendLine("            | Some cid, Some cs, Some url ->");
        sb.AppendLine("                let! token = fetchOAuth2Token http url cid cs tokenCache");
        sb.AppendLine("                match token with");
        sb.AppendLine("                | Some t -> headers.Add((\"Authorization\", sprintf \"Bearer %s\" t))");
        sb.AppendLine("                | None -> eprintfn \"warning: failed to obtain an OAuth2 token for scheme '%s' — sending unauthenticated.\" scheme.Id");
        sb.AppendLine("            | _ -> eprintfn \"warning: no clientId/clientSecret/tokenUrl configured for scheme '%s' in secrets.json — sending unauthenticated.\" scheme.Id");
        sb.AppendLine("        | _ -> eprintfn \"warning: scheme '%s' (%s) is not a supported auth kind — sending unauthenticated.\" scheme.Id scheme.Kind");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// OAuth2 (US3): PKCE + state, entra-preset endpoint resolution, the interactive `login`
    /// flow (loopback callback + browser launch + headless fallback), token exchange/refresh/
    /// client_credentials, and a file-locked token cache — the F# translation of the identical
    /// logic in CsFileEmitter/CsxEmitter.
    /// </summary>
    private static void AppendOAuthFunctions(StringBuilder sb)
    {
        sb.AppendLine("let generatePkce () : string * string =");
        sb.AppendLine("    let bytes = Array.zeroCreate<byte> 32");
        sb.AppendLine("    RandomNumberGenerator.Fill(bytes)");
        sb.AppendLine("    let verifier = Convert.ToBase64String(bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')");
        sb.AppendLine("    let challengeBytes = SHA256.HashData(Encoding.ASCII.GetBytes(verifier))");
        sb.AppendLine("    let challenge = Convert.ToBase64String(challengeBytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')");
        sb.AppendLine("    (verifier, challenge)");
        sb.AppendLine();

        sb.AppendLine("let generateState () : string =");
        sb.AppendLine("    let bytes = Array.zeroCreate<byte> 16");
        sb.AppendLine("    RandomNumberGenerator.Fill(bytes)");
        sb.AppendLine("    Convert.ToBase64String(bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')");
        sb.AppendLine();

        sb.AppendLine("let parseQuery (query: string) : Dictionary<string, string> =");
        sb.AppendLine("    let result = Dictionary<string, string>(StringComparer.Ordinal)");
        sb.AppendLine("    let q = query.TrimStart('?')");
        sb.AppendLine("    if q.Length > 0 then");
        sb.AppendLine("        for pair in q.Split('&') do");
        sb.AppendLine("            let idx = pair.IndexOf('=')");
        sb.AppendLine("            if idx < 0 then");
        sb.AppendLine("                result.[Uri.UnescapeDataString(pair)] <- \"\"");
        sb.AppendLine("            else");
        sb.AppendLine("                result.[Uri.UnescapeDataString(pair.Substring(0, idx))] <- Uri.UnescapeDataString(pair.Substring(idx + 1))");
        sb.AppendLine("    result");
        sb.AppendLine();

        sb.AppendLine("let tryLaunchBrowser (url: string) : bool =");
        sb.AppendLine("    try");
        sb.AppendLine("        Process.Start(ProcessStartInfo(url, UseShellExecute = true)) |> ignore");
        sb.AppendLine("        true");
        sb.AppendLine("    with _ ->");
        sb.AppendLine("        try");
        sb.AppendLine("            if OperatingSystem.IsMacOS() then");
        sb.AppendLine("                Process.Start(\"open\", url) |> ignore");
        sb.AppendLine("                true");
        sb.AppendLine("            elif OperatingSystem.IsLinux() then");
        sb.AppendLine("                Process.Start(\"xdg-open\", url) |> ignore");
        sb.AppendLine("                true");
        sb.AppendLine("            elif OperatingSystem.IsWindows() then");
        sb.AppendLine("                Process.Start(ProcessStartInfo(\"cmd\", sprintf \"/c start %s\" url, CreateNoWindow = true)) |> ignore");
        sb.AppendLine("                true");
        sb.AppendLine("            else");
        sb.AppendLine("                false");
        sb.AppendLine("        with _ ->");
        sb.AppendLine("            false");
        sb.AppendLine();

        AppendClipboardFunctions(sb);

        sb.AppendLine("let addCallbackPrefixes (listener: HttpListener) (uri: Uri) =");
        sb.AppendLine("    let scheme = uri.Scheme");
        sb.AppendLine("    let port = uri.Port");
        sb.AppendLine("    let host = uri.Host");
        sb.AppendLine("    listener.Prefixes.Add(sprintf \"%s://%s:%d/\" scheme host port) |> ignore");
        sb.AppendLine("    if String.Equals(host, \"localhost\", StringComparison.OrdinalIgnoreCase) then");
        sb.AppendLine("        listener.Prefixes.Add(sprintf \"%s://127.0.0.1:%d/\" scheme port) |> ignore");
        sb.AppendLine("    elif host = \"127.0.0.1\" || host = \"::1\" then");
        sb.AppendLine("        listener.Prefixes.Add(sprintf \"%s://localhost:%d/\" scheme port) |> ignore");
        sb.AppendLine();

        sb.AppendLine("let beginCallbackListener (callbackUrl: string) : HttpListener =");
        sb.AppendLine("    let uri = Uri(callbackUrl)");
        sb.AppendLine("    let listener = new HttpListener()");
        sb.AppendLine("    addCallbackPrefixes listener uri");
        sb.AppendLine("    try");
        sb.AppendLine("        listener.Start()");
        sb.AppendLine("    with :? HttpListenerException as ex ->");
        sb.AppendLine("        raise (AuthResolutionException (sprintf \"Could not start the local OAuth callback listener on %s:%d (%s). Another process may be using this port \\u2014 try a different callbackUrl in auth.json.\" uri.Host uri.Port ex.Message))");
        sb.AppendLine("    listener");
        sb.AppendLine();

        sb.AppendLine("let awaitOAuthCallbackAsync (listener: HttpListener) : Task<Dictionary<string, string>> =");
        sb.AppendLine("    let rec waitForCode () = task {");
        sb.AppendLine("        let! context = listener.GetContextAsync()");
        sb.AppendLine("        let queryString = if isNull (box context.Request.Url) then \"\" else context.Request.Url.Query");
        sb.AppendLine("        let result = parseQuery queryString");
        sb.AppendLine("        if result.ContainsKey(\"code\") || result.ContainsKey(\"error\") then");
        sb.AppendLine("            let page = Encoding.UTF8.GetBytes(\"<html><body>Login complete \\u2014 you can close this window and return to the terminal.</body></html>\")");
        sb.AppendLine("            context.Response.StatusCode <- 200");
        sb.AppendLine("            context.Response.ContentType <- \"text/html; charset=utf-8\"");
        sb.AppendLine("            context.Response.ContentLength64 <- int64 page.Length");
        sb.AppendLine("            context.Response.OutputStream.Write(page, 0, page.Length)");
        sb.AppendLine("            context.Response.Close()");
        sb.AppendLine("            return result");
        sb.AppendLine("        else");
        sb.AppendLine("            context.Response.StatusCode <- 404");
        sb.AppendLine("            context.Response.Close()");
        sb.AppendLine("            return! waitForCode ()");
        sb.AppendLine("    }");
        sb.AppendLine("    task {");
        sb.AppendLine("        try");
        sb.AppendLine("            return! waitForCode ()");
        sb.AppendLine("        finally");
        sb.AppendLine("            listener.Stop()");
        sb.AppendLine("            listener.Close()");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("let resolveOAuthEndpoints (profile: JsonElement) : string option * string option * string list =");
        sb.AppendLine("    let preset = getProp profile \"preset\"");
        sb.AppendLine("    let tenant = getProp profile \"tenant\"");
        sb.AppendLine("    let explicitAuthUrl = match profile.TryGetProperty(\"authUrl\") with | true, v -> Some (v.GetString()) | false, _ -> None");
        sb.AppendLine("    let explicitTokenUrl = match profile.TryGetProperty(\"tokenUrl\") with | true, v -> Some (v.GetString()) | false, _ -> None");
        sb.AppendLine("    let scopes =");
        sb.AppendLine("        match profile.TryGetProperty(\"scopes\") with");
        sb.AppendLine("        | true, scopesEl when scopesEl.ValueKind = JsonValueKind.Array ->");
        sb.AppendLine("            scopesEl.EnumerateArray() |> Seq.choose (fun s -> match s.GetString() with | null -> None | sv -> Some sv) |> List.ofSeq");
        sb.AppendLine("        | _ -> []");
        sb.AppendLine("    if String.Equals(preset, \"entra\", StringComparison.OrdinalIgnoreCase) then");
        sb.AppendLine("        let authUrl = explicitAuthUrl |> Option.orElseWith (fun () -> if tenant.Length > 0 then Some (sprintf \"https://login.microsoftonline.com/%s/oauth2/v2.0/authorize\" tenant) else None)");
        sb.AppendLine("        let tokenUrl = explicitTokenUrl |> Option.orElseWith (fun () -> if tenant.Length > 0 then Some (sprintf \"https://login.microsoftonline.com/%s/oauth2/v2.0/token\" tenant) else None)");
        sb.AppendLine("        let scopesWithOffline = if List.contains \"offline_access\" scopes then scopes else scopes @ [\"offline_access\"]");
        sb.AppendLine("        (authUrl, tokenUrl, scopesWithOffline)");
        sb.AppendLine("    else");
        sb.AppendLine("        (explicitAuthUrl, explicitTokenUrl, scopes)");
        sb.AppendLine();

        sb.AppendLine("let buildAuthorizeUrl (authUrl: string) (clientId: string) (callbackUrl: string) (scopes: string list) (challenge: string) (state: string) (profile: JsonElement) : string =");
        sb.AppendLine("    let qs = ResizeArray<string>()");
        sb.AppendLine("    qs.Add(\"response_type=code\")");
        sb.AppendLine("    qs.Add(sprintf \"client_id=%s\" (Uri.EscapeDataString(clientId)))");
        sb.AppendLine("    qs.Add(sprintf \"redirect_uri=%s\" (Uri.EscapeDataString(callbackUrl)))");
        sb.AppendLine("    qs.Add(sprintf \"code_challenge=%s\" (Uri.EscapeDataString(challenge)))");
        sb.AppendLine("    qs.Add(\"code_challenge_method=S256\")");
        sb.AppendLine("    qs.Add(sprintf \"state=%s\" (Uri.EscapeDataString(state)))");
        sb.AppendLine("    if not (List.isEmpty scopes) then");
        sb.AppendLine("        qs.Add(sprintf \"scope=%s\" (Uri.EscapeDataString(String.concat \" \" scopes)))");
        sb.AppendLine("    match profile.TryGetProperty(\"authorizeRequest\") with");
        sb.AppendLine("    | true, arEl ->");
        sb.AppendLine("        match arEl.TryGetProperty(\"body\") with");
        sb.AppendLine("        | true, bodyEl when bodyEl.ValueKind = JsonValueKind.Object ->");
        sb.AppendLine("            for prop in bodyEl.EnumerateObject() do");
        sb.AppendLine("                qs.Add(sprintf \"%s=%s\" (Uri.EscapeDataString(prop.Name)) (Uri.EscapeDataString(match prop.Value.GetString() with | null -> \"\" | s -> s)))");
        sb.AppendLine("        | _ -> ()");
        sb.AppendLine("    | _ -> ()");
        sb.AppendLine("    let sep = if authUrl.Contains('?') then \"&\" else \"?\"");
        sb.AppendLine("    authUrl + sep + String.concat \"&\" qs");
        sb.AppendLine();

        sb.AppendLine("let postTokenRequestAsync (http: HttpClient) (profile: JsonElement) (tokenUrl: string) (clientId: string) (form: Dictionary<string, string>) (secrets: JsonElement option) : Task<TokenResponse option> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        let clientAuth = getProp profile \"clientAuth\"");
        sb.AppendLine("        let clientSecretRaw = match profile.TryGetProperty(\"clientSecret\") with | true, v -> (match v.GetString() with | null -> None | s -> Some s) | false, _ -> None");
        sb.AppendLine("        let clientSecret =");
        sb.AppendLine("            match clientSecretRaw with");
        sb.AppendLine("            | Some raw when raw.Length > 0 -> Some (resolveSecretOrLiteral raw secrets)");
        sb.AppendLine("            | _ -> None");
        sb.AppendLine();
        sb.AppendLine("        use request = new HttpRequestMessage(HttpMethod.Post, tokenUrl)");
        sb.AppendLine("        match clientAuth, clientSecret with");
        sb.AppendLine("        | \"basic\", Some cs ->");
        sb.AppendLine("            form.Remove(\"client_id\") |> ignore");
        sb.AppendLine("            let basic = Convert.ToBase64String(Encoding.UTF8.GetBytes(sprintf \"%s:%s\" clientId cs))");
        sb.AppendLine("            request.Headers.TryAddWithoutValidation(\"Authorization\", sprintf \"Basic %s\" basic) |> ignore");
        sb.AppendLine("        | _, Some cs ->");
        sb.AppendLine("            form.[\"client_secret\"] <- cs");
        sb.AppendLine("        | _ -> ()");
        sb.AppendLine();
        sb.AppendLine("        match profile.TryGetProperty(\"tokenRequest\") with");
        sb.AppendLine("        | true, trEl ->");
        sb.AppendLine("            match trEl.TryGetProperty(\"headers\") with");
        sb.AppendLine("            | true, hEl when hEl.ValueKind = JsonValueKind.Object ->");
        sb.AppendLine("                for prop in hEl.EnumerateObject() do");
        sb.AppendLine("                    request.Headers.TryAddWithoutValidation(prop.Name, (match prop.Value.GetString() with | null -> \"\" | s -> s)) |> ignore");
        sb.AppendLine("            | _ -> ()");
        sb.AppendLine("            match trEl.TryGetProperty(\"body\") with");
        sb.AppendLine("            | true, bEl when bEl.ValueKind = JsonValueKind.Object ->");
        sb.AppendLine("                for prop in bEl.EnumerateObject() do");
        sb.AppendLine("                    form.[prop.Name] <- (match prop.Value.GetString() with | null -> \"\" | s -> s)");
        sb.AppendLine("            | _ -> ()");
        sb.AppendLine("        | _ -> ()");
        sb.AppendLine();
        sb.AppendLine("        request.Content <- new FormUrlEncodedContent(form)");
        sb.AppendLine("        let! response = http.SendAsync(request)");
        sb.AppendLine("        let! text = response.Content.ReadAsStringAsync()");
        sb.AppendLine("        if not response.IsSuccessStatusCode then");
        sb.AppendLine("            return None");
        sb.AppendLine("        else");
        sb.AppendLine("            try");
        sb.AppendLine("                use doc = JsonDocument.Parse(text)");
        sb.AppendLine("                let root = doc.RootElement");
        sb.AppendLine("                let preferred = match profile.TryGetProperty(\"tokenField\") with | true, tfEl -> (match tfEl.GetString() with | null | \"\" -> \"access_token\" | s -> s) | false, _ -> \"access_token\"");
        sb.AppendLine("                let other = if preferred = \"id_token\" then \"access_token\" else \"id_token\"");
        sb.AppendLine("                let readField (name: string) = match root.TryGetProperty(name) with | true, el -> (match el.GetString() with | null -> None | s -> Some s) | false, _ -> None");
        sb.AppendLine("                let mutable accessToken = readField preferred");
        sb.AppendLine("                if accessToken.IsNone then");
        sb.AppendLine("                    accessToken <- readField other");
        sb.AppendLine("                    match accessToken with");
        sb.AppendLine("                    | Some _ -> eprintfn \"warning: token response missing '%s'; using '%s' instead.\" preferred other");
        sb.AppendLine("                    | None -> ()");
        sb.AppendLine("                match accessToken with");
        sb.AppendLine("                | None -> return None");
        sb.AppendLine("                | Some tokenValue ->");
        sb.AppendLine("                    let refreshToken = readField \"refresh_token\"");
        sb.AppendLine("                    let idToken = readField \"id_token\"");
        sb.AppendLine("                    let expiresIn = match root.TryGetProperty(\"expires_in\") with | true, eiEl -> (match eiEl.TryGetInt32() with | true, ei -> ei | false, _ -> 3600) | false, _ -> 3600");
        sb.AppendLine("                    return Some { AccessToken = tokenValue; RefreshToken = refreshToken; ExpiresIn = expiresIn; IdToken = idToken }");
        sb.AppendLine("            with :? JsonException ->");
        sb.AppendLine("                return None");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("let exchangeCodeForTokenAsync (http: HttpClient) (profile: JsonElement) (tokenUrl: string) (clientId: string) (code: string) (verifier: string) (callbackUrl: string) (secrets: JsonElement option) : Task<TokenResponse option> =");
        sb.AppendLine("    let form = Dictionary<string, string>(StringComparer.Ordinal)");
        sb.AppendLine("    form.[\"grant_type\"] <- \"authorization_code\"");
        sb.AppendLine("    form.[\"code\"] <- code");
        sb.AppendLine("    form.[\"redirect_uri\"] <- callbackUrl");
        sb.AppendLine("    form.[\"code_verifier\"] <- verifier");
        sb.AppendLine("    form.[\"client_id\"] <- clientId");
        sb.AppendLine("    postTokenRequestAsync http profile tokenUrl clientId form secrets");
        sb.AppendLine();

        sb.AppendLine("let fetchClientCredentialsTokenAsync (http: HttpClient) (profile: JsonElement) (tokenUrl: string) (clientId: string) (secrets: JsonElement option) : Task<TokenResponse option> =");
        sb.AppendLine("    let form = Dictionary<string, string>(StringComparer.Ordinal)");
        sb.AppendLine("    form.[\"grant_type\"] <- \"client_credentials\"");
        sb.AppendLine("    form.[\"client_id\"] <- clientId");
        sb.AppendLine("    postTokenRequestAsync http profile tokenUrl clientId form secrets");
        sb.AppendLine();

        sb.AppendLine("let refreshOAuthTokenAsync (http: HttpClient) (profile: JsonElement) (tokenUrl: string) (clientId: string) (refreshToken: string) (secrets: JsonElement option) : Task<TokenResponse option> =");
        sb.AppendLine("    let form = Dictionary<string, string>(StringComparer.Ordinal)");
        sb.AppendLine("    form.[\"grant_type\"] <- \"refresh_token\"");
        sb.AppendLine("    form.[\"refresh_token\"] <- refreshToken");
        sb.AppendLine("    form.[\"client_id\"] <- clientId");
        sb.AppendLine("    postTokenRequestAsync http profile tokenUrl clientId form secrets");
        sb.AppendLine();

        sb.AppendLine("let tokenCachePath = IO.Path.Combine(__SOURCE_DIRECTORY__, \"..\", \".auth-cache.json\")");
        sb.AppendLine();

        sb.AppendLine("let readTokenCacheAsync (path: string) : Task<Dictionary<string, JsonElement>> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        let result = Dictionary<string, JsonElement>(StringComparer.Ordinal)");
        sb.AppendLine("        if IO.File.Exists(path) then");
        sb.AppendLine("            try");
        sb.AppendLine("                let! text = IO.File.ReadAllTextAsync(path)");
        sb.AppendLine("                use doc = JsonDocument.Parse(text)");
        sb.AppendLine("                for prop in doc.RootElement.EnumerateObject() do");
        sb.AppendLine("                    result.[prop.Name] <- prop.Value.Clone()");
        sb.AppendLine("            with :? JsonException -> ()");
        sb.AppendLine("        return result");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("let writeTokenCacheAsync (path: string) (cache: Dictionary<string, JsonElement>) : Task<unit> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        let obj = JsonObject()");
        sb.AppendLine("        for kv in cache do");
        sb.AppendLine("            obj.[kv.Key] <- JsonNode.Parse(kv.Value.GetRawText())");
        sb.AppendLine("        let tmpPath = path + \".tmp-\" + Guid.NewGuid().ToString(\"N\")");
        sb.AppendLine("        do! IO.File.WriteAllTextAsync(tmpPath, obj.ToJsonString(JsonSerializerOptions(WriteIndented = true)))");
        sb.AppendLine("        if not (OperatingSystem.IsWindows()) then");
        sb.AppendLine("            IO.File.SetUnixFileMode(tmpPath, IO.UnixFileMode.UserRead ||| IO.UnixFileMode.UserWrite)");
        sb.AppendLine("        IO.File.Move(tmpPath, path, true)");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("let storeTokenInCache (cache: Dictionary<string, JsonElement>) (profileName: string) (token: TokenResponse) : unit =");
        sb.AppendLine("    let obj = JsonObject()");
        sb.AppendLine("    obj.[\"access_token\"] <- JsonValue.Create(token.AccessToken)");
        sb.AppendLine("    obj.[\"expires_at\"] <- JsonValue.Create(DateTimeOffset.UtcNow.AddSeconds(float token.ExpiresIn).ToString(\"o\"))");
        sb.AppendLine("    (match token.RefreshToken with");
        sb.AppendLine("     | Some rt -> obj.[\"refresh_token\"] <- JsonValue.Create(rt)");
        sb.AppendLine("     | None -> ())");
        sb.AppendLine("    (match token.IdToken with");
        sb.AppendLine("     | Some idt -> obj.[\"id_token\"] <- JsonValue.Create(idt)");
        sb.AppendLine("     | None -> ())");
        sb.AppendLine("    cache.[profileName] <- JsonDocument.Parse(obj.ToJsonString()).RootElement.Clone()");
        sb.AppendLine();

        sb.AppendLine("let withTokenCacheLockAsync<'T> (action: unit -> Task<'T>) : Task<'T> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        let lockPath = tokenCachePath + \".lock\"");
        sb.AppendLine("        let mutable lockStream : IO.FileStream option = None");
        sb.AppendLine("        let mutable attempt = 0");
        sb.AppendLine("        while lockStream.IsNone && attempt < 100 do");
        sb.AppendLine("            try");
        sb.AppendLine("                lockStream <- Some (new IO.FileStream(lockPath, IO.FileMode.OpenOrCreate, IO.FileAccess.ReadWrite, IO.FileShare.None))");
        sb.AppendLine("            with :? IO.IOException ->");
        sb.AppendLine("                do! Task.Delay(50)");
        sb.AppendLine("            attempt <- attempt + 1");
        sb.AppendLine("        if lockStream.IsNone then");
        sb.AppendLine("            raise (AuthResolutionException \"Could not acquire the token cache lock (.auth-cache.json.lock) after multiple attempts \\u2014 another process may be stuck holding it.\")");
        sb.AppendLine("        let stream = lockStream.Value");
        sb.AppendLine("        try");
        sb.AppendLine("            return! action ()");
        sb.AppendLine("        finally");
        sb.AppendLine("            stream.Dispose()");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("let tryClientCredentialsOrFail (http: HttpClient) (profile: JsonElement) (profileName: string) (tokenUrl: string) (clientId: string) (grant: string) (secrets: JsonElement option) (cache: Dictionary<string, JsonElement>) : Task<string> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        if grant = \"client_credentials\" then");
        sb.AppendLine("            let! fetched = fetchClientCredentialsTokenAsync http profile tokenUrl clientId secrets");
        sb.AppendLine("            match fetched with");
        sb.AppendLine("            | Some tr ->");
        sb.AppendLine("                storeTokenInCache cache profileName tr");
        sb.AppendLine("                do! writeTokenCacheAsync tokenCachePath cache");
        sb.AppendLine("                return tr.AccessToken");
        sb.AppendLine("            | None ->");
        sb.AppendLine("                return raise (AuthResolutionException (sprintf \"Failed to obtain a client_credentials token for auth profile '%s'.\" profileName))");
        sb.AppendLine("        else");
        sb.AppendLine("            return raise (AuthResolutionException (sprintf \"No valid or refreshable token for auth profile '%s'. Run: dotnet fsi scripts/call.fsx -- login %s\" profileName profileName))");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("let resolveOAuthAccessTokenAsync (http: HttpClient) (profile: JsonElement) (profileName: string) (secrets: JsonElement option) : Task<string> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        let (_, tokenUrlOpt, _) = resolveOAuthEndpoints profile");
        sb.AppendLine("        match tokenUrlOpt with");
        sb.AppendLine("        | None ->");
        sb.AppendLine("            return raise (AuthResolutionException (sprintf \"Auth profile '%s' (oauth2) has no tokenUrl configured (directly or via a preset).\" profileName))");
        sb.AppendLine("        | Some tokenUrl ->");
        sb.AppendLine();
        sb.AppendLine("        let clientId = resolveSecretOrLiteral (getProp profile \"clientId\") secrets");
        sb.AppendLine("        let grant = getProp profile \"grant\"");
        sb.AppendLine();
        sb.AppendLine("        return! withTokenCacheLockAsync (fun () ->");
        sb.AppendLine("            task {");
        sb.AppendLine("                let! cache = readTokenCacheAsync tokenCachePath");
        sb.AppendLine("                match cache.TryGetValue(profileName) with");
        sb.AppendLine("                | false, _ ->");
        sb.AppendLine("                    return! tryClientCredentialsOrFail http profile profileName tokenUrl clientId grant secrets cache");
        sb.AppendLine("                | true, entry ->");
        sb.AppendLine("                    let expiresAt =");
        sb.AppendLine("                        match entry.TryGetProperty(\"expires_at\") with");
        sb.AppendLine("                        | true, eaEl -> (match DateTimeOffset.TryParse(eaEl.GetString()) with | true, ea -> ea | false, _ -> DateTimeOffset.MinValue)");
        sb.AppendLine("                        | false, _ -> DateTimeOffset.MinValue");
        sb.AppendLine("                    let cachedToken = match entry.TryGetProperty(\"access_token\") with | true, atEl -> (match atEl.GetString() with | null -> None | s -> Some s) | false, _ -> None");
        sb.AppendLine("                    match cachedToken with");
        sb.AppendLine("                    | Some token when expiresAt > DateTimeOffset.UtcNow.AddSeconds(30.0) ->");
        sb.AppendLine("                        return token");
        sb.AppendLine("                    | _ ->");
        sb.AppendLine("                        let refreshToken = match entry.TryGetProperty(\"refresh_token\") with | true, rtEl -> (match rtEl.GetString() with | null -> None | s -> Some s) | false, _ -> None");
        sb.AppendLine("                        match refreshToken with");
        sb.AppendLine("                        | None ->");
        sb.AppendLine("                            return! tryClientCredentialsOrFail http profile profileName tokenUrl clientId grant secrets cache");
        sb.AppendLine("                        | Some rt ->");
        sb.AppendLine("                            let! refreshed = refreshOAuthTokenAsync http profile tokenUrl clientId rt secrets");
        sb.AppendLine("                            match refreshed with");
        sb.AppendLine("                            | Some tr ->");
        sb.AppendLine("                                storeTokenInCache cache profileName tr");
        sb.AppendLine("                                do! writeTokenCacheAsync tokenCachePath cache");
        sb.AppendLine("                                return tr.AccessToken");
        sb.AppendLine("                            | None ->");
        sb.AppendLine("                                return! tryClientCredentialsOrFail http profile profileName tokenUrl clientId grant secrets cache");
        sb.AppendLine("            })");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("let runScriptCommandAsync (command: string) (skillRoot: string) : Task<int * string * string> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        let psi = ProcessStartInfo()");
        sb.AppendLine("        psi.RedirectStandardOutput <- true");
        sb.AppendLine("        psi.RedirectStandardError <- true");
        sb.AppendLine("        psi.UseShellExecute <- false");
        sb.AppendLine("        psi.WorkingDirectory <- skillRoot");
        sb.AppendLine("        if OperatingSystem.IsWindows() then");
        sb.AppendLine("            psi.FileName <- \"cmd.exe\"");
        sb.AppendLine("            psi.ArgumentList.Add(\"/c\") |> ignore");
        sb.AppendLine("            psi.ArgumentList.Add(command) |> ignore");
        sb.AppendLine("        else");
        sb.AppendLine("            psi.FileName <- \"/bin/sh\"");
        sb.AppendLine("            psi.ArgumentList.Add(\"-c\") |> ignore");
        sb.AppendLine("            psi.ArgumentList.Add(command) |> ignore");
        sb.AppendLine("        use proc = Process.Start(psi)");
        sb.AppendLine("        let! stdout = proc.StandardOutput.ReadToEndAsync()");
        sb.AppendLine("        let! stderr = proc.StandardError.ReadToEndAsync()");
        sb.AppendLine("        do! proc.WaitForExitAsync()");
        sb.AppendLine("        return (proc.ExitCode, stdout, stderr)");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("let applyExplicitProfileAsync (http: HttpClient) (profile: JsonElement) (profileName: string) (secrets: JsonElement option) (query: ResizeArray<string>) (headers: ResizeArray<string * string>) : Task<unit> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        let profType = getProp profile \"type\"");
        sb.AppendLine("        match profType with");
        sb.AppendLine("        | \"bearer\" ->");
        sb.AppendLine("            let token = resolveSecretOrLiteral (getProp profile \"token\") secrets");
        sb.AppendLine("            let value = if token.StartsWith(\"Bearer \", StringComparison.OrdinalIgnoreCase) then token else sprintf \"Bearer %s\" token");
        sb.AppendLine("            headers.Add((\"Authorization\", value))");
        sb.AppendLine("        | \"basic\" ->");
        sb.AppendLine("            let user = resolveSecretOrLiteral (getProp profile \"username\") secrets");
        sb.AppendLine("            let pass = resolveSecretOrLiteral (getProp profile \"password\") secrets");
        sb.AppendLine("            let encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes(sprintf \"%s:%s\" user pass))");
        sb.AppendLine("            headers.Add((\"Authorization\", sprintf \"Basic %s\" encoded))");
        sb.AppendLine("        | \"custom\" ->");
        sb.AppendLine("            match profile.TryGetProperty(\"headers\") with");
        sb.AppendLine("            | true, headersEl when headersEl.ValueKind = JsonValueKind.Array ->");
        sb.AppendLine("                for h in headersEl.EnumerateArray() do");
        sb.AppendLine("                    let name = getProp h \"name\"");
        sb.AppendLine("                    let value = resolveSecretOrLiteral (getProp h \"value\") secrets");
        sb.AppendLine("                    headers.Add((name, value))");
        sb.AppendLine("            | _ -> ()");
        sb.AppendLine("        | \"oauth2\" ->");
        sb.AppendLine("            let! accessToken = resolveOAuthAccessTokenAsync http profile profileName secrets");
        sb.AppendLine("            headers.Add((\"Authorization\", sprintf \"Bearer %s\" accessToken))");
        sb.AppendLine("        | \"script\" ->");
        sb.AppendLine("            let command = getProp profile \"command\"");
        sb.AppendLine("            let headerName =");
        sb.AppendLine("                let h = getProp profile \"header\"");
        sb.AppendLine("                if String.IsNullOrEmpty(h) then \"Authorization\" else h");
        sb.AppendLine("            let bearerPrefix =");
        sb.AppendLine("                match profile.TryGetProperty(\"bearerPrefix\") with");
        sb.AppendLine("                | true, v -> v.ValueKind = JsonValueKind.True");
        sb.AppendLine("                | _ -> false");
        sb.AppendLine("            let skillRoot = Path.GetFullPath(Path.Combine(__SOURCE_DIRECTORY__, \"..\"))");
        sb.AppendLine("            let! exitCode, stdout, stderr = runScriptCommandAsync command skillRoot");
        sb.AppendLine("            if exitCode <> 0 then");
        sb.AppendLine("                return raise (AuthResolutionException (sprintf \"Script command for auth profile '%s' exited with code %d: %s\" profileName exitCode (stderr.Trim())))");
        sb.AppendLine("            let token = stdout.Trim()");
        sb.AppendLine("            let value = if bearerPrefix && not (token.StartsWith(\"Bearer \", StringComparison.OrdinalIgnoreCase)) then sprintf \"Bearer %s\" token else token");
        sb.AppendLine("            headers.Add((headerName, value))");
        sb.AppendLine("        | other ->");
        sb.AppendLine("            raise (AuthResolutionException (sprintf \"Auth profile type '%s' is not supported by this generated dispatcher yet.\" other))");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("let loginAsync (profileName: string) : Task<int> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        try");
        sb.AppendLine("            let authConfig = loadAuthConfig ()");
        sb.AppendLine("            let profilesEl =");
        sb.AppendLine("                match authConfig with");
        sb.AppendLine("                | Some cfg -> (match cfg.TryGetProperty(\"profiles\") with | true, p -> Some p | false, _ -> None)");
        sb.AppendLine("                | None -> None");
        sb.AppendLine("            match findProfile profilesEl profileName with");
        sb.AppendLine("            | None ->");
        sb.AppendLine("                eprintfn \"No auth profile named '%s' in auth.json.\" profileName");
        sb.AppendLine("                return 2");
        sb.AppendLine("            | Some profile ->");
        sb.AppendLine();
        sb.AppendLine("            let profType = getProp profile \"type\"");
        sb.AppendLine("            if profType <> \"oauth2\" then");
        sb.AppendLine("                eprintfn \"Profile '%s' is type '%s', not 'oauth2' \\u2014 login is only applicable to oauth2 profiles.\" profileName profType");
        sb.AppendLine("                return 2");
        sb.AppendLine("            else");
        sb.AppendLine();
        sb.AppendLine("            let grant = getProp profile \"grant\"");
        sb.AppendLine("            if grant = \"client_credentials\" then");
        sb.AppendLine("                printfn \"Profile '%s' uses client_credentials \\u2014 not applicable: no interactive login is needed, a token is obtained automatically at call time.\" profileName");
        sb.AppendLine("                return 0");
        sb.AppendLine("            else");
        sb.AppendLine();
        sb.AppendLine("            let (authUrlOpt, tokenUrlOpt, scopes) = resolveOAuthEndpoints profile");
        sb.AppendLine("            match authUrlOpt, tokenUrlOpt with");
        sb.AppendLine("            | None, _ | _, None ->");
        sb.AppendLine("                eprintfn \"Profile '%s' is missing authUrl/tokenUrl (directly or via a preset).\" profileName");
        sb.AppendLine("                return 2");
        sb.AppendLine("            | Some authUrl, Some tokenUrl ->");
        sb.AppendLine();
        sb.AppendLine("            let callbackUrlRaw = getProp profile \"callbackUrl\"");
        sb.AppendLine("            let callbackUrl = if callbackUrlRaw.Length = 0 then \"http://localhost:8400/callback\" else callbackUrlRaw");
        sb.AppendLine("            let secrets = loadSecrets ()");
        sb.AppendLine("            let clientId = resolveSecretOrLiteral (getProp profile \"clientId\") secrets");
        sb.AppendLine();
        sb.AppendLine("            let (verifier, challenge) = generatePkce ()");
        sb.AppendLine("            let state = generateState ()");
        sb.AppendLine("            let authorizeUrl = buildAuthorizeUrl authUrl clientId callbackUrl scopes challenge state profile");
        sb.AppendLine();
        sb.AppendLine("            let callbackListener = beginCallbackListener callbackUrl");
        sb.AppendLine("            printfn \"Listening for OAuth callback on %s ...\" callbackUrl");
        sb.AppendLine();
        sb.AppendLine("            let browserLaunch = getProp profile \"browserLaunch\"");
        sb.AppendLine("            if browserLaunch = \"clipboard\" then");
        sb.AppendLine("                let copied = tryCopyToClipboard authorizeUrl");
        sb.AppendLine("                printfn \"%s\" (if copied then sprintf \"Copied the sign-in URL to your clipboard for profile '%s'. Paste it into your browser:\" profileName else sprintf \"Could not copy the sign-in URL to the clipboard automatically. Open this URL to sign in for profile '%s':\" profileName)");
        sb.AppendLine("                printfn \"%s\" authorizeUrl");
        sb.AppendLine("            else");
        sb.AppendLine("                printfn \"Opening your browser to sign in for profile '%s'...\" profileName");
        sb.AppendLine("                let browserLaunched = tryLaunchBrowser authorizeUrl");
        sb.AppendLine("                printfn \"%s\" (if browserLaunched then \"If it did not open, visit this URL to sign in:\" else \"Could not launch a browser automatically. Open this URL to sign in:\")");
        sb.AppendLine("                printfn \"%s\" authorizeUrl");
        sb.AppendLine();
        sb.AppendLine("            let! callbackParams = awaitOAuthCallbackAsync callbackListener");
        sb.AppendLine();
        sb.AppendLine("            let stateMatches = match callbackParams.TryGetValue(\"state\") with | true, returnedState -> returnedState = state | false, _ -> false");
        sb.AppendLine("            if not stateMatches then");
        sb.AppendLine("                eprintfn \"The callback's state did not match what was sent \\u2014 rejecting (possible CSRF/mix-up). No token was stored. Run login again.\"");
        sb.AppendLine("                return 2");
        sb.AppendLine("            else");
        sb.AppendLine();
        sb.AppendLine("            match callbackParams.TryGetValue(\"code\") with");
        sb.AppendLine("            | false, _ ->");
        sb.AppendLine("                let err = match callbackParams.TryGetValue(\"error\") with | true, e -> e | false, _ -> \"no authorization code was returned\"");
        sb.AppendLine("                eprintfn \"Login failed: %s\" err");
        sb.AppendLine("                return 2");
        sb.AppendLine("            | true, code ->");
        sb.AppendLine();
        sb.AppendLine("            use http = new HttpClient()");
        sb.AppendLine("            let! tokenResponse = exchangeCodeForTokenAsync http profile tokenUrl clientId code verifier callbackUrl secrets");
        sb.AppendLine("            match tokenResponse with");
        sb.AppendLine("            | None ->");
        sb.AppendLine("                eprintfn \"Failed to exchange the authorization code for a token.\"");
        sb.AppendLine("                return 2");
        sb.AppendLine("            | Some tr ->");
        sb.AppendLine();
        sb.AppendLine("            do! withTokenCacheLockAsync (fun () ->");
        sb.AppendLine("                task {");
        sb.AppendLine("                    let! cache = readTokenCacheAsync tokenCachePath");
        sb.AppendLine("                    storeTokenInCache cache profileName tr");
        sb.AppendLine("                    do! writeTokenCacheAsync tokenCachePath cache");
        sb.AppendLine("                })");
        sb.AppendLine();
        sb.AppendLine("            printfn \"Login succeeded for profile '%s'. You can now call operations that use it.\" profileName");
        sb.AppendLine("            return 0");
        sb.AppendLine("        with AuthResolutionException msg ->");
        sb.AppendLine("            eprintfn \"%s\" msg");
        sb.AppendLine("            return 2");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// <c>browserLaunch: "clipboard"</c> (US OAuth manual-browser login): copies the authorize URL
    /// to the system clipboard via native OS tools instead of launching a browser — no new NuGet
    /// dependency, mirroring how <c>tryLaunchBrowser</c> already shells out to <c>open</c>/<c>xdg-open</c>/<c>cmd</c>.
    /// </summary>
    private static void AppendClipboardFunctions(StringBuilder sb)
    {
        sb.AppendLine("let runClipboardCommand (fileName: string) (args: string list) (text: string) : bool =");
        sb.AppendLine("    try");
        sb.AppendLine("        let psi = ProcessStartInfo(fileName, RedirectStandardInput = true, UseShellExecute = false, CreateNoWindow = true)");
        sb.AppendLine("        for a in args do psi.ArgumentList.Add(a)");
        sb.AppendLine("        use proc = Process.Start(psi)");
        sb.AppendLine("        proc.StandardInput.Write(text)");
        sb.AppendLine("        proc.StandardInput.Close()");
        sb.AppendLine("        proc.WaitForExit()");
        sb.AppendLine("        proc.ExitCode = 0");
        sb.AppendLine("    with _ ->");
        sb.AppendLine("        false");
        sb.AppendLine();

        sb.AppendLine("let tryCopyToClipboard (text: string) : bool =");
        sb.AppendLine("    if OperatingSystem.IsMacOS() then");
        sb.AppendLine("        runClipboardCommand \"pbcopy\" [] text");
        sb.AppendLine("    elif OperatingSystem.IsWindows() then");
        sb.AppendLine("        runClipboardCommand \"clip\" [] text");
        sb.AppendLine("    elif OperatingSystem.IsLinux() then");
        sb.AppendLine("        runClipboardCommand \"wl-copy\" [] text");
        sb.AppendLine("        || runClipboardCommand \"xclip\" [\"-selection\"; \"clipboard\"] text");
        sb.AppendLine("        || runClipboardCommand \"xsel\" [\"--clipboard\"; \"--input\"] text");
        sb.AppendLine("    else");
        sb.AppendLine("        false");
        sb.AppendLine();
    }

    private static void AppendRunFunction(StringBuilder sb, SkillModel model)
    {
        sb.AppendLine("let run (args: string[]) : Task<int> =");
        sb.AppendLine("    task {");
        sb.AppendLine("        if args.Length > 0 && args.[0] = \"login\" then");
        sb.AppendLine("            if args.Length < 2 then");
        sb.AppendLine("                eprintfn \"Usage: dotnet fsi call.fsx -- login <profile>\"");
        sb.AppendLine("                return 2");
        sb.AppendLine("            else");
        sb.AppendLine("                return! loginAsync args.[1]");
        sb.AppendLine("        else");
        sb.AppendLine();
        sb.AppendLine("        if args.Length = 0 || args.[0] = \"-h\" || args.[0] = \"--help\" then");
        sb.AppendLine("            eprintfn \"Usage: dotnet fsi call.fsx -- <operationId> [--<param> <value> ...] [--body <json|@file>]\"");
        sb.AppendLine("            eprintfn \"Known operations: %s\" (String.concat \", \" (operations.Keys |> Seq.sort))");
        sb.AppendLine("            return 2");
        sb.AppendLine("        else");
        sb.AppendLine();
        sb.AppendLine("        let operationId = args.[0]");
        sb.AppendLine("        match operations.TryFind(operationId) with");
        sb.AppendLine("        | None ->");
        sb.AppendLine("            eprintfn \"Unknown operationId '%s'.\" operationId");
        sb.AppendLine("            eprintfn \"Known operations: %s\" (String.concat \", \" (operations.Keys |> Seq.sort))");
        sb.AppendLine("            return 2");
        sb.AppendLine("        | Some op ->");
        sb.AppendLine();
        sb.AppendLine("        let (paramValues, bodyOpt) = parseArgs (args.[1..])");
        sb.AppendLine("        let secrets = loadSecrets ()");
        sb.AppendLine();
        sb.AppendLine($"        let configuredBaseUrl = (topLevelSecret secrets \"baseUrl\") |> Option.defaultValue {Literal(model.BaseUrl ?? string.Empty)}");
        sb.AppendLine("        let baseUrl =");
        sb.AppendLine("            match Environment.GetEnvironmentVariable(\"API2SKILL_BASE_URL\") with");
        sb.AppendLine("            | null -> configuredBaseUrl");
        sb.AppendLine("            | v -> v");
        sb.AppendLine("        if String.IsNullOrWhiteSpace(baseUrl) then");
        sb.AppendLine("            eprintfn \"No base URL configured. Set API2SKILL_BASE_URL or add \\\"baseUrl\\\" to secrets.json.\"");
        sb.AppendLine("            return 2");
        sb.AppendLine("        else");
        sb.AppendLine();
        sb.AppendLine("        let mutable path = op.PathTemplate");
        sb.AppendLine("        let query = ResizeArray<string>()");
        sb.AppendLine("        let headers = ResizeArray<string * string>()");
        sb.AppendLine("        for p in op.Parameters do");
        sb.AppendLine("            match paramValues.TryGetValue(p.Name) with");
        sb.AppendLine("            | false, _ -> ()");
        sb.AppendLine("            | true, value ->");
        sb.AppendLine("                match p.Location with");
        sb.AppendLine("                | \"path\" -> path <- path.Replace(\"{\" + p.Name + \"}\", Uri.EscapeDataString(value))");
        sb.AppendLine("                | \"query\" -> query.Add(sprintf \"%s=%s\" (Uri.EscapeDataString(p.Name)) (Uri.EscapeDataString(value)))");
        sb.AppendLine("                | \"header\" -> headers.Add((p.Name, value))");
        sb.AppendLine("                | _ -> ()");
        sb.AppendLine();
        sb.AppendLine("        use handler = new HttpClientHandler()");
        sb.AppendLine($"        let insecureDefault = {Literal(model.InsecureDefault ? "1" : "0")}");
        sb.AppendLine("        let insecure =");
        sb.AppendLine("            match Environment.GetEnvironmentVariable(\"API2SKILL_INSECURE\") with");
        sb.AppendLine("            | null -> insecureDefault");
        sb.AppendLine("            | v -> v");
        sb.AppendLine("        if insecure = \"1\" then");
        sb.AppendLine("            // Dev-only: accepts self-signed/invalid TLS certificates. Never enable in production.");
        sb.AppendLine("            handler.ServerCertificateCustomValidationCallback <- HttpClientHandler.DangerousAcceptAnyServerCertificateValidator");
        sb.AppendLine("        use http = new HttpClient(handler)");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("            let tokenCache = Dictionary<string, string>()");
        sb.AppendLine("            if not (List.isEmpty op.AuthProfileNames) then");
        sb.AppendLine("                let authConfig = loadAuthConfig ()");
        sb.AppendLine("                let profilesEl =");
        sb.AppendLine("                    match authConfig with");
        sb.AppendLine("                    | Some cfg -> (match cfg.TryGetProperty(\"profiles\") with | true, p -> Some p | false, _ -> None)");
        sb.AppendLine("                    | None -> None");
        sb.AppendLine("                for profileName in op.AuthProfileNames do");
        sb.AppendLine("                    match findProfile profilesEl profileName with");
        sb.AppendLine("                    | None -> raise (AuthResolutionException (sprintf \"auth.json has no profile named '%s' (referenced by operation '%s').\" profileName operationId))");
        sb.AppendLine("                    | Some profile -> do! applyExplicitProfileAsync http profile profileName secrets query headers");
        sb.AppendLine("            else");
        sb.AppendLine("                for schemeId in op.SecuritySchemeIds do");
        sb.AppendLine("                    match schemes.TryFind(schemeId) with");
        sb.AppendLine("                    | None -> ()");
        sb.AppendLine("                    | Some scheme -> do! applyAuth http scheme secrets query headers tokenCache");
        sb.AppendLine();
        sb.AppendLine("            let url =");
        sb.AppendLine("                baseUrl.TrimEnd('/') + path +");
        sb.AppendLine("                (if query.Count > 0 then \"?\" + String.concat \"&\" query else \"\")");
        sb.AppendLine();
        sb.AppendLine("            let invalidHeaderName =");
        sb.AppendLine("                headers |> Seq.tryPick (fun (n, v) -> if v.IndexOfAny([| '\\r'; '\\n' |]) >= 0 then Some n else None)");
        sb.AppendLine("            if invalidHeaderName.IsSome then");
        sb.AppendLine("                eprintfn \"Invalid value for header '%s': control characters are not allowed.\" invalidHeaderName.Value");
        sb.AppendLine("                return 2");
        sb.AppendLine("            else");
        sb.AppendLine();
        sb.AppendLine("            use request = new HttpRequestMessage(HttpMethod(op.Method), url)");
        sb.AppendLine("            for (name, value) in headers do");
        sb.AppendLine("                request.Headers.TryAddWithoutValidation(name, value) |> ignore");
        sb.AppendLine();
        sb.AppendLine("            if op.HasBody then");
        sb.AppendLine("                let bodyText = bodyOpt |> Option.defaultValue \"{}\"");
        sb.AppendLine("                let resolvedBody = if bodyText.StartsWith('@') then IO.File.ReadAllText(bodyText.Substring(1)) else bodyText");
        sb.AppendLine("                let contentType = op.BodyContentType |> Option.defaultValue \"application/json\"");
        sb.AppendLine("                request.Content <- new StringContent(resolvedBody, Encoding.UTF8, contentType)");
        sb.AppendLine();
        sb.AppendLine("            let! response = http.SendAsync(request)");
        sb.AppendLine("            let! responseText = response.Content.ReadAsStringAsync()");
        sb.AppendLine("            printfn \"%s\" responseText");
        sb.AppendLine("            if not response.IsSuccessStatusCode then");
        sb.AppendLine("                eprintfn \"HTTP %d %s\" (int response.StatusCode) (string response.StatusCode)");
        sb.AppendLine("                return 1");
        sb.AppendLine("            else");
        sb.AppendLine("                return 0");
        sb.AppendLine("        with");
        sb.AppendLine("        | AuthResolutionException msg ->");
        sb.AppendLine("            eprintfn \"%s\" msg");
        sb.AppendLine("            return 2");
        sb.AppendLine("        | :? HttpRequestException as ex ->");
        sb.AppendLine("            eprintfn \"Network error calling %s: %s\" baseUrl ex.Message");
        sb.AppendLine("            return 3");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string LocationKey(ParameterLocation location) => location switch
    {
        ParameterLocation.Path => "path",
        ParameterLocation.Header => "header",
        _ => "query",
    };

    private static string SchemeKindKey(SecuritySchemeKind kind) => kind switch
    {
        SecuritySchemeKind.ApiKey => "apiKey",
        SecuritySchemeKind.Bearer => "bearer",
        SecuritySchemeKind.Basic => "basic",
        SecuritySchemeKind.OAuth2 => "oauth2",
        _ => "unsupported",
    };

    /// <summary>Renders an F# string literal (escaping rules are the same subset C# uses).</summary>
    private static string Literal(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
